openshift/lightspeed-service

Makefile
Adding a Makefile to trigger rehearsal job in PROW: https://github.com/openshift/release/pull/45457/files
=> Adding a Makefile to kickoff PROW pjrehearse

modules/conversation_cache.py, modules/yaml_generator.py, ols.py
=> add an extremely primitive conversation caching implementation

src/logger.py
Adding a class for logging functionalities. Once the class is merged, I will start connecting it to the other services.
=> Add Logging class to start aggregating logging functionalities

gradio/main.py, readme.md, requirements.txt
=> Add a minimal gradio interface with history

Containerfile, README.md, config/kustomization.yaml, config/namespace.yaml, config/ols-client-test-rbac.yaml, config/ols-client-test.yaml, config/ols-client.yaml, config/ols-rbac.yaml, config/ols.yaml
Implementing basic kube-rbac-proxy authentication.
- Related Issue # https://issues.redhat.com/browse/OLS-19?filter=-3
Tested in my local environment with the below command
```
export OLS_IMAGE=quay.io/vchalla/lightspeed-service:latest
kustomize build . | envsubst | oc apply -f -
```
Verified valid responses from pod logs.
```
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:     10.128.2.151:0 - "GET /docs HTTP/1.1" 200 OK
```
```
*   Trying 172.30.61.91:8443...
* Connected to ols-proxy.ols.svc (172.30.61.91) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: …
```
=> Implementing kube-rbac-proxy authentication/authorization

Containerfile, build-container.sh
Updating Containerfile to use UBI-based Python 3.11. 
- Updating Containerfile to use UBI-based Python 3.11. 
- Adding environment variables to optimize Python-based images and improve stdout logging behavior in Kubernetes environments. 
- Add explicit files and directories to the image to avoid accidental information leaking during the dev process. 
- Adding script wrapper to help developers build and test the container image locally
- Closes #
To test the changes, execute the `./build-container.sh` and run the resulting container image.
Run image locally and successfully interacted with the …
=> Updating Containerfile to use UBI-based Python 3.11

.gitignore, CONTRIBUTING.md, README.md
=> Adding contributing guide

README.md, modules/gradio_ui.py, ols.py
=> embed the gradio ui within the fastapi server

Makefile, README.md, modules/gradio_ui.py, scripts/build-container.sh
=> Add a Make run target, fix up port references to be consistent on 8080

ols.py
=> Include the user query in the conversation cache

README.md
=> Mention the published lightspeed image on quay.io in readme

scripts/build-container.sh
=> Add env vars for controlling image build behavior

.gitignore, default.env, modules/gradio_ui.py, ols.py, src/config.py, src/logger.py
Updating logging class.
Wrapped gradio interface into a class to remove gradio import from ols.py 
Created env variable to enable/disable the loading of the local UI interface 
Connecting ols.py to the logging class as a single instance on run. 
Minor updates to script and env file to reflect changes.
See intro.
- Closes #
To test this change I generated the container locally and made sure it is still operational interacting with the LLM.
=> Adding class to handle configuration and first interconnection of logging class

Makefile, src/ui/gradio_ui.py
=> Specify gradio path at mount time, not instantiation time

Containerfile
=> Set permissions so OLS image can run as arbitrary uids

tests/integration/test_ols.py, tests/mock_classes/langchain_interface.py
* moves mocking langchain interface class to separate file
* updates ols test to use new method
N/A
Tests still pass locally
=> Refactor base OLS endpoint tests

app/main.py, src/ui/gradio_ui.py, utils/config.py, utils/logger.py
Case insensitive string for OLS_ENABLE_UI
https://github.com/openshift/lightspeed-service/pull/18#discussion_r1400985521
Making logfile name and size configurable
https://github.com/openshift/lightspeed-service/pull/18#discussion_r1400993505
Use logger in gradio class
https://github.com/openshift/lightspeed-service/pull/18#discussion_r1400969721
Remove hardcoded default fallback for BASE_COMPLETION_MODEL (return None if not defined) https://github.com/openshift/lightspeed-service/pull/18#discussion_r1400987617
- Closes #
=> OLS-38: Complete work for OLS-38

app/endpoints/ols.py, src/indexer/indexer.py, src/ui/gradio_ui.py
More idiomatic comparison with `None` value. In Python comparison with `None` is usually performed using `is` and `not is` operators
- It should be covered by unit tests
=> More idiomatic comparison with None value

app/main.py, tests/integration/test_ols.py, utils/json_tools.py
=> Removed unused imports

manifests/ols-rbac.yaml, manifests/ols-redis.yaml, manifests/ols.yaml
- Added use of SCC to run OLS in OpenShift
- Container image names have been replaced with direct link instead of variables
This is a preparatory work for completing the task https://issues.redhat.com/browse/OLS-50
- Closes #
=> chore: update deployment manifests

README.md
Just fixed typo in README.md
- N/A
=> Fixed typo (trivial)

src/indexer/indexer.py
Named lambdas (e.g. lambdas assigned to variable) can be transformed into a normal function which might be easier to document and test.
- IMHO covered by existing automatic tests
=> Named lambda is the same as normal function

src/query_helpers/question_validator.py, tests/unit/query_helpers/test_question_validator.py
* adds valueerror to the validator
* tests the validator
N/A
There are tests!
=> Testing of question validator

tests/unit/utils/test_json_tools.py
Unit tests for `parse_json_markdown` function. Checks correct inputs and also some incorrect ones.
- It is part of unit testing job
=> Unit tests for `parse_json_markdown` function

Makefile
Fixed wrong message in Makefile when running integration tests
- Run `make test-integration` to see
=> Fixed wrong message in Makefile when running integration tests

src/ui/gradio_ui.py, utils/config.py, utils/logger.py
According to PEP-8, multiple imports should usually be on separate lines:
https://peps.python.org/pep-0008/#imports
- N/A
=> Fixed multiple imports

tests/unit/utils/test_json_tools.py, utils/json_tools.py
- Fix for `parsing_and_checking_json` function: `TypeError` is not caught
- Added unit tests with 100% coverage for this function
- Run `make test-unit` as usual
=> Fix + unit tests for parsing_and_checking_json

CONTRIBUTING.md, Makefile, pyproject.toml
Incorporate Ruff linter into CI + for local checks
- To be run on CI
- It is possible to check locally using `make verify` (Ruff needs to be installed in this case)
=> Incorporate Ruff linter

Makefile, pyproject.toml, src/query_helpers/task_performer.py, src/query_helpers/task_processor.py, tests/unit/test_cache_factory.py, utils/logger.py
- Added more Ruff checks
- Few fixes in the code
- Makefile updated - we accept `assert` statement in tests (but check for it in the real code)
Please note that "opinionated" rules/checks (like "D") are not yet added. Rules added are all well known and accepted in Python community.
- `make verify`
=> More Ruff checks

pyproject.toml, src/ui/gradio_ui.py
Use timeout for HTTP POST method to avoid infinite waits
- Right now it is not covered by integration tests, unfortunately
=> Use timeout for HTTP POST method to avoid infinite waits

app/endpoints/ols.py, src/cache/cache_factory.py, src/cache/in_memory_cache.py, src/cache/redis_cache.py, src/docs/docs_summarizer.py, src/indexer/indexer.py, src/query_helpers/happy_response_generator.py, src/query_helpers/question_validator.py, src/query_helpers/task_performer.py, src/query_helpers/task_processor.py, src/query_helpers/task_rephraser.py, src/query_helpers/yaml_generator.py, src/query_helpers/yes_no_classifier.py, tests/unit/test_cache_factory.py
More idiomatic imports statements:
Using the `from` keyword to import the submodule is more concise and readable.
- Usual unit tests and integration tests
=> More idiomatic imports statements

app/endpoints/feedback.py, app/endpoints/ols.py, app/main.py, app/models/models.py, scripts/transform_coverage_report.py, src/cache/cache.py, src/cache/cache_factory.py, src/cache/in_memory_cache.py, src/cache/redis_cache.py, src/docs/docs_summarizer.py, src/indexer/indexer.py, src/llms/llm_loader.py, src/query_helpers/happy_response_generator.py, src/query_helpers/question_validator.py, src/query_helpers/task_breakdown.py, src/query_helpers/task_performer.py, src/query_helpers/task_processor.py, src/query_helpers/task_rephraser.py, src/query_helpers/yaml_generator.py, src/query_helpers/yes_no_classifier.py, src/ui/gradio_ui.py, tests/integration/test_ols.py, tests/unit/test_cache.py, tests/unit/test_cache_factory.py, tests/unit/utils/test_json_tools.py, utils/config.py, utils/logger.py, utils/model_context.py
- Use sorted imports everywhere
- More linters can be enabled right now
- See CI jobs
=> Use sorted imports + enable more linters

README.md, helm/.helmignore, helm/Chart.yaml, helm/templates/_helpers.tpl, helm/templates/ols/clusterrole.yaml, helm/templates/ols/clusterrolebinding.yaml, helm/templates/ols/deployment.yaml, helm/templates/ols/sa.yaml, helm/templates/ols/secret.yaml, helm/templates/ols/service.yaml, helm/templates/redis/deployment.yaml, helm/templates/redis/route-insight.yaml, helm/templates/redis/service.yaml, helm/values.yaml
Added Helm chart to simplify OLS installation
https://issues.redhat.com/browse/OLS-50
=> chore: add Helm chart

src/cache/in_memory_cache.py
Fully typed in-memory cache
- Will be done on CI as usual
=> Fully typed in-memory cache

scripts/build-container.sh
Prevent globbing in shellscript in case any environment variable contain space or other whitespace character.
- N/A easily (unless you build locally with specifically crafted environment variables)
=> Prevent globbing in shellscript

CONTRIBUTING.md, requirements-test.txt
Updated contributing documentation and pre-commit dependencies.
- Closes #
=> Update contrib install instructions

app/models/config.py, src/cache/redis_cache.py, src/query_helpers/happy_response_generator.py, src/query_helpers/question_validator.py, src/query_helpers/yaml_generator.py, src/query_helpers/yes_no_classifier.py, tests/integration/test_ols.py, utils/config.py, utils/logger.py
- Added type info for functions without return value
- This is trivial as in this case type of return value is `None` (in Python _every_ functions return some value, but it can be `None` which is like "no value")
=> Type info for functions without return value

.gitignore
Ignore cache directories - these should not be pushed into the repo
- Run any linter or unit test and the call `git status`. It should not list those "dot directories" even if "dot files" are included in search path in Git settings
=> Ignore cache directories - these should not be pushed into the repo

src/cache/in_memory_cache.py, src/query_helpers/question_validator.py, src/query_helpers/yes_no_classifier.py
Added more types for functions called from unit tests (and thus tested properly)
- To be checked on CI
=> Added more types for functions called from unit tests

pyproject.toml
Currently the project is "clean" from basic type checker perspective. In order to maintain this code quality, it would be nice to check it on CI and locally `make verify`.
- Related Issue [OLS-83](https://issues.redhat.com//browse/OLS-83)
- `make verify` will do the magic there
=> Enable Flake8-like type checking

app/endpoints/ols.py, src/indexer/indexer.py, src/llms/llm_loader.py
There are some errors found during type checking (NPE can occurs etc.). So let's fix them.
- Related Issue [OLS-83](https://issues.redhat.com//browse/OLS-83)
- N/A right now
=> Fixed type related errors

tests/integration/test_feedback.py, tests/integration/test_ols.py
- Proper endpoints to be checked in integration tests
- Added two negative test cases
=> Proper endpoints in integration tests + 2 negative test cases

utils/config.py
- Use the constant that used to be defined for this purpose
- Look like somebody just forget do update the code
- N/A
=> Use the constant that used to be defined for this purpose

app/endpoints/ols.py
Better HTTP status codes
- Related Issue #[OLS-158](https://issues.redhat.com//browse/OLS-158)
- To be checked on CI
=> Better HTTP status codes

CONTRIBUTING.md, pyproject.toml
- Added code coverage check settings in `pyproject.toml`
- Updated contributing guide a bit with info about coverage checks
- You can try to make the threshold higher in `pyproject.toml` and rerun tests to see failures
=> Code coverage checks + updated contributing documentation a bit

app/endpoints/feedback.py, app/endpoints/ols.py, app/main.py, app/models/models.py, app/utils.py, scripts/transform_coverage_report.py, src/cache/cache_factory.py, src/cache/in_memory_cache.py, src/cache/redis_cache.py, src/docs/docs_summarizer.py, src/llms/llm_loader.py, src/query_helpers/happy_response_generator.py, src/query_helpers/question_validator.py, src/query_helpers/yaml_generator.py, src/query_helpers/yes_no_classifier.py, tests/mock_classes/langchain_interface.py, tests/mock_classes/llm_chain.py, utils/json_tools.py, utils/logger.py
- Fixed docstyle in sources
- Now it's the right time to do it - before bigger changes
- Will allow us to enable docstyle-like checkers (separate PR)
- N/A
=> Fixed docstyle in sources

tests/integration/test_ols.py
Two new integration tests for query post endpoint
- Related Issue #[OLS-158](https://issues.redhat.com//browse/OLS-158)
- Just `make test-integration`
=> Two new integration tests for query post endpoint

pyproject.toml
Setup Google doc style convention for Ruff (and thus for CI)
- Related Issue #OLS-83
- N/A right now
=> Setup Google doc style convention for Ruff (and thus for CI)

.github/PULL_REQUEST_TEMPLATE.md
Updated PR template: checkbox about linters
- N/A
=> Updated PR template: checkbox about linters

app/endpoints/ols.py, tests/integration/test_ols.py
Refactoring: unknown question type handling
Added integration test for the unknown question variant
=> Refactoring: unknown question type handling

tests/unit/utils/test_logger.py
100% unit test coverage for logging module
- Related Issue #[OLS-187](https://issues.redhat.com//browse/OLS-187)
- To be tested on CI
=> 100% unit test coverage for logging module

app/models/config.py
Idiomatic checks in model config checking
- N/A
=> Idiomatic checks in model config checking

tests/unit/test_cache_factory.py
Trivial refactoring: use `return` directly
- N/A
=> Trivial refactoring: use `return` directly

ols/app/main.py, ols/src/cache/__init__.py, ols/src/cache/cache.py, ols/src/cache/cache_factory.py, ols/src/cache/in_memory_cache.py, ols/src/cache/redis_cache.py, ols/src/llms/llm_loader.py, ols/src/query_helpers/__init__.py, ols/src/query_helpers/happy_response_generator.py, ols/src/query_helpers/question_validator.py, ols/src/query_helpers/yaml_generator.py, ols/src/query_helpers/yes_no_classifier.py, ols/src/ui/__init__.py, ols/src/ui/gradio_ui.py, ols/utils/__init__.py, ols/utils/config.py, ols/utils/logger.py, scripts/transform_coverage_report.py
- Docstrings update, round #1
- Background: we'd like to add a docstyle checks. But first all existing docstrings needs to be correct (and exist at all). This is the 1st round as the number of changes is huge (and the discussion might be lengthy and coincides by new PRs). I know that some docstrings are "repeated" (in module+in class etc.), but checker really needs all of them.
- Args. doc - the "-" are removed as these are not expected in Google style (and it is checked too by linters, of course)
- N/A
=> Docstrings update, round #1

CONTRIBUTING.md
Contributing.md update with docstring style section.
[OLS-83](https://issues.redhat.com/browse/OLS-83)
=> Update contributing with docstring style section

ols/src/cache/in_memory_cache.py
The variable assignment is not necessary as the value can be returned
directly.
=> (Minor refactor) directly return value

CONTRIBUTING.md
Info about code coverage report (documentation update)
- N/A
=> Info about code coverage report

README.md
This slipped my radar.
- Closes #
=> Fix run command in readme

ols/app/models/config.py
Handling exceptions such `Exception` requires the use of `except Exception`, which
captures _any_ raised exception, including failed assertions,
division by zero, and more.
It is then better to raise our own exception, or a more specific built-in
exception, so that we can avoid over-capturing exceptions that we
don't intend to handle.
=> Use custom exception

ols/__init__.py, ols/app/__init__.py, ols/app/endpoints/__init__.py, ols/app/models/__init__.py, ols/src/__init__.py, ols/src/docs/__init__.py, ols/src/llms/__init__.py, ols/src/llms/llm_loader.py
Public packages should be documented via docstrings to outline their
purpose and contents.
- [PEP 257 – Docstring Conventions](https://peps.python.org/pep-0257/)
- [PEP 287 – reStructuredText Docstring Format](https://peps.python.org/pep-0287/)
- [NumPy Style Guide](https://numpydoc.readthedocs.io/en/latest/format.html)
- [Google Style Python Docstrings](https://google.github.io/styleguide/pyguide.html#s3.8-comments-and-docstrings)
Public packages should be documented via docstrings
- N/A
=> Public packages should be documented via docstrings

.github/PULL_REQUEST_TEMPLATE.md
=> move description section to top of PR template

tests/unit/query_helpers/test_yaml_generator.py
- Unit tests for YAML generator class
- 100% code coverage, but just thanks to using mocks
=> Unit tests for YAML generator class

README.md
-H2 isn't a valid curl arg, it just takes multiple -H args
- Closes #
=> docs: fix curl example in readme

default.env, ols/utils/logger.py, tests/unit/utils/test_logger.py
Added explicit env for logging level when logging to file.
=> OLS-155: Add explicit env for logging level when logging to file

tests/unit/test_cache_factory.py
Cache factory returning Redis interface: unit test
- `make test-unit` should display full code coverage for `CacheFactorry`
=> OLS-186: Cache factory returning Redis interface: unit test

OWNERS
Over time I expect everyone who's officially working on OLS to end up as an approver, but right now there isn't enough shared understanding of the goals/vision so we need to be careful about what is being merged that may not be aligned with the overall direction/goals of the project.
It will also be important for people to understand how/when to use their approval permissions vs when to pull someone else into the conversation.  Just because you have approval rights and someone asks you to approve something, doesn't mean you are the right person to assess it.
- Closes #
=> Set owners file to clean slate

ols/app/endpoints/ols.py
Fixed wrong return type
- Use mypy or Pyright to check types
=> Fixed wrong return type

ols/src/llms/llm_loader.py, tests/unit/llms/test_llm_loader.py
- Fix logging message template - avoid key error
- Unit test checks that key error is not thrown
- Program logic will probably need to be updated, but not in this simple bug fix
=> Check if provider is supported

default.env, ols/app/models/config.py, ols/utils/config.py, ols/utils/logger.py, tests/unit/utils/test_logger.py
As agreed, this PR removes the app's ability to log into the file.
=> OLS-155: Remove ability for logging to file

tests/mock_classes/llm_chain.py, tests/mock_classes/mock_llama_index.py, tests/mock_classes/redis.py
- Info how to patch (docstring)
- Use `@patch` decorator or `patch` as context manager
=> OLS-83: Info how to patch (docstring)

OWNERS
Pavel will help shepherd the trivial refactors and test update PRs through.
Ben will continue to provide approvals for "bigger picture" changes (and continue approving the smaller changes as needed)
- Closes #
=> Add Pavel to approvers list

ols/app/constants.py, ols/app/endpoints/ols.py, ols/app/models/config.py, ols/constants.py, ols/src/cache/cache_factory.py, ols/src/cache/redis_cache.py, ols/src/docs/docs_summarizer.py, ols/src/indexer/indexer.py, ols/src/llms/llm_loader.py, ols/src/query_helpers/question_validator.py, ols/src/query_helpers/yaml_generator.py, ols/src/query_helpers/yes_no_classifier.py, ols/utils/config.py, tests/integration/test_ols.py, tests/unit/llms/test_llm_loader.py, tests/unit/test_cache_factory.py
Having two different constants.py under app and src makes the codebase a bit confusing. This PR merges both into `ols/constants.py` and fixes imports.
=> OLS-155: Merge constants under single project level module

CONTRIBUTING.md
Definition of Done
- Related Issue #[OLS-160](https://issues.redhat.com//browse/OLS-160): Definition of Done
=> OLS-160: Definition of Done

ols/src/docs/docs_summarizer.py
[OLS-83](https://issues.redhat.com//browse/OLS-83): Added missing type hints into DocsSummarizer
=> OLS-83: Added missing type hints into DocsSummarizer

ols/utils/config.py
=> OLS-83: Loglevel as name everywhere

ols/src/cache/cache_factory.py, ols/src/cache/in_memory_cache.py, ols/src/indexer/indexer.py, ols/src/query_helpers/question_validator.py, ols/src/query_helpers/yaml_generator.py, ols/src/query_helpers/yes_no_classifier.py, ols/src/ui/gradio_ui.py, ols/utils/logger.py
OSL-83: Use imperative mood in sources.
This will allow us to enable the last missing docstyle check: D401
=> OLS-83: Use imperative mood in sources

tests/unit/test_cache_factory.py
Removes unused commented code in test.
=> Remove commented code in test

ols/app/endpoints/ols.py, tests/integration/test_ols.py
LLM loader returns a `ChatOpenAI` instance(derived from `BaseChatModel`) for openai, whereas for BAM the loader returns a `LangChainInterface` (derived from `LLM`), and those two base classes don't have the same invocation arguments(one takes the prompt in the form of a raw string, the other expects a List of BaseMessages), 
This meant we weren't able to use the result of llmloader directly(it would fail when switching to openai, the code worked for the LLM base class but not for the BaseChatModel class).  
All the rest of our code seems to wrap the result of llmloader into a `LLMChain` which seems to abstract the argument difference, so i've updated the base_prompt implementation to do the same.....but this is going to be something to keep an eye on (using LLM vs BaseChatModel interfaces …
=> Use LLMChain for base prompt llm invocation

ols/src/llms/llm_loader.py, tests/integration/test_ols.py
Raise exception when selected LLM can not be loaded
=> Raise exception when selected LLM can not be loaded

CONTRIBUTING.md
Tips and hints for writing unit tests
=> Tips and hints for writing unit tests

ols/app/models/models.py, ols/constants.py, ols/src/docs/docs_summarizer.py, ols/src/llms/llm_loader.py, ols/src/query_helpers/question_validator.py, ols/src/query_helpers/yaml_generator.py, ols/src/query_helpers/yes_no_classifier.py, ols/utils/config.py, pyproject.toml
Implements project line length for 100.
See various threads about this topic
- https://github.com/openshift/lightspeed-service/pull/96
- https://redhat-internal.slack.com/archives/C068JAU4Y0P/p1704277149765139
- https://redhat-internal.slack.com/archives/C068JAU4Y0P/p1705091283613439
This is on hold until all PRs from today are merged. Once they are, I'll fix the rest of the errors.
=> OLS-155: Set project line length

tests/unit/llms/test_llm_loader.py
Checks how improper LLM loading is handled by LLM loader
- Will be done on CI
=> OLS-186: Checks how improper LLM loading is handled by LLM loader

ols/src/cache/cache_factory.py
- Use `match-case` instead of `if-elseif` flow so it would be easy to add more cases.
- Backed by unit tests
=> Use match-case instead of if-elseif flow

tests/unit/utils/test_logger.py
Slightly better unit tests for logger
- On CI
- `make test-unit`
=> OLS-186: Slightly better unit tests for logger

CONTRIBUTING.md
Info about capturing in unit tests and integration tests
- N/A
=> Info about capturing in unit tests and integration tests

tests/integration/test_ols.py
Get rid of `monkeypatch` from integration tests
=> Get rid of `monkeypatch` from integration tests

CONTRIBUTING.md
[OLS-151](https://issues.redhat.com//browse/OLS-151): Info about tests. It should, I hope, covered all relevant pieces (and not going too deep).
- Related Issue #[OLS-151](https://issues.redhat.com//browse/OLS-151)
- Closes #[OLS-151](https://issues.redhat.com//browse/OLS-151)
- N/A
=> OLS-151: Info about tests

tests/unit/llms/test_llm_loader.py
[OLS-186](https://issues.redhat.com//browse/OLS-186): Final LLM loader unit tests
- Will run on CI
- `make test-unit`
=> OLS-186: Final LLM loader unit tests

ols/src/docs/docs_summarizer.py
[OLS-153](https://issues.redhat.com//browse/OLS-153): Fix local var type
This will allow us to incorporate basic type checks (as specified in task)
- Related Issue #[OLS-153](https://issues.redhat.com//browse/OLS-153)
- N/A (the setup PR will follow)
=> OLS-153: Fix local var type

README.md, ols/app/endpoints/feedback.py, ols/app/endpoints/health.py, ols/app/endpoints/ols.py, ols/app/main.py, ols/app/models/models.py, tests/integration/test_feedback.py, tests/integration/test_ols.py
This PR is the first step to complete [OLS-102](https://issues.redhat.com//browse/OLS-102) . 
As a first step PR  includes versioning for the api and swagger doc and examples. Updated the integration tests to reflect the changes. 
We will have a follow up PR to formalize the error codes and review of the API and  propose changes.
- Related Issue([OLS-102](https://issues.redhat.com//browse/OLS-102)) [#](https://issues.redhat.com/browse/OLS-102)
=> OLS-102: Version OLS API endpoints

ols/app/models/config.py
Fix custom error docstring formatting to Google's standard.
=> Fix InvalidConfigurationError docstring format

tests/unit/llms/test_llm_loader.py
Fix unit test: no key to be passed everywhere
=> Fix unit test: no key to be passed everywhere

ols/src/llms/llm_loader.py
Refactoring: require LLM init to return the right object or fail in all cases
Why:
1) previously the code allows some initializers to simply don't touch `self.llm` and still be "fine"
2) the code that uses `self.llm` later (all query helpers etc.) will need to check `llm is not None` everywhere which is not there in the current code (and will be overkill)
3) now any LLM to be initialized **must** return the right object **or** throws an exception (the other possibilities will be detected)
4) it might help in the future with modularization
- Related Issue #[OLS-84](https://issues.redhat.com//browse/OLS-84)
- Closes #
=> OLS-84: Refactoring: require LLM init to return the right object or fail in all cases

ols/src/llms/llm_loader.py
=> Typed params (minor)

pyproject.toml
Updated Mypy settings - for new version
=> Updated Mypy settings - for new version

ols/src/ui/gradio_ui.py
Fix URL for our UI
- Run locally, go into UI and try to send a query to LLM - it should not say "Not found"
=> Fix URL for our UI

ols/src/cache/redis_cache.py
Docupdate: Info about exception that can be thrown. It is unlikely to happen, but can indeed happen for one long context.
- N/A
=> Docupdate: Info about exception that can be thrown

ols/src/llms/llm_loader.py, requirements.txt, tests/unit/llms/test_llm_loader.py
Bug fix: initializing BAM LLM in new version (genai etc. seems to be changing rapidly)
=> Bug fix: initializing BAM LLM in new version

ols/app/endpoints/ols.py, ols/app/models/models.py, requirements-test.txt, tests/e2e/test_api.py, tests/integration/test_ols.py, tests/unit/test_app_endpoints.py
Mypy reports a couple small errors, fix them up so that https://github.com/openshift/release/pull/47904 can proceed
- Closes #
=> Fix type errors so we can enable type checking

CONTRIBUTING.md
Minor contributing guide improvement
- N/A
=> Minor contributing guide improvement

ols/src/llms/llm_loader.py
Remove unused url parameter in LLMLoader.
=> Remove unused url parameter in LLMLoader

pyproject.toml
=> Don't expect all types libs

CONTRIBUTING.md, hooks/pre-commit
Updated pre-commit hook + updated contributing guide accordingly
- Closes #[OLS-153](https://issues.redhat.com//browse/OLS-153)
- N/A
=> OLS-153: Updated pre-commit hook + updated contributing guide accordingly

README.md, ols/src/docs/docs_summarizer.py
When asking "what is kubernetes?" with the OpenAI backend, the server crashes with FileNotFoundError: [Errno 2] No such file or directory: '/home/ometelka/projects/lightspeed-service/vector-db/ocp-product-docs/docstore.json' 
- [ X] Bug fix
- Related Issue # [OLS-212](https://issues.redhat.com//browse/OLS-212)
- Closes # [OLS-212](https://issues.redhat.com//browse/OLS-212)
=> Ols 212: Missing documentation about index store

ols/app/main.py, ols/src/cache/in_memory_cache.py, ols/src/cache/redis_cache.py, ols/src/ui/gradio_ui.py, tests/unit/ui/test_gradio_ui.py
- Proper case for identifiers in all sources
- It allow us to enable yet another linter
=> Proper case for identifiers in all sources

ols/app/models/models.py
Adds comment about `model_config` parameter. It might be confusing to someone as it is not used directly in code. It is "automagically" used by the FastApi docs generator.
=> Add comment about model_config attr

tests/unit/llms/test_llm_loader.py
Unit tests need to be updated after LLM loader was refactored
- `make test-unit`
=> Unit tests need to be updated after LLM loader was refactored

ols/src/cache/cache_factory.py
=> Get rid of `in-memory` option

.gitignore, ols/src/query_helpers/query_docs.py, requirements.txt, tests/integration/query_helpers/test_query_docs.py, tests/mock_classes/mock_retrievers.py, tests/unit/query_helpers/test_query_docs.py
This is the code for basic retriever as described in 
https://issues.redhat.com/secure/RapidBoard.jspa?rapidView=18820&projectKey=OLS&view=detail&selectedIssue=[OLS-103](https://issues.redhat.com//browse/OLS-103)
- [ X] New feature
- Closes #
- [X ] I have performed a self-review of my code.
- unit test/integration test included
=> OLS-103 - Completed basic retriever

README.md, ols/app/main.py, ols/app/models/config.py, tests/unit/test_models.py
Fix enable UI configuration option
- Try to change the configuration option before `make run`
=> Fix enable UI configuration option

ols/utils/config.py
Removes comment disabling linter for config.py - relevant code is no longer there.
=> Enable linting for config.py

.gitignore, README.md, tests/config/test_app_endpoints.txt, tests/config/test_app_endpoints.yaml, tests/integration/test_feedback.py, tests/integration/test_ols.py
some minor clean up as a follow on to https://github.com/openshift/lightspeed-service/pull/166
- Closes #
=> OLS-89: Config yaml follow-ups

ols/src/query_helpers/yes_no_classifier.py
More specific error message
Why?
w/o this one in the end we will end with log full of the same error messages which won't say anything about the real problem
- [] Refactor
- Run on CI
=> More specific error message

ols/src/utils/__init__.py, ols/src/utils/constants.py, ols/src/utils/token_handler.py, tests/unit/utils/test_token_handler.py
We need a mechanism to limit tokens based on context window.
The modification covers below
- utility to convert text to tokens
- get approximate token count
- limit the context based on context window.
- Related Issue # [OLS-104](https://issues.redhat.com//browse/OLS-104)
- Closes #
=> feat: [OLS-104] Add token handler utility for context

Makefile, scripts/test-e2e-standalone.sh, tests/config/singleprovider.e2e.template.config.yaml
Defines a script that generates a config file for OLS, starts the server, and
then runs our e2e tests against the OLS server.
- Closes #
=> Define e2e execution logic in ols repo

ols/app/models/models.py, ols/src/llms/llm_loader.py, ols/src/query_helpers/__init__.py, ols/src/query_helpers/query_docs.py, ols/src/utils/token_handler.py, tests/integration/query_helpers/test_query_docs.py, tests/mock_classes/mock_retrievers.py, tests/unit/query_helpers/test_query_docs.py, tests/unit/test_models.py, tests/unit/utils/test_app_utils.py, tests/unit/utils/test_token_handler.py
=> Make Black happy again

ols/src/query_helpers/query_docs.py, tests/unit/query_helpers/test_query_docs.py
(Minor) Fixed typo in exception message
- N/A
=> (Minor) Fixed typo in exception message

ols/src/query_helpers/question_validator.py, tests/unit/query_helpers/test_question_validator.py
More specific error message
Why?
w/o this one in the end we will end with log full of the same error messages which won't say anything about the real problem
- N/A
=> Specific exception message in question validator

tests/mock_classes/mock_retrievers.py, tests/mock_classes/redis.py
=> Removed unecessarry statement

tests/unit/utils/test_logging.py
Fixes logging tests. They were not working correctly before.
Renames test module accordingly.
=> Fix logging tests

ols/src/query_helpers/docs_summarizer.py
=> Correct type for `summary`

ols/src/query_helpers/docs_summarizer.py, ols/src/query_helpers/question_validator.py, ols/src/query_helpers/yaml_generator.py, ols/src/query_helpers/yes_no_classifier.py
Remove duplicated log msg. Model is currently captured in the settings_string.
=> OLS-204: Remove duplicated log msg

ols/src/llms/llm_loader.py
=> Update LLMLoader docstring

tests/unit/test_config.py
Missing tests for improper URL
=> Missing tests for improper URL

ols/src/llms/llm_loader.py, scripts/test-e2e-standalone.sh, tests/config/singleprovider.e2e.template.config.yaml
=> Ensure script returns error code from test execution

ols/app/models/config.py, tests/unit/llms/test_llm_loader.py
Removed `pass` keyword where it is not needed
=> Removed `pass` keyword where it is not needed

tests/integration/test_ols.py
Fix integration tests: pydantic version
=> Fix integration tests: pydantic version

README.md
This PR improves the readability of the README. It's still not perfect, but imo the proposed change structures the content better, removes some redundant parts, and corrects invalid links. 
- Closes #
=> Improvement of readability of the readme

README.md
=> Fix instructions for enabling dev ui

ols/src/query_helpers/__init__.py
Added missing type in query helper superclass
=> Added missing type in query helper superclass

ols/src/ui/gradio_ui.py, tests/unit/ui/test_gradio_ui.py
Added missing types in Gradio UI handlers
=> Added missing types in Gradio UI handlers

ols/src/utils/token_handler.py, tests/unit/utils/test_token_handler.py
Added missing types into token handler
=> Added missing types into token handler

README.md, examples/olsconfig.yaml, ols/app/main.py, ols/app/models/config.py, ols/src/llms/llm_loader.py, ols/src/query_helpers/question_validator.py, ols/utils/config.py, tests/config/singleprovider.e2e.template.config.yaml, tests/config/test_app_endpoints.yaml, tests/config/valid_config.yaml, tests/unit/test_config.py, tests/unit/test_models.py
Introduce a new config section for developer-only settings.  Initial settings:
set llm generation temperature
enable/disable ui
enable/disable question validation
enable/disable auth (not wired to anything yet)
- Closes #
=> Add a developer mode configuration section

ols/src/cache/cache.py
Better docstring for cache
- Related Issue #[OLS-109](https://issues.redhat.com//browse/OLS-109)
=> OLS-109: Better docstring for cache

ols/src/cache/cache_factory.py
No magic constants in exception message
=> No magic constants in exception message

tests/integration/test_openapi.py
Integration test for OpenAPI endpoint
- Integration tests on CI
- `make test-integration` locally
=> OLS-201: Integration test for OpenAPI endpoint

ols/app/endpoints/ols.py
Rename conversation to conversation_id. Just conversation suggests it holds more than just id.
=> OLS-157: Rename conversation to conversation_id

tests/integration/test_ols.py
More integration tests for debug endpoint
- Related Issue #OSL-201
=> OLS-201: More integration tests for debug endpoint

tests/integration/test_ols.py
Check how model and provider are checked by REST API handler
=> OLS-201: Check how model and provider are checked by REST API handler

README.md, examples/olsconfig.yaml, ols/app/models/config.py, tests/config/config_without_logging.yaml, tests/config/singleprovider.e2e.template.config.yaml, tests/config/test_app_endpoints.yaml, tests/config/valid_config.yaml, tests/config/valid_config_redis.yaml, tests/unit/test_config.py, tests/unit/test_models.py
also cleans up a few error messages
- Closes #
=> Use snake_case consistently in ols config yaml

tests/integration/test_feedback.py
Check how no payload situation is checked on feedback endpoint
=> OLS-201: Check how no payload situation is checked on feedback endpoint

tests/integration/test_ols.py
Fix typos + one check improvement
=> Fix typos + one check improvement

tests/integration/test_ols.py
- Check all possible flows in REST API handler
- Please note that YAML processing is skipped on purpose (can create new PR with remaining tests if really needed)
- Closes #[OLS-201](https://issues.redhat.com//browse/OLS-201)
- Integration tests on CI
=> OLS-201: Check all possible flows in REST API handler

Makefile
=> Add logic to install pdm if needed prior to installing deps

pyproject.toml
We are good with unit tests and integration tests! We can safely increase threshold to 60%
=> Increase threshold to 60%

tests/e2e/test_api.py, tests/integration/test_feedback.py, tests/integration/test_liveness_readiness.py, tests/integration/test_ols.py, tests/integration/test_openapi.py, tests/unit/test_config.py
Removes return type from tests. It's not needed there.
=> Remove return type in tests

pdm.lock
=> Update deps in pdm.lock

ols/app/endpoints/health.py, tests/integration/test_liveness_readiness.py, tests/unit/app/endpoints/test_health.py
Support for HEAD HTTP methods for liveness endpoints
- CI
=> OLS-201: Support for HEAD HTTP methods for liveness endpoints

scripts/test-e2e-standalone.sh
=> Prevent globbing

tests/integration/test_openapi.py
Check HEAD HTTP method for OpenAPI endpoint
=> OLS-201: Check HEAD HTTP method for OpenAPI endpoint

tests/unit/app/models/test_config.py
- More unit tests for ModelConfig
- Now the ModelConfig is 100% covered by the right tests
=> OLS-89: More unit tests for ModelConfig

tests/unit/app/models/test_config.py
- More unit tests for `ProviderConfig` model
- 100% code coverage now
- `make test-unit` as expected
=> OLS-89: More unit tests for ProviderConfig model

tests/unit/test_cache_factory.py
Fixed comments: we don't use environment variables anymore
=> Fixed comments: we don't use environment variables anymore

pyproject.toml
Helper commands:
`pdm run`
`pdm test-unit`
etc.
=> Helper commands

examples/olsconfig.yaml
Removes second training new line and `---` as its just a single document.
=> Update example olsconfig.yaml formating

pdm.lock, pyproject.toml
I've removed some deps that seem extra or indirect. 
Eventually, we should pin everything we have in lock in pyproject.toml to be Konflux compliant. But now, it would be an overkill.
The app still works as usual. But I can't confirm if those aren't used in some corners. Like indexer.py?
=> Clean project deps

ols/src/cache/cache.py, ols/utils/suid.py, tests/e2e/test_api.py, tests/unit/utils/test_suid.py
=> Use UUID as conversation ID

tests/unit/app/models/test_config.py
New unit tests: equality operator
=> OLS-89: New unit tests: equality operator

CONTRIBUTING.md, Makefile
Separated integration tests coverage threshold
=> Separated integration tests coverage threshold

pyproject.toml
Increase unit test coverage threshold to 90%
=> Increase unit test coverage threshold to 90%

CONTRIBUTING.md
contributing guide was missing a step
- Closes #
=> Instruct users to just run unit+integration test

tests/unit/app/models/test_config.py
Unit tests: Redis credentials configuration
=> OLS-89: Unit tests: Redis credentials configuration

tests/unit/ui/test_gradio_ui.py
=> More unit tests for Gradio UI

README.md
=> (doc) Info about Swagger UI

ols/app/models/config.py, ols/app/models/models.py, ols/src/query_helpers/__init__.py, ols/src/query_helpers/docs_summarizer.py, ols/src/query_helpers/query_docs.py, ols/src/query_helpers/yaml_generator.py, ols/src/ui/gradio_ui.py
Seems we are using `Optional` instead of `something | None`.
=> OLS-233: Use Optional type instead of | operator

ols/app/main.py
=> License in Swagger UI

CONTRIBUTING.md
Added missing `make` command into contributing guide
=> Added missing `make` command into contributing guide

ols/utils/config.py
Added missing types into `utils.config`
=> Added missing types into `utils.config`

ols/src/cache/cache.py
Added missing types into `cache.py` module
=> Added missing types into `cache.py` module

ols/app/models/config.py
Added missing types for return values
=> Added missing types for return values

ols/src/query_helpers/__init__.py, tests/unit/query_helpers/test_query_helper.py
=> Removed unused code

ols/app/endpoints/ols.py, ols/constants.py, ols/src/query_helpers/question_validator.py, tests/integration/test_ols.py, tests/unit/app/endpoints/test_ols.py, tests/unit/query_helpers/test_question_validator.py
The fix addresses the following issues
a. BAM provider does not accurately return the expected classification response
b. Remove yaml categorization for Kubernetes related queries.
- Closes #
=> OLS-256: Removed yaml category for Kubernetes queries

ols/app/endpoints/ols.py, ols/app/models/models.py, tests/integration/test_ols.py, tests/unit/app/endpoints/test_ols.py, tests/unit/app/models/test_models.py
Use pydantic abilities to validate its own models instead of us doing the same work. It still raises 422, but the json is a bit different.
=> OLS-157: Do request validation in pydantic model

.codecov.yml, Makefile, scripts/codecov.sh
Pre-requisite PR from PROW: https://github.com/openshift/release/pull/46818
Needs integration with PROW PR above to see it reflected in the subsequent PRs.
=> Adding code coverage bits

Makefile
=> Bug fix: word splitting

README.md, ols/app/endpoints/ols.py, ols/app/main.py, ols/app/metrics.py, pdm.lock, pyproject.toml
- Introducting Prometheus metrics
- Three example counters
- An example how to test metrics (counters)
- Related Issue #[OLS-116](https://issues.redhat.com//browse/OLS-116)
- You can access the metrics as `/metrics` enpoint
=> OLS-116: Introducting Prometheus metrics

examples/olsconfig.yaml, ols/app/models/config.py, ols/constants.py, ols/src/query_helpers/docs_summarizer.py, tests/config/config_without_logging.yaml, tests/config/singleprovider.e2e.template.config.yaml, tests/config/test_app_endpoints.yaml, tests/config/valid_config.yaml, tests/config/valid_config_redis.yaml, tests/integration/test_ols.py, tests/mock_classes/langchain_interface.py, tests/unit/docs/test_doc_summarizer.py, tests/unit/utils/test_config.py
=> OLS-212: Add test case for missing doc store scenario

ols/app/models/config.py, ols/constants.py, ols/src/cache/cache_factory.py, ols/src/cache/in_memory_cache.py, ols/src/cache/redis_cache.py, ols/src/llms/llm_loader.py, ols/src/query_helpers/docs_summarizer.py, tests/config/redis_user.txt, tests/config/redis_username.txt, tests/config/valid_config_redis.yaml, tests/config/with_openai_api_key.yaml, tests/config/without_openai_api_key.yaml, tests/unit/app/models/test_config.py, tests/unit/llms/test_llm_loader.py, tests/unit/test_in_memory_cache.py, tests/unit/test_redis_cache.py, tests/unit/utils/test_config.py
- Redis cache config now comes from YAML
- Added more YAML config validation
- Related Issue # [OLS-89](https://issues.redhat.com//browse/OLS-89)
- Closes #
=> OLS-89: YAML configuration: redis conf from YAML, more validation

CONTRIBUTING.md
=> Fix typo (trivial)

ols/app/models/models.py
Use proper conversation ID in examples
=> Use proper conversation ID in examples

tests/unit/docs/test_doc_summarizer.py, tests/unit/query_helpers/test_question_validator.py, tests/unit/query_helpers/test_yes_no_classifier.py, tests/unit/ui/test_gradio_ui.py
Use proper conversation ID in unit tests
=> Use proper conversation ID in unit tests

CONTRIBUTING.md
Minor contributing guide update
=> Minor contributing guide update

tests/unit/query_helpers/test_question_validator.py
Test disabled question validator behaviour
=> Test disabled question validator behaviour

scripts/test-e2e-standalone.sh, tests/config/singleprovider.e2e.template.config.yaml, tests/e2e/test_api.py
- Related Issue # [OLS-158](https://issues.redhat.com//browse/OLS-158)
- Closes # [OLS-158](https://issues.redhat.com//browse/OLS-158)
=> OLS-158: Added e2e test case

pdm.lock, pyproject.toml
Update: fix vulnerability in FastAPI
=> Update: fix vulnerability in FastAPI

pdm.lock, tests/e2e/test_api.py
we had a merge race and landed a new test that expected a field that another PR
was in the process of dropping
- Closes #
=> Fix broken e2e test

ols/src/cache/cache.py, ols/src/cache/in_memory_cache.py, ols/src/cache/redis_cache.py
Proper usage of `Optional` type
=> Proper usage of `Optional` type

tests/unit/app/models/test_config.py
=> Some missing config tests

ols/src/query_helpers/question_validator.py
Fix question validator return type
=> Fix question validator return type

Containerfile.rag, README.md
Quick containerfile that makes it easy to test "e2e" with the rag data already present
N/A
=> OLS-265: Implements an all-in-one container for testing

ols/src/ui/gradio_ui.py
(Trivial) Added missing `FastAPI` type
=> Added missing `FastAPI` type

ols/utils/token_handler.py
Proper `RetrievedNode` class declaration
=> Proper `RetrievedNode` class declaration

ols/app/main.py, ols/app/routers.py
- Separate routers handling functions
- It is hard/impossible to call any code from `main.py` from unit or integration tests, so it's better to refactor all functions out of it
=> Separate routers

ols/src/query_helpers/docs_summarizer.py, ols/src/query_helpers/question_validator.py, ols/src/query_helpers/yes_no_classifier.py, tests/unit/query_helpers/test_question_validator.py, tests/unit/query_helpers/test_yes_no_classifier.py
Change `conversation` to `conversation_id` as it is misleading and implies it is something more than id.
=> Change conversation to conversation_id

ols/src/llms/llm_loader.py, tests/unit/llms/test_llm_loader.py
We don't have any specific install groups. All deps listed in `pyproject.toml` are available.
=> OLS-233: Import all llm libs at once

ols/src/query_helpers/docs_summarizer.py, ols/src/query_helpers/yes_no_classifier.py
(Minor) Missing kwargs types where needed
[Later it might be better to use keyword params with strict typing]
=> Missing kwargs types where needed

ols/app/models/models.py, ols/app/routers.py, ols/src/ui/gradio_ui.py
=> Few missing type declarations

tests/integration/query_helpers/test_query_docs.py
=> Removed leftover

ols/src/query_helpers/query_docs.py
=> Trivial: reformat

scripts/test-e2e-standalone.sh
Make sure we exit on any failure such as pulling down the RAG content or extracting it
- Closes #
=> E2E script needs to exit on errors

scripts/test-e2e-standalone.sh
Change script shebang from sh to bash.
=> Change script shebang from sh to bash

tests/mock_classes/redis.py, tests/unit/cache/test_redis_cache.py
=> Unit tests: init Redis code

ols/app/endpoints/ols.py, tests/integration/test_ols.py
Refactor: LLMConfigurationError is not thrown from DocsSummarizer
=> Refactor: LLMConfigurationError is not thrown from DocsSummarizer

ols/src/ui/gradio_ui.py
History type for Gradio's Chat UI
=> History type for Gradio's Chat UI

ols/app/endpoints/ols.py
=> (Trivial) typo

README.md
Fix Markdown format in paragraph about keys storage solution
- Look at `README.md` rendering in any Markdown editor/renderer
=> Fix Markdown format in paragraph about keys storage solution

README.md
Link to OLS config example
- Look at README.md rendering in any Markdown editor/renderer
=> Link to OLS config example

README.md
Info about conversation cache configuration
- Related Issue #[OLS-31](https://issues.redhat.com//browse/OLS-31)
=> OLS-31: Info about conversation cache configuration

tests/unit/app/endpoints/test_ols.py
Unit test: check for LLMConfiguration issue
=> Unit test: check for LLMConfiguration issue

tests/unit/docs/test_doc_summarizer.py
Unit tests fix: use proper conversation ID
=> Unit tests fix: use proper conversation ID

tests/unit/llms/test_llm_loader.py
New unit test: check for key existence
Please note: not for WatsonX as it is handled differently
=> New unit test: check for key existence

README.md
Use proper syntax highlighter (documentation, trivial)
=> Use proper syntax highlighter (documentation, trivial)

tests/integration/test_ols.py
Better check for conversation ID
=> OLS-254: Better check for conversation ID

ols/app/endpoints/ols.py, tests/unit/app/endpoints/test_ols.py
Refactoring: retrieving conversation ID
=> OLS-254: Refactoring: retrieving conversation ID

ols/app/endpoints/ols.py
Proper type for `response` variable
=> OLS-254: Proper type for `response` variable

ols/src/query_helpers/docs_summarizer.py
See the TODO comment in this PR. This is a hack to make us tolerate both
data types for now, but we need to abstract this difference better in the future.
- Closes #
=> Tolerate different response objects from different llm providers

ols/src/cache/cache.py, tests/unit/cache/test_in_memory_cache.py, tests/unit/cache/test_redis_cache.py
=> Fix exception message

ols/app/endpoints/ols.py, tests/unit/app/endpoints/test_ols.py
[OLS-254](https://issues.redhat.com//browse/OLS-254): Refactor: store conversation history
+ new unit tests, as usual
=> OLS-254: Refactor: store conversation history

ols/app/endpoints/ols.py
Type issue has been fixed there - no need to have this warning
=> OLS-254: Type issue has been fixed there - no need to have this warning

ols/app/endpoints/ols.py, tests/unit/app/endpoints/test_ols.py
Refactoring: validate question function
+ new unit tests as usual
- Related Issue #OLS-254
=> OLS-254: Refactoring: validate question function

ols/app/endpoints/ols.py, tests/unit/app/endpoints/test_ols.py
- Refactor: call docs summarizer
- More unit tests (now 100% code coverage for the whole `ols.py`)
=> OLS-254: Refactor: call docs summarizer

tests/unit/query_helpers/test_query_docs.py
A single `with` block can include multiple context managers.
Combining multiple context managers into a single `with` statement
will minimize the indentation depth of the code, making it more
readable.
=> Avoid nested patches, use multiple contexts

ols/app/endpoints/ols.py, tests/unit/app/endpoints/test_ols.py
- Refactored: debug endpoint handler
- Added unit tests (100% coverage)
=> OLS-254: Refactored: debug endpoint handler

ols/app/models/config.py, ols/constants.py, tests/unit/app/models/test_config.py
- Context window size configuration option
- Updated model logic
- Added/updated unit tests
=> OLS-58: Context window size configuration option

ols/app/endpoints/ols.py
- handlers are much more important, so put them on top
- verifications, info retrieval, response generators are below
- no changes in program logic, so no changes in tests
=> OLS-254: Reorder functions

tests/integration/test_ols.py
Avoid nested patching in tests
=> Avoid nested patching in tests

ols/app/main.py, ols/app/metrics.py
REST API call counter in metrics
- Related Issue #[OLS-114](https://issues.redhat.com//browse/OLS-114)
- access `/metrics/` endpoint to see new counter there
=> OLS-114: REST API call counter

ols/src/query_helpers/docs_summarizer.py
Refactor: getting embed model to be better testable
=> Refactor: getting embed model to be better testable

ols/app/main.py, ols/app/metrics.py
Use path in REST API call to counter metric
- Related Issue #[OLS-114](https://issues.redhat.com//browse/OLS-114)
=> OLS-114: Use path in REST API call to counter metric

ols/src/ui/gradio_ui.py
i'm seeing us hit this timeout in gradio even though OLS still gets a response from
the backend, eventually.
- Closes #
=> Bump the gradio timeout

tests/integration/test_metrics.py
Depends on: https://github.com/openshift/lightspeed-service/pull/429
- Related Issue #[OLS-114](https://issues.redhat.com//browse/OLS-114)
=> OLS-114: Integration tests for metrics exposed by the service

tests/e2e/test_api.py
=> Fix e2e response expectations due to granite model behavior change

scripts/test-e2e-standalone.sh
Fixed checking if OLS has been started
=> Fixed checking if OLS has been started

ols/app/models/config.py
Simpler logic - not needed to nest conditions
=> Simpler logic - not needed to nest conditions

tests/integration/test_metrics.py
Check for all counters in metrics
- Related Issue #[OLS-114](https://issues.redhat.com//browse/OLS-114)
=> OLS-114: Check for all counters in metrics

tests/integration/test_metrics.py
Check for histogram in metrics
- Related Issue #[OLS-113](https://issues.redhat.com//browse/OLS-113)
=> OLS-113: Check for histogram in metrics

tests/unit/app/models/test_config.py
Use plain old teste function instead of methods where appropriate
=> Use plain old teste function instead of methods where appropriate

ols/app/models/config.py
Added missing types into `config.py`
=> Added missing types into `config.py`

ols/app/main.py
Added missing types into `main.py`
=> Added missing types into `main.py`

ols/app/models/config.py
Fixed type for loglevel attribute
=> Fixed type for loglevel attribute

ols/src/query_helpers/question_validator.py
Added missing type info in QuestionValidator
=> Added missing type info in QuestionValidator

ols/src/query_helpers/docs_summarizer.py
Proper return type (type hints)
=> Proper return type (type hints)

tests/unit/app/models/test_config.py
Added missing unit tests in `config` module
=> Added missing unit tests in `config` module

ols/app/endpoints/ols.py, ols/src/query_helpers/docs_summarizer.py, ols/src/query_helpers/query_docs.py
`logging.exception` logs the exception and the traceback, while
`logging.error` only logs the exception. The former is more appropriate
when logging an exception, as the traceback is often useful for debugging.
=> Log traceback, not just error message

tests/integration/test_ols.py
Minor: Test steps are regular functions
=> Minor: Test steps are regular functions

ols/app/models/config.py
(trivial) Added missing type hint
=> (trivial) Added missing type hint

tests/integration/test_ols.py
Refactor: combine multiple patches into one `with` block
=> Refactor: combine multiple patches into one with block

ols/utils/query_filter.py
Added missing conversation ID type hint
=> Added missing conversation ID type hint

ols/src/ui/gradio_ui.py, runner.py
Disable Gradio telemetry as soon as possible
=> Disable Gradio telemetry as soon as possible

README.md, examples/olsconfig.yaml, ols/app/endpoints/feedback.py, ols/app/endpoints/ols.py, ols/app/models/config.py, ols/utils/auth_dependency.py, pdm.lock, pyproject.toml, tests/config/auth_config.yaml, tests/config/config_without_logging.yaml, tests/config/empty_openai_api_key.yaml, tests/config/kubeconfig, tests/config/singleprovider.e2e.template.config.yaml, tests/config/valid_config.yaml, tests/config/valid_config_redis.yaml, tests/config/with_openai_api_key.yaml, tests/integration/test_ols.py, tests/mock_classes/mock_k8s_api.py, tests/unit/utils/test_auth_dependency.py, tests/unit/utils/test_config.py
Enable Authentication support in OLS using Openshift/K8S SSAR.
the provided implementation doesnt make use of any centralized k8s client that makes token review for users,
instead we use SSAR with the User token for that.
- Related Issue #267 
- Closes #267 
=> OLS-118: Add Auth Support

.github/dependabot.yml
Change ecosystem for dependabot
=> Change ecosystem for dependabot

tests/unit/app/models/test_config.py
Query filter tests (for flow/branches not covered before)
=> Query filter tests (for flow/branches not covered before)

ols/app/endpoints/feedback.py, ols/app/endpoints/ols.py, ols/utils/auth_dependency.py
Types for new auth code
- Related Issue #[OLS-241](https://issues.redhat.com//browse/OLS-241)
=> OLS-241: Types for new auth code

ols/utils/auth_dependency.py
Trivial change: TODO word is recognized by IDEs and some linters
=> Trivial change: TODO word is recognized by IDEs and some linters

ols/src/llms/providers/bam.py, ols/src/llms/providers/openai.py, ols/src/llms/providers/watsonx.py
=> Param type hints

ols/src/llms/providers/bam.py, ols/src/llms/providers/watsonx.py
taken from https://ibm.ent.box.com/s/u4g9ph1va95ayu4ajnt93c0xy98z2tmp
- Closes #
=> Use IBM recommended params for granite model

pdm.lock, pyproject.toml
Security update: bump-up Gradio
https://github.com/advisories/GHSA-hmx6-r76c-85g9
- [x ] CVE fix
=> Security update: bump-up Gradio

ols/app/models/config.py, ols/src/llms/llm_loader.py, ols/src/llms/providers/provider.py
Updated and added missing type hints
=> OLS-364: Updated and added missing type hints

ols/app/main.py
Move query filter initialisation after logger is configured.
- Closes #
=> Move query filter after logger init

pdm.lock
=> Bump-up Prometheus client

ols/src/llms/providers/registry.py, pdm.lock, pyproject.toml
=> Added return type info

pdm.lock, pyproject.toml
Use latest Black [dev depencency]
=> Use latest Black [dev depencency]

ols/utils/auth_dependency.py
Auth deps type hints
The last part that does not allow us to test all missing types on CI
=> Auth deps type hints

pdm.lock
Update lockfile so PDM would be able to verify lockfile:
```
pdm lock --check --verbose
```
=> Update lockfile so PDM would be able to verify lockfile 

Makefile
All type hints are in, so we can (finally!) enable strict type checking
=> Strict type checking possible

tests/unit/app/metrics/__init__.py, tests/unit/app/metrics/test_token_counter.py
Unit test form `TokenCounter.on_llm_start` method
=> Unit test form `TokenCounter.on_llm_start` method

tests/unit/llms/providers/test_openai.py
Unit test: filtering OpenAI parameters
=> Unit test: filtering OpenAI parameters

tests/integration/test_metrics.py
(trivial) Counter metrics have labels now
=> (trivial) Counter metrics have labels now

tests/unit/app/metrics/test_token_counter.py
Unit test for `TokenCounter.on_llm_end` method
=> Unit test for `TokenCounter.on_llm_end` method

examples/openshift-lightspeed-tls.yaml
missed this change in https://github.com/openshift/lightspeed-service/pull/505/files#r1508116150
- Closes #
=> Add path to embedding model to sample config

ols/src/query_helpers/docs_summarizer.py
Link to Jira issue ([OLS-58](https://issues.redhat.com//browse/OLS-58)) to avoid bare TODOs
=> OLS-58: Link to Jira issue

tests/e2e/test_api.py
Basic metrics endpoint e2e test
=> Basic metrics endpoint e2e test

ols/constants.py, ols/utils/auth_dependency.py
Default user UID and name for local testing
(one TODO going to trash bin ;)
=> Default user UID and name for local testing

tests/e2e/test_api.py
E2E tests: check query REST API endpoint called with missing and improper payload
=> E2E tests: check query REST API endpoint called with missing and improper payload

ols/app/main.py
[OLS-364](https://issues.redhat.com//browse/OLS-364): Type fix: response is awaitable
=> OLS-364: Type fix: response is awaitable

tests/scripts/test-e2e-cluster.sh
=> OLS-371: Document more arguments for the e2e-cluster test script

tests/scripts/test-e2e-cluster.sh, tests/scripts/utils.sh
=> OLS-371: must-gather for e2e script, and install test dep prereqs

tests/scripts/test-e2e-cluster.sh
=> OLS-371: export ols token and url for e2e invocation

ols/app/main.py, ols/src/rag_index/index_loader.py, runner.py
Envs setting moved to runner.py
=> OLS-345: configuration in runner.py

tests/mock_classes/mock_llama_index.py, tests/unit/app/models/test_config.py
Proper `noqa` markers (trivial)
=> Proper noqa markers (trivial)

tests/integration/test_metrics.py
Don't rewrite loop variable inside loop
=> Don't rewrite loop variable inside loop

scripts/test-e2e-standalone.sh, tests/config/singleprovider.e2e.template.config.yaml
=> OLS-283: allow CI to run our e2e against azure openai

ols/src/llms/providers/openai.py
Link to Jira: handling OpenAI-related parameters
=> OLS-373: Link to Jira: handling OpenAI-related parameters

tests/config/cluster_install/ols_configmap.yaml, tests/config/singleprovider.e2e.template.config.yaml
=> Fix rag index id to align w/ updated versioned index names

ols/src/ui/gradio_ui.py
Avoid possible type error during logging (depends on logger):
```
TypeError: not all arguments converted during string formatting
```
=> Avoid possible type error during logging

ols/src/llms/providers/azure_openai.py
=> OLS-281: pass azure openai model parameters as model_kwargs

tests/e2e/test_api.py
Check auth. mechanism in e2e tests
=> Check auth. mechanism in e2e tests

examples/olsconfig.yaml, examples/openshift-lightspeed-tls.yaml
=> Update index id refs to use versioned index id

tests/e2e/test_api.py
Metrics checks in regular REST API calls
Not all possible cases are tested, it's just beginning, some utility functions etc.
=> Metrics checks in regular REST API calls

ols/utils/suid.py, tests/unit/app/endpoints/test_ols.py, tests/unit/cache/test_in_memory_cache.py, tests/unit/cache/test_redis_cache.py
Caught type errors during UUID checks.
- Related Issue #[OLS-378](https://issues.redhat.com//browse/OLS-378)
- Closes #[OLS-378](https://issues.redhat.com//browse/OLS-378)
=> OLS-378: Caught type errors during UUID checks

tests/e2e/test_api.py
REST API call checker as context manager
It allow us to simply add new checks w/o touching actual test functions
And the same approach can be used to check token counters
- Related Issue #[OLS-398](https://issues.redhat.com//browse/OLS-398)
- Closes #
=> OLS-398: REST API call checker as context manager

tests/e2e/test_api.py
Specify timeouts for all REST API calls performed in e2e tests
Allow us to quickly react when (for example) some model will be slower than usual (90 seconds now)
=> OLS-398: Specify timeouts for all REST API calls performed in e2e tests

ols/utils/query_filter.py
(Trivial) Don't shadow filter builtin
=> (Trivial) Don't shadow filter builtin

runner.py
Move config init from configure_hugging_face_envs
=> OLS-345: Move config init from configure_hugging_face_envs

ols/app/endpoints/ols.py, ols/src/cache/cache.py, ols/src/cache/in_memory_cache.py, ols/src/cache/redis_cache.py, ols/src/prompts/prompts.py, ols/src/query_helpers/chat_history.py, ols/src/query_helpers/docs_summarizer.py, tests/e2e/test_api.py, tests/integration/test_ols.py, tests/unit/app/endpoints/test_ols.py, tests/unit/cache/test_in_memory_cache.py, tests/unit/cache/test_redis_cache.py
Add ability to include previous conversations for user query
- Related Issue (https://issues.redhat.com/browse/OLS-110)
- [x ] I have performed a self-review of my code.
=> OLS-110:added conversation history

Containerfile.redis
Removed Vim package from Redis container file
=> Removed Vim package from Redis container file

ols/src/llms/providers/registry.py, tests/unit/llms/providers/test_providers.py
=> Use TypeError not ValueError

ols/app/models/config.py
Removed else block: not needed
=> Removed else block: not needed

ols/app/models/config.py
=> More readable condition flow

tests/unit/utils/test_config.py
Provide message to `pytest.fail` to be caught and processed by `pytest` tool
=> Provide message to `pytest.fail` to be caught and processed by `pytest` tool

tests/e2e/test_api.py
Check duration counters update for all REST API calls
- Related Issue #[OLS-398](https://issues.redhat.com//browse/OLS-398)
=> OLS-398: Check duration counters update for all REST API calls

ols/utils/token_handler.py
=> OLS-58: Ability to select tokenizer

ols/utils/token_handler.py, tests/unit/utils/test_token_handler.py
Helper method to compute message length
=> OLS-58: Helper method to compute message length

tests/unit/cache/__init__.py, tests/unit/docs/__init__.py, tests/unit/llms/__init__.py, tests/unit/llms/providers/__init__.py, tests/unit/query_helpers/__init__.py, tests/unit/ui/__init__.py, tests/unit/utils/__init__.py
(Minor) `__init__.py` for all unit tests sub-packages
=> `__init__.py` for all unit tests sub-packages

README.md, docs/openapi.json
Pre-generated OpenAPI schema + documentation update
- [] New feature
- Related Issue #[OLS-230](https://issues.redhat.com//browse/OLS-230)
=> OLS-230: Pre-generated OpenAPI schema + documentation update

ols/app/main.py, ols/app/metrics/__init__.py, ols/app/metrics/metrics.py, tests/integration/test_metrics.py
Expose selected model and provider through Prometheus metrics
- Related Issue #[OLS-307](https://issues.redhat.com//browse/OLS-307)
=> OLS-307 Expose selected model and provider through Prometheus metrics

tests/integration/test_openapi.py
Check pre-generated OpenAPI schema
- Related Issue #[OLS-230](https://issues.redhat.com//browse/OLS-230)
- use `make test-integration`
=> OSL-230: Check pre-generated OpenAPI schema

tests/e2e/test_api.py
Token counter checks in e2e tests
- Related Issue #[OLS-398](https://issues.redhat.com//browse/OLS-398)
- Closes #
- Run `make test-e2e`
=> OLS-398: Token counter checks in e2e tests

ols/src/query_helpers/docs_summarizer.py, ols/utils/token_handler.py, tests/unit/docs/test_doc_summarizer.py, tests/unit/utils/test_token_handler.py
=> OLS-58: Limit conversation history

ols/app/models/config.py, ols/constants.py, tests/unit/app/models/test_config.py
- Redis commands retry settings
- No changes made in Redis client (yet)
=> OLS-302: Redis commands retry settings

ols/src/cache/redis_cache.py
[OLS-302](https://issues.redhat.com//browse/OLS-302): Initialize Redis with retry settings (if provided and enabled)
- It is possible to change settings via `olsconfig.yaml`, block Redis (firewall etc.) and run the service
=> OLS-302: Initialize Redis with retry settings (if provided and enabled)

tests/unit/cache/test_redis_cache.py
Unit tests: Redis retry settings on Redis client initialization
- Use `make test-unit`
=> OLS-302: Unit tests: Redis retry settings on Redis client initialization

tests/scripts/test-e2e-cluster.sh
=> Use the ols image built by the PR when testing

ols/src/cache/redis_cache.py
Bug fix: marshal and unmarshal messages to be stored in Redis
(new `list[BaseMessage]` can't be stored directly)
Tested against real Redis
=> Bug fix: marshal and unmarshal messages to be stored in Redis

tests/mock_classes/redis.py
Stricter Redis mock to avoid errors like [OLS-416](https://issues.redhat.com//browse/OLS-416)
- Related Issue #[OLS-416](https://issues.redhat.com//browse/OLS-416)
=> Stricter Redis mock to avoid errors like OLS-416

tests/mock_classes/mock_redis_client.py, tests/unit/cache/test_cache_factory.py, tests/unit/cache/test_redis_cache.py
Renamed: `MockRedisClient`
Context: we'll need to introduce mocked Redis pipeline soon
=> Renamed: MockRedisClient

CONTRIBUTING.md
Update docs about adding new provider
=> Update docs about adding new provider

ols/utils/auth_dependency.py
Test for several values using membership test against set
More idiomatic and faster approach
=> Test for several values using membership test against set

ols/src/query_helpers/docs_summarizer.py, ols/utils/token_handler.py, tests/unit/utils/test_token_handler.py
`limit_conversation_history` is static method
=> `limit_conversation_history` is static method

scripts/asciidoctor-text/convert-it-all.py
Use opened file as context manager
File will be closed automatically in all circumstances
=> Bug fix: use opened file as context manager

ols/app/metrics/__init__.py
Sorted identifiers in `__all__`
=> Sorted identifiers in `__all__`

examples/olsconfig.yaml, ols/app/models/config.py, tests/unit/app/models/test_config.py
Add config for ols user data collection.
=> OLS-387: Add user data collection config

pdm.lock, pyproject.toml
=> Bump-up OpenAI to 1.14.0

pdm.lock
=> Bump-up devel dependencies: Black

examples/openshift-lightspeed-tls.yaml
will delete the old service once the console is updated.
- Closes #
=> use consistent service name between example and operator

ols/app/models/config.py, tests/unit/app/models/test_config.py
Allow model options (fully optional)
It will be passed to prompt generator (TBD)
- Related Issue #[OLS-244](https://issues.redhat.com//browse/OLS-244)
=> OLS-244: Allow model options (fully optional)

scripts/asciidoctor-text/convert-it-all.py
(Trivial) Use shebang for executable script
=> Use shebang for executable script

pdm.lock, pyproject.toml
=> Spacy package as dependency

ols/src/query_helpers/docs_summarizer.py
Better local symbol names
These symbols will be used in prompt generator later (too)
- Related Issue #[OLS-244](https://issues.redhat.com//browse/OLS-244)
=> OLS-244: Better local symbol names

pdm.lock
Update Ruff (devel dependency)
=> Update Ruff (devel dependency)

.gitignore, pyproject.toml, scripts/questions_gen.py
- [V] New feature
- Closes #
- [V] I have performed a self-review of my code.
=> added gen question script

ols/app/endpoints/ols.py
Refactoring - retrieve user ID
(it will be used in several parts of code)
=> Refactoring - retrieve user ID

examples/openshift-lightspeed-tls.yaml
=> Add RBAC roles for SAR checking and OLS usage to example setup

scripts/questions_gen.py
=> Refactoring: use match-case

scripts/asciidoctor-text/convert-it-all.py
Refactoring: moved expression out of the loop
=> Refactoring: moved expression out of the loop

scripts/generate_embeddings.py
Refactoring: use `dict` constructor
=> Refactoring: use dict constructor

docs/openapi.json, ols/app/endpoints/feedback.py, ols/app/models/config.py, ols/app/models/models.py, tests/config/cluster_install/ols_configmap.yaml, tests/config/cluster_install/ols_manifests.yaml, tests/config/singleprovider.e2e.template.config.yaml, tests/e2e/test_api.py, tests/integration/test_feedback.py, tests/scripts/test-e2e-standalone.sh, tests/unit/app/endpoints/test_feedback.py, tests/unit/app/models/test_config.py, tests/unit/app/models/test_models.py
Implementation of the feedback storage system.
[OLS-397](https://issues.redhat.com/browse/OLS-397)
[OLS-387](https://issues.redhat.com/browse/OLS-387)
=> OLS-135: feedback storage

pdm.lock, pyproject.toml
Updated Ruff as devel dependency
=> Updated Ruff as devel dependency

ols/app/models/config.py, ols/constants.py, ols/src/cache/cache_factory.py, ols/src/cache/postgres_cache.py, tests/config/postgres_password.txt, tests/config/valid_config_postgres.yaml, tests/unit/app/models/test_config.py, tests/unit/utils/test_config.py
Postgres configuration
- Related Issue #[OLS-440](https://issues.redhat.com//browse/OLS-440)
=> OLS-440: Postgres configuration

ols/app/models/config.py
Refactoring: not too nested logic flow
=> Refactoring: not too nested logic flow

tests/e2e/test_api.py
Model settings metrics tests
- Related Issue #[OLS-437](https://issues.redhat.com//browse/OLS-437)
=> OLS-437: Model settings metrics tests

scripts/questions_gen.py
Refactoring: use `dict` constructor
- Closes #
=> Refactoring: use `dict` constructor

ols/src/ui/gradio_ui.py
Refactoring: `else` block not needed
=> Refactoring: `else` block not needed

tests/unit/llms/providers/test_bam.py, tests/unit/llms/providers/test_watsonx.py
Bug fix: fixed provider unit tests
=> OSL-363: Bug fix: fixed provider unit tests

Makefile
=> Prepend provider to test class names

tests/unit/llms/providers/test_bam.py, tests/unit/llms/providers/test_watsonx.py
(Trivial) Correct provider names
=> (Trivial) Correct provider names

ols/src/prompts/prompt_generator.py
Stricter type checking in `prompt_generator.py`
=> Stricter type checking in `prompt_generator.py`

ols/src/query_helpers/question_validator.py
TODO: refactoring params from `QuestionValidator`
=> OLS-447: Added TODO: refactoring params from QuestionValidator

scripts/validate_response.py, tests/e2e/conftest.py, tests/e2e/test_api.py, tests/test_data/question_answer_pair.json
- Add question ids to QnA json file.
- Load QnA based on id from file in e2e test cases (currently model/scenario hard coded)
Script changes for passing arguments to pytest will be done separate PR.
- Related Issue # [OLS-434](https://issues.redhat.com//browse/OLS-434)
=> OLS-434: e2e test - load QnA from file

Containerfile, Containerfile.rag
=> Move towards a single ols image that includes rag

examples/olsconfig.yaml, examples/openshift-lightspeed-tls.yaml
=> Remove use of ols-rag image, ols image includes rag now

ols/src/llms/providers/provider.py, tests/unit/llms/providers/test_azure_openai.py, tests/unit/llms/providers/test_openai.py
Provider parameters check
- Related Issue #[OLS-363](https://issues.redhat.com//browse/OLS-363)
=> OLS-363: Provider parameters check

.gitignore, examples/olsconfig.yaml, examples/openshift-lightspeed-tls.yaml
Update latest default vector db folder name.
=> Add latest vec db folder to gitignore/example

examples/olsconfig.yaml, ols/app/models/config.py, runner.py, tests/unit/app/models/test_config.py, tests/unit/utils/test_config.py
=> Uvicorn log level settings

tests/e2e/cluster_utils.py, tests/e2e/consts.py, tests/e2e/metrics_utils.py, tests/e2e/test_api.py, tests/e2e/test_utils.py, tests/scripts/test-e2e-standalone.sh, tests/scripts/utils.sh
also refactor some of the e2e helper code into utils modules
- Closes #
=> Convert e2e test script logic into python code

Makefile, tests/e2e/conftest.py, tests/e2e/consts.py, tests/e2e/test_api.py, tests/scripts/utils.sh, tests/test_data/question_answer_pair.json
Pass arguments to e2e from script
- Related Issue # [OLS-434](https://issues.redhat.com//browse/OLS-434)
=> OLS-434: Pass arguments to e2e

Containerfile.rag
=> Remove old rag containerfile

examples/olsconfig.yaml, ols/constants.py
=> Bump default context window size to 8000, to align w/ granite v2

ols/app/metrics/__init__.py, ols/app/metrics/metrics.py, tests/e2e/metrics_utils.py, tests/e2e/test_api.py, tests/integration/test_metrics.py
=> OLS-117: combine provider+model enabled metric

README.md
Update readme to use new vector db to local
=> Update readme for local vector db

tests/e2e/cluster_utils.py
=> Fixed type hints in e2e tests

tests/e2e/test_api.py
Bug fix: allow local e2e testing
=> Bug fix: allow local e2e testing

ols/src/llms/providers/bam.py
=> Fix deprecated import in bam

ols/app/metrics/token_counter.py
Token counter fix
Re Jira @bparees "I think we do not need the "on_llm_start" callback at all. ". I think that we need to "remember" input prompt or token length from it, as it is not available when `on_llm_end` is called. I keep counting tokens there, but we can just store input prompt instead and defer token counting only when needed at the end of `on_llm_end`. So it's a bit mem/cpu tradeoff (+ tiktoken counter is fast, so probably it is not too limiting. Actual tokenization speed on my i7:
```
Tokens: 1000000
Time: 0.7104394719935954 seconds
1407579 tokens per second
```
- Related Issue #[OLS-446](https://issues.redhat.com//browse/OLS-446)
=> OLS-446: Token counter fix

tests/e2e/metrics_utils.py
Optional metrics retriever return value
=> Optional metrics retriever return value

ols/app/models/config.py, ols/constants.py, tests/unit/app/models/test_config.py, tests/unit/utils/test_config.py
Check: default model and provider are required
=> Check: default model and provider are required

tests/e2e/test_api.py
=> Run metrics e2e tests in cluster envs

ols/app/main.py
Implemented logging of HTTP requests and responses going to and from OLS FastAPI. Said logging only occurs if `ols_config.logging_config.app_log_level` is set to `debug`. For correlation of requests and responses, client_IP:port are logged.
- Closes # https://issues.redhat.com/browse/OLS-375
An example of log for a conversation with Gradio UI:
```
2024-03-28 23:09:09,140 [ols.app.main:main.py:76] DEBUG: Request from 127.0.0.1:33730 Headers({'host': '127.0.0.1:8080', 
'user-agent': 'python-requests/2.31.0', 'accept-encoding': 'gzip, deflate', 'accept': 'application/json', 'connection': …
```
=> OLS-375: Log OLS HTTP request+response payloads

tests/unit/prompts/test_prompt_generator.py
More precise test parameter description
(original code was ok, but the new is parametrizable)
=> More precise test parameter description

ols/constants.py, ols/src/prompts/prompts.py, ols/src/query_helpers/question_validator.py
Move all prompt templates to prompt.py file.
Minor grouping of constants.
Most of the templates are unused, but keeping these for now..
=> Move prompt templates to prompt file

Makefile, scripts/validate_response.py, tests/scripts/utils.sh
- Make target for response evaluation.
- Run only if flag is set for evaluation.
- Related Issue # [OLS-434](https://issues.redhat.com//browse/OLS-434)
- Closes #
=> OLS-434: make target for response evaluation

pyproject.toml
Llama-index is indeed used in production code
=> Llama-index is indeed used in production code

README.md
=> Info about other providers

CONTRIBUTING.md
Documentation update: info about coverage
=> Documentation update: info about coverage

docs/openapi.json, ols/app/endpoints/ols.py, ols/app/models/models.py, tests/integration/test_ols.py, tests/unit/app/endpoints/test_ols.py
[OLS-419](https://issues.redhat.com//browse/OLS-419): More detailed errors in HTTP REST API responses
An example of error response (formatted using `jq`):
```
Sorry, an error occurred:
{
"detail": {
"response": "Error while validating question",
"cause": "Failed to handle request to [https://bam-api.res.ibm.com/v2/text/generation/limits?version=2023-11-22.\n{\n](https://bam-api.res.ibm.com/v2/text/generation/limits?version=2023-11-22.%5Cn%7B%5Cn) 'error': 'Unauthorized',\n 'extensions': {\n 'code': 'AUTH_ERROR',\n 'state': null,\n 'reason': 'TOKEN_INVALID'\n },\n 'message': 'Invalid or missing JWT token',\n 'status_code': 401\n}"
}
}
```
- Closes #
=> OLS-419: More detailed errors in HTTP REST API responses

tests/e2e/test_api.py
Conversation ID checks in REST API tests: better error description is expected
- Closes #
=> OLS-419 Conversation ID checks in REST API tests

ols/app/metrics/metrics.py, tests/e2e/metrics_utils.py, tests/e2e/test_api.py, tests/integration/test_metrics.py
=> OLS-117: Disable built in metrics and prefix ols metrics with ols_

ols/app/endpoints/ols.py, tests/config/valid_config.yaml, tests/e2e/cluster_utils.py, tests/e2e/test_api.py, tests/integration/test_ols.py, tests/unit/app/endpoints/test_ols.py
=> OLS-139: Adds transcripts collection.

tests/e2e/__init__.py, tests/e2e/test_api.py
=> Minor e2e tests fixes

pdm.lock, pyproject.toml
Updates for 2004 w15
- Related Issue #[OLS-420](https://issues.redhat.com//browse/OLS-420)
- Closes #
=> OLS-420: Updates for 2004 w15

scripts/generate_openapi_schema.py
Bug fix: schema generation
- Closes #
=> Bug fix: schema generation

docs/openapi.json, ols/app/endpoints/ols.py, ols/app/models/models.py
Added 401 and 403 HTTP codes for query REST API endpoint spec
- Closes #
=> OSL-419: Added 401 and 403 HTTP codes for query REST API endpoint spec

tests/e2e/test_api.py, tests/unit/utils/test_auth_dependency.py
Consistent usage of parenthesis for all fixtures
(Linter rule will be added in separate PR, as usual)
=> Consistent usage of parenthesis for all fixtures

tests/e2e/__init__.py, tests/e2e/test_api.py
E2e tests for provider and model
- Closes #
=> OLS-419: E2e tests for provider and model

ols/utils/token_handler.py, scripts/validate_response.py, tests/e2e/constants.py
Map stories against TODOs for evaluation/token handler
=> OLS-373: map stories against TODOs

ols/src/cache/cache_factory.py, tests/unit/app/endpoints/test_ols.py
[OLS-373](https://issues.redhat.com//browse/OLS-373): updated TODO with link to [OLS-440](https://issues.redhat.com//browse/OLS-440)
- Closes #
=> OLS-373: updated TODO with link to OLS-440

ols/src/prompts/prompt_generator.py
Removed wrongly placed TODOs (there are not real TODOs, just places in code that can be configured and modified later)
=> OLS-373: Removed wrongly placed TODOs

docs/openapi.json, ols/app/endpoints/authorized.py, ols/utils/auth_dependency.py
Better error messages for auth. endpoint
=> OLS-419: Better error messages for auth. endpoint

ols/app/endpoints/health.py, ols/utils/auth_dependency.py
Add TODO for [OLS-495](https://issues.redhat.com//browse/OLS-495)
- Closes #
=> OLS-373: Add TODO for OLS-495

ols/src/llms/providers/azure_openai.py
Add TODO for [OLS-496](https://issues.redhat.com//browse/OLS-496)
- Closes #
=> OLS-373: Add TODO for OLS-496

ols/src/prompts/prompts.py
Add TODO for [OLS-503](https://issues.redhat.com//browse/OLS-503): Fine tune system prompt
- Closes #
=> OLS-373: Add TODO for OLS-503

pdm.lock, pyproject.toml
See https://github.com/IBM/ibm-cos-sdk-python/issues/60 for further info
- Closes #
=> OLS-373: Don't lock types-requests version, not needed

docs/openapi.json, ols/app/metrics/metrics.py
Metrics response is in plain text format
- Closes #
=> OLS-419: Metrics response is in plain text format

scripts/questions_gen.py
Added link to Jira issue [OLS-505](https://issues.redhat.com//browse/OLS-505)
- Closes #
=> OLS-373: Link to Jira issue OLS-505

tests/e2e/test_api.py
Link to Jira issue [OLS-506](https://issues.redhat.com//browse/OLS-506)
- Closes #
=> OLS-373: Link to Jira issue OLS-506

tests/e2e/test_api.py
Check content type in e2e tests
- Closes #
=> OLS-419: Check content type in e2e tests

docs/openapi.json, ols/app/models/models.py
Fixed feedback object example used on Swagger page
- Closes #
=> OLS-419: fixed feedback object example used on Swagger page

scripts/validate_response.py
Option to use api url retrieved from cluster for response evaluation.
This is required as weekly job for evaluation run against api deployed in a cluster (https://github.com/openshift/release/pull/50793)
=> OLS-434: Use cluster url for evaluation

ols/app/models/config.py, tests/config/postgres_password.txt, tests/unit/app/models/test_config.py
Read password for Postgres from file
- Related Issue #[OLS-440](https://issues.redhat.com//browse/OLS-440)
=> OLS-440: Read password for Postgres from file

docs/openapi.json, ols/app/endpoints/feedback.py
User feedback HTTP responses
- Closes #
=> OLS-419: User feedback HTTP responses

scripts/validate_response.py
=> Fixed argument types

pdm.lock, pyproject.toml
=> Bump-up Ruff to version 0.3.7

ols/app/models/models.py, tests/unit/app/models/test_models.py
[OLS-419](https://issues.redhat.com//browse/OLS-419): Check conversation ID for feedback endpoint
- Closes #
=> OLS-419: Check conversation ID for feedback endpoint

tests/e2e/cluster_utils.py
Simplify `cluster_utils.py` a bit
=> Simplify `cluster_utils.py` a bit

tests/e2e/test_api.py
Feedback e2e tests for improper input
- Closes #
=> OLS-419: Feedback e2e tests for improper input

ols/src/llms/providers/azure_openai.py
=> move to newer azure api version

tests/integration/test_authorized.py, tests/integration/test_feedback.py, tests/integration/test_liveness_readiness.py, tests/integration/test_metrics.py, tests/integration/test_ols.py, tests/integration/test_ols_debug.py, tests/integration/test_openapi.py
Fix [OLS-513](https://issues.redhat.com//browse/OLS-513): ability to run integration tests independently
- Related Issue #[OLS-512](https://issues.redhat.com//browse/OLS-512)
- Closes #
=> Fix OLS-513: ability to run integration tests independently

tests/scripts/test-e2e-cluster.sh, tests/scripts/utils.sh
=> Fix run_suite exit code handling, avoid variable shadowing

tests/e2e/conftest.py, tests/e2e/test_api.py
=> Fixed argparser type

tests/integration/test_ols.py
Integration test: query withoutimproper conversation ID
=> Integration test: query without improper conversation ID

ols/app/endpoints/feedback.py
[OLS-419](https://issues.redhat.com//browse/OLS-419): Removed inaccessible statement
- Closes #
=> OLS-419: Removed inaccessible statement

ols/app/endpoints/ols.py, ols/src/query_helpers/question_validator.py, ols/utils/token_handler.py, tests/e2e/test_api.py, tests/unit/utils/test_token_handler.py
- [OLS-469](https://issues.redhat.com//browse/OLS-469): Prompt limit check
- Unit tests for the new code (+ added even more unit tests for the modified method)
- Related Issue #[OLS-469](https://issues.redhat.com//browse/OLS-469)
- Closes #
=> OLS-469: Prompt limit check

docs/openapi.json, ols/app/endpoints/ols.py, ols/app/models/models.py
Prompt too long response in schema
- Related Issue #[OLS-469](https://issues.redhat.com//browse/OLS-469)
- Closes #
=> OLS-469: Prompt too long response in schema

CONTRIBUTING.md
Hint in contribution guide: detecting live and dead code
=> Hint in contribution guide: detecting live and dead code

Containerfile
Allows to avoid unnecessary container rebuilding when changing the OLS code
- Closes https://issues.redhat.com/browse/OLS-497
- [] PR has passed all pre-merge test jobs.
=> OLS-497: minimize image rebuilds by leveraging layer caching

tests/integration/test_feedback.py, tests/unit/app/endpoints/test_feedback.py
Improve feedback tests coverage
=> Improve feedback tests coverage

tests/e2e/test_api.py
Elementary OpenAPI check in e2e tests
=> Elementary OpenAPI check in e2e tests

ols/app/models/config.py, ols/constants.py, ols/src/cache/cache_error.py, ols/src/cache/cache_factory.py, ols/src/cache/postgres_cache.py, pdm.lock, pyproject.toml, tests/config/valid_config_postgres.yaml, tests/e2e/postgres_utils.py, tests/e2e/test_api.py, tests/unit/app/models/test_config.py, tests/unit/cache/test_cache_factory.py, tests/unit/cache/test_postgres_cache.py, tests/unit/utils/test_config.py
=> OLS-440: Postgres-based cache

.coveragerc, .gitignore, examples/openshift-lightspeed-tls.yaml, ols/user_data_collection/__init__.py, ols/user_data_collection/data_collector.py, tests/config/cluster_install/ols_manifests.yaml, tests/e2e/cluster_utils.py, tests/e2e/test_api.py, tests/unit/user_data_collection/test_data_collector.py
Script that collects data, packages it, and sends it to ingress.
TODO:
=> OLS-136: data to ingress

ols/app/models/config.py, ols/constants.py, tests/unit/app/models/test_config.py
Model-specific default context window size
- Related Issue #[OLS-469](https://issues.redhat.com//browse/OLS-469)
- Closes #
=> OLS-469: Model-specific default context window size

pdm.lock, pyproject.toml, tests/integration/test_ols.py
Update Fastapi and Pydantic
- Related Issue #[OLS-448](https://issues.redhat.com//browse/OLS-448)
- Closes #
=> OLS-448: Update Fastapi and Pydantic

pyproject.toml
Added more linters that are part of recent Ruff
=> Added more linters that are part of recent Ruff

ols/src/rag_index/index_loader.py, ols/utils/config.py, ols/utils/query_filter.py, runner.py
Link to Jira issues #380 and #381
=> Link to Jira issues #380 and #381

pdm.lock, pyproject.toml
=> OLS-448: Bump project deps

ols/user_data_collection/data_collector.py
Handling of errors for fet k8s objects.
- [OLS-486](https://issues.redhat.com/browse/OLS-486)
=> OLS-136: Handle data collector errors

docs/openapi.json, ols/app/models/models.py, tests/unit/app/models/test_models.py
Something I noticed during Pavel's demo. We don't have an explicit check for the value. We allow either good(1) or bad(-1).
=> Add sentiment field validation for feedback model

tests/integration/test_feedback.py, tests/unit/app/models/test_models.py
More unit and integration tests for `sentiment` attribute
=> More unit and integration tests for sentiment attribute

ols/user_data_collection/data_collector.py, tests/config/cluster_install/ols_manifests.yaml, tests/scripts/utils.sh
Collect logs from all containers in artifacts
=> Collect logs from all containers in artifacts

tests/e2e/test_api.py
More readable assert error message in e2e tests
=> More readable assert error message in e2e tests

pdm.lock, pyproject.toml
=> Removed Spacy lib

ols/src/llms/providers/azure_openai.py, tests/config/valid_config_with_azure_openai.yaml, tests/config/valid_config_with_azure_openai_api_version.yaml, tests/unit/llms/providers/test_azure_openai.py, tests/unit/utils/test_config.py
[OLS-496](https://issues.redhat.com//browse/OLS-496): API version is parametrized for Azure OpenAI
Updated tests as well
- Related Issue #[OLS-496](https://issues.redhat.com//browse/OLS-496)
=> OLS-496: API version is parametrized for Azure OpenAI

README.md
Info about PostgreSQL (documentation update)
=> Info about PostgreSQL (documentation update)

pdm.lock, pyproject.toml
=> Bump-up Torch(cpu) to 2.2.2

ols/src/query_helpers/query_docs.py
Exception chaining in query docs for better stack trace readiblity
=> OLS-538: Exception chaining in query docs for better stack trace readiblity

README.md
Removed Redis from documentation in `README.md`
=> Removed Redis from documentation in README.md

ols/app/endpoints/ols.py, ols/constants.py, ols/src/prompts/prompt_generator.py, ols/src/query_helpers/docs_summarizer.py, scripts/validate_response.py, tests/e2e/test_api.py, tests/integration/test_ols.py, tests/unit/prompts/test_prompt_generator.py
=> Remove the "no rag used in response" prefix message from ols responses

ols/user_data_collection/data_collector.py
=> Retrieve clusterversion object by correct name

runner.py
=> Remove obsolete todo

ols/user_data_collection/data_collector.py, tests/e2e/cluster_utils.py, tests/e2e/test_api.py
Ability to control collector via file existence
=> OLS-508: Ability to control collector via file existence

scripts/feedback_aggregator.py
- Strip endlines from query + LLM response for better output table.
- Full quoting in CSV cells (not nice to read, but safer for readers)
- Related Issue #[OLS-549](https://issues.redhat.com//browse/OLS-549)
- Closes #
=> OLS-549: Proper output to CSV file

ols/app/endpoints/ols.py, ols/src/prompts/prompt_generator.py, ols/src/query_helpers/docs_summarizer.py, ols/utils/token_handler.py, tests/integration/test_ols.py, tests/unit/app/endpoints/test_ols.py, tests/unit/prompts/test_prompt_generator.py, tests/unit/query_helpers/test_docs_summarizer.py, tests/unit/utils/test_token_handler.py
Include role and new line for history token calculation.
This will make sure that final token count is not beyond context window.
[OLS-548](https://issues.redhat.com/browse/OLS-548)
=> consider role for history tokens

tests/unit/app/endpoints/test_ols.py
[OLS-538](https://issues.redhat.com//browse/OLS-538): Unit test for too long prompt exception
- Closes #
=> OLS-538: Unit test for too long prompt exception

tests/unit/llms/providers/test_providers.py
Unit test for checking provider type
- Closes #
- Run `make test-unit` as usual
=> OLS-447: Unit test for checking provider type

scripts/feedback_aggregator.py
See second sheet for example outputs:
https://docs.google.com/spreadsheets/d/15F1gka4seEFA45qiuHcTraP8ui88SY-jrIY5H1FUzRg/edit#gid=77087141
=> Ability to aggregate full conversation history for user feedback

Makefile, tests/e2e/test_api.py, tests/scripts/validate_response.py
Move validation script to tests. It is only used there. It is causing some problems with imports.
=> OLS-506: Move testing script ot tests

scripts/feedback_aggregator.py
Ability to export referenced documents in conversation history
See it in action on second sheet there:
https://docs.google.com/spreadsheets/d/15F1gka4seEFA45qiuHcTraP8ui88SY-jrIY5H1FUzRg/edit#gid=171711864
- Related Issue #[OLS-137](https://issues.redhat.com//browse/OLS-137)
- Closes #
=> OLS-137: Ability to export referenced documents in conversation history

ols/user_data_collection/data_collector.py
Proper type for request headers
(to be linted correctly by all type checkers)
=> Proper type for request headers

ols/app/models/config.py, ols/src/llms/providers/watsonx.py, tests/unit/app/models/test_config.py, tests/unit/llms/providers/test_providers.py, tests/unit/llms/providers/test_watsonx.py
Watsonx is written with lowercase "x" at the end
(nitpick-controlled PR ;)
=> Proper Watsonx name

scripts/feedback_aggregator.py
=> Proper return type (fix)

tests/e2e/cluster_utils.py
Return value fix (we can simply return `None`, the only distinction between success and failure is signaled by exception raised)
=> Return value fix

tests/scripts/utils.sh
=> Add junit reporting for ols setup failures

tests/scripts/validate_response.py
Don't use magic constant in tests
=> Don't use magic constant in tests

Makefile, tests/scripts/utils.sh, tests/scripts/validate_response.py
Save response eval result csv file during CI execution.
=> Save CI response eval job result

ols/app/models/config.py
Use filepath instead of raw string
- Related Issue #[OLS-259](https://issues.redhat.com//browse/OLS-259)
- Closes #
=> OLS-259: Use filepath instead of raw string

tests/scripts/utils.sh
Fix logging in the number of attempts
=> Fix logging in the number of attempts

tests/unit/llms/test_llm_loader.py
Based on conversation there https://github.com/openshift/lightspeed-service/pull/857#pullrequestreview-2036292089
=> Fixed unit test

ols/constants.py, ols/src/llms/llm_loader.py, ols/src/llms/providers/provider.py, ols/src/query_helpers/docs_summarizer.py, ols/src/query_helpers/query_helper.py, ols/src/query_helpers/question_validator.py, tests/mock_classes/mock_llm_loader.py, tests/unit/llms/providers/test_watsonx.py, tests/unit/query_helpers/test_query_helper.py, tests/unit/query_helpers/test_question_validator.py
[OLS-447](https://issues.redhat.com//browse/OLS-447): LLM parameters mapping
- Closes #
=> OLS-447: LLM parameters mapping

Containerfile, Makefile, README.md, examples/openshift-lightspeed-tls.yaml, scripts/build-container.sh
do not merge until https://github.com/openshift/release/pull/51603 has merged and we see mirroring to the new quay repos is working.
- Closes #
=> Update quay references to use the openshift-lightspeed org

ols/constants.py
=> OLS-423: use a generic message for rejecting non-openshift questions

tests/e2e/cluster_utils.py
Don't reuse the same variable for different purposes
It is just local change, but yet will help the linters to figure out what can go wrong
=> Don't reuse the same variable for different purposes

scripts/questions_gen.py
[OLS-582](https://issues.redhat.com//browse/OLS-582): Don't pass ServiceContext
- Related Issue #[OLS-582](https://issues.redhat.com//browse/OLS-582)
=> OLS-582: Don't pass ServiceContext

ols/src/query_helpers/query_docs.py
List of documents is no longer optional (API we call has changed)
=> List of documents is no longer optional (API we call has changed)

tests/e2e/cluster_utils.py, tests/e2e/test_api.py, tests/scripts/must_gather.py, tests/scripts/utils.sh
Move after tests must-gather logic to python tests
=> OLS-506: must-gather in tests

tests/e2e/cluster_utils.py
Added missing `return` statement
=> Added missing `return` statement

tests/integration/test_ols.py
Use `Path` value properly in tests
(+ checks of Optional values for mocked configuration)
=> Use `Path` value properly in tests

runner.py, tests/unit/utils/__init__.py
Specify host in all cases
- Related Issue #[OLS-589](https://issues.redhat.com//browse/OLS-589)
- Closes #
=> OLS-589: Specify host in all cases

scripts/list_objects_in_ceph.py
Script to list objects stored in Ceph bucket
(will be also used as an example in our internal documentation)
=> Script to list objects stored in Ceph bucket

.gitignore
Ignore `__pypackages__` directory
(used by some IDEs in similar way as `.venv`)
=> Ignore __pypackages__ directory

scripts/feedback_aggregator.py
[OLS-591](https://issues.redhat.com//browse/OLS-591): ignore cluster used by CCX checking infrastructure
- Related Issue #[OLS-591](https://issues.redhat.com//browse/OLS-591)
=> OLS-591: ignore cluster used by CCX checking infrastructure

tests/integration/test_authorized.py
=> Fixtures for authorization

ols/app/models/config.py, ols/constants.py, ols/src/cache/cache_factory.py, ols/src/cache/in_memory_cache.py, tests/unit/app/models/test_config.py, tests/unit/cache/test_cache_factory.py, tests/unit/cache/test_in_memory_cache.py
`MemoryConfig` is basically meaningles, let's use better self-documented name instead
- Closes #
=> Use proper in memory cache config class name

scripts/data_collection/README.md, scripts/data_collection/download_ols_archive.py
Script to download object from Ceph
+Documentation
- Closes #
=> OLS-598: Script to download object from Ceph

Makefile
=> Print e2e tests durations

docs/openapi.json, ols/app/models/models.py
Add missing field in schema for LLMResponse.
=> Add missing field in schema for LLMResponse

scripts/data_collection/user_data_aggregator.py
Allow spaces in cluster list
- Closes #
=> OSL-598: Allow spaces in cluster list

scripts/data_collection/README.md, scripts/data_collection/delete_ols_archive.py
Script to delete OLS archive from Ceph bucket
This is the last thing that is missing to close [OLS-598](https://issues.redhat.com//browse/OLS-598)
- Closes #
=> OLS-598: Script to delete OLS archive from Ceph bucket

ols/src/cache/postgres_cache.py
Remove unreachable return from postgres cache
=> Remove unreachable return from postgres cache

ols/utils/auth_dependency.py, tests/unit/app/models/test_config.py
"None" (string) are not special values to be checked for auth. attributes
=> "None" (string) are not special values to be checked for auth. attributes

tests/e2e/test_decorators.py
Better retry logic for flaky end-to-end tests
- it is possible to specify error type
- it is possible to specify which text must be included in error message
=> Better retry logic for flaky end-to-end tests

scripts/questions_gen.py
TODO with [OLS-619](https://issues.redhat.com//browse/OLS-619)
=> TODO with OLS-619

ols/user_data_collection/data_collector.py, tests/e2e/test_api.py, tests/unit/user_data_collection/test_data_collector.py
Chunk collected user data to archives and ensure the data dir can't grow over the limit.
=> OLS-473: Chunk collected user data to archives

ols/app/endpoints/ols.py, ols/src/cache/cache.py, ols/src/cache/in_memory_cache.py, ols/src/cache/postgres_cache.py, ols/src/cache/redis_cache.py
Full type specification for conversation history
=> Full type specification for conversation history

scripts/data_collection/README.md, scripts/data_collection/update_google_sheet.py
Script to upload CSV files into Google sheet
- Related Issue #[OLS-626](https://issues.redhat.com//browse/OLS-626)
- Closes #
=> OLS-626: Script to upload CSV files into Google sheet

tests/e2e/test_api.py
Fix [OLS-596](https://issues.redhat.com//browse/OLS-596): timeout in BAM provider
-
- Related Issue #[OLS-596](https://issues.redhat.com//browse/OLS-596)
- Closes #
=> Fix OLS-596: timeout in BAM provider

tests/scripts/test-e2e-cluster.sh
=> Re-enable BAM for e2e testing

CONTRIBUTING.md
Just for the sake of completeness.
=> Add tip for local e2e testing

tests/e2e/test_api.py
[OLS-570](https://issues.redhat.com//browse/OLS-570): log test stage in case of any detected error
- Related Issue #[OLS-570](https://issues.redhat.com//browse/OLS-570)
- Closes #
=> OLS-570: log test stage in case of any detected error

tests/e2e/test_api.py
Check schema against pre-generated one
- Related Issue #[OLS-570](https://issues.redhat.com//browse/OLS-570)
- Closes #
=> OLS-570: Check schema against pre-generated one

tests/e2e/test_api.py
Fix unexpected and random 503 HTTP failures accessing openapi.json
- Related Issue #[OLS-570](https://issues.redhat.com//browse/OLS-570)
- Closes #
=> OLS-570: Fix unexpected and random 503 HTTP failures accessing openapi.json

ols/src/cache/postgres_cache.py, ols/src/cache/redis_cache.py, tests/e2e/test_api.py, tests/unit/cache/test_postgres_cache.py
Don't use pickle module, now it is possible to use simple JSON
=> Don't use pickle module, now it is possible to use simple JSON

tests/unit/rag_index/test_index_loader.py
Fixture with OLS configuration used in unit tests + use `Path` object as expected
=> Fixture with OLS configuration used in unit tests + use Path object as expected

pdm.lock, pyproject.toml
Added Bandit as devel dependencies
=> Added Bandit as devel dependencies

ols/app/endpoints/ols.py, ols/src/cache/cache.py, ols/src/cache/in_memory_cache.py, ols/src/cache/postgres_cache.py, ols/src/cache/redis_cache.py
Type safer working with list of messages
=> Type safer working with list of messages

tests/mock_classes/mock_retrievers.py
Mock all methods for mock vector store
- Related Issue #[OLS-612](https://issues.redhat.com//browse/OLS-612)
- Closes #
=> OLS-612: Mock all methods for mock vector store

scripts/data_collection/update_google_sheet.py
=> Fix: added missing shebang

ols/src/prompts/prompts.py, tests/config/valid_config.yaml, tests/unit/utils/test_config.py
A better system prompt, based on EA feedback.
- Related Issues # https://issues.redhat.com/browse/OLS-572, https://issues.redhat.com/browse/OLS-545, https://issues.redhat.com/browse/OLS-528
- Closes # https://issues.redhat.com/browse/OLS-503
=> OLS-503: Fine-tune system prompt

ols/app/endpoints/feedback.py, tests/unit/app/endpoints/test_feedback.py
=> added timestamp to feedback endpoint (OLS-616)

ols/app/models/config.py
Provider config refactoring (the function is too long right now and will be even longer with provider-specific config code)
- Closes #
=> OLS-622: Provider config refactoring

ols/app/models/config.py
Main config attributes are not optional anymore
=> Main config attributes are not optional anymore

ols/app/models/models.py
=> OLS-631: Use buildin dict in typing

ols/utils/auth_dependency.py
Added TODO for [OLS-648](https://issues.redhat.com//browse/OLS-648)
Fix for empty path check
- Related Issue #[OLS-648](https://issues.redhat.com//browse/OLS-648)
=> Added TODO for OLS-648 + one simple fix for empty path check

.gitignore, .woke.yaml, Makefile, ols/src/query_helpers/docs_summarizer.py, tests/scripts/utils.sh
Added .woke.yaml config file that aligns with https://inclusivenaming.org/ requirements
scanned the project with woke-cli and fixed the inclusive-naming incompatibilities
more info on woke-cli: https://github.com/get-woke/woke
- Closes #[OLS-451](https://issues.redhat.com//browse/OLS-451)
=> #OLS-451 added woke rules and fixed inclusive-naming incompatabilities

ols/app/metrics/metrics.py
Fix type for `AppConfig`, change introduced by https://github.com/openshift/lightspeed-service/pull/943
=> Fix type for AppConfig

ols/app/endpoints/authorized.py, ols/app/endpoints/feedback.py, ols/app/endpoints/ols.py
Explicit response metadata type specifications
(note the dict key type specifiers - it is not just `int` but `int | str` as expected by decorator type specification)
=> Explicit response metadata type specifications

ols/app/metrics/metrics.py, ols/src/cache/redis_cache.py, ols/src/rag_index/index_loader.py
Ignore false type errors or errors that can't be fixed due to missing type hints
=> Ignore false type errors or errors that can't be fixed due to missing type hints

Makefile, pyproject.toml
Better Bandit configuration based on our central `pyproject.toml` configuration file
=> Better Bandit configuration

ols/app/models/config.py, tests/config/valid_config_with_azure_openai.yaml, tests/config/valid_config_with_bam.yaml, tests/config/valid_config_with_watsonx.yaml, tests/unit/app/models/test_config.py, tests/unit/utils/test_config.py
- Azure OpenAI-specific config
- more unit tests
- updated model-loading code
=> OLS-641: Azure OpenAI-specific config

.snyk
=> Add snyk exclusions for test code

Containerfile, Makefile
Point to latest rag content (last changed through https://github.com/openshift/lightspeed-rag-content/pull/28)
=> Use latest rag content

.snyk
=> Add more snyk exclusions

pyproject.toml
TODO about bump-up langchain to version 0.2.0
- Related Issue #[OLS-657](https://issues.redhat.com//browse/OLS-657)
- Closes #
=> OLS-657: TODO about bump-up langchain to version 0.2.0

ols/src/llms/providers/azure_openai.py, tests/config/secret2.txt, tests/unit/llms/providers/test_azure_openai.py
Provider specific parameters take precedence over regular parameters
- Closes #
=> OLS-622: Provider specific parameters take precedence over regular parameters

tests/mock_classes/mock_retrievers.py
(Trivial) simplify mock retrievers class
=> (Trivial) simplify mock retrievers class

ols/src/llms/providers/bam.py, ols/src/llms/providers/openai.py, ols/src/llms/providers/watsonx.py, tests/unit/llms/providers/test_azure_openai.py, tests/unit/llms/providers/test_bam.py, tests/unit/llms/providers/test_openai.py, tests/unit/llms/providers/test_watsonx.py
- [OLS-622](https://issues.redhat.com//browse/OLS-622): provider-specific config for other providers (not just Azure OpenAI)
- New code paths covered by new unit test
- Closes #
=> OLS-622: provider-specific config for other providers (not just Azure OpenAI)

ols/app/endpoints/ols.py, ols/app/models/models.py, ols/src/query_helpers/docs_summarizer.py, ols/utils/token_handler.py, scripts/data_collection/user_data_aggregator.py, tests/e2e/test_api.py, tests/unit/app/endpoints/test_ols.py, tests/unit/query_helpers/test_docs_summarizer.py, tests/unit/utils/test_token_handler.py
Add rag context to transcript and google spreadsheet.
The last commit (_Add SummarizerResponse model as result of summarization_) is optional. It is bounded to https://github.com/openshift/lightspeed-service/pull/954
=> OLS-631: Rag in transcript

scripts/data_collection/__init__.py, scripts/data_collection/user_data_aggregator.py
[OLS-510](https://issues.redhat.com//browse/OLS-510): minor updates in code
- Related Issue #[OLS-510](https://issues.redhat.com//browse/OLS-510)
- Closes #
=> OLS-510: minor updates in code

scripts/data_collection/user_data_aggregator.py
Fix tar related vulnerability issues found by Snyk
- Related Issue #[OLS-661](https://issues.redhat.com//browse/OLS-661)
- Closes #
=> OLS-661: Fix tar related vulnerability issues found by Snyk

.gitignore
=> Ignore Snyk cache files

ols/src/llms/providers/bam.py, ols/src/llms/providers/watsonx.py, tests/unit/llms/providers/test_bam.py, tests/unit/llms/providers/test_watsonx.py
[OLS-622](https://issues.redhat.com//browse/OLS-622): check for credentials
- Closes #
=> OLS-622: check for credentials

ols/src/llms/providers/azure_openai.py, ols/src/llms/providers/openai.py
Fix - proper type conversion
- Closes #
=> OLS-641: fix - proper type conversion

ols/src/llms/providers/azure_openai.py, tests/unit/llms/providers/test_azure_openai.py
- Access token retrieval code
- Backed by unit tests
=> OLS-641: Access token retrieval code

ols/src/llms/providers/azure_openai.py, tests/unit/llms/providers/test_azure_openai.py
Now the new code has 100% code coverage as expected
- Closes #
=> OLS-641: Added missing unit test

pdm.lock, pyproject.toml
=> Bump-up Ruff to version 0.4.6

docs/openapi.json, ols/app/endpoints/health.py, ols/app/models/models.py, tests/e2e/test_api.py, tests/integration/test_liveness_readiness.py, tests/unit/app/endpoints/test_health.py, tests/unit/app/models/test_models.py
=> OLS-488: Refactor /liveness endpoint

.github/PULL_REQUEST_TEMPLATE.md
Update to PR template - new change type
=> Update to PR template - new change type

tests/test_data/question_answer_pair.json
More pre-defined QnAs for response evaluation. [OLS-491](https://issues.redhat.com//browse/OLS-491)
=> Add more QnAs for resp eval

scripts/questions_gen.py
=> OLS-505: Refactor script scripts/question_gen.py

scripts/questions_gen.py
Small fix for possible index array error
=> Small fix for possible index array error

ols/src/llms/providers/azure_openai.py
Added TODO for [OLS-679](https://issues.redhat.com//browse/OLS-679)
- Related Issue #[OLS-679](https://issues.redhat.com//browse/OLS-679)
- Closes #
=> Added TODO for OLS-679

ols/app/endpoints/ols.py, ols/app/models/config.py, ols/src/query_helpers/docs_summarizer.py, ols/utils/token_handler.py
Fixed [OLS-673](https://issues.redhat.com//browse/OLS-673)-related issues
- Related Issue #[OLS-673](https://issues.redhat.com//browse/OLS-673)
- Closes #
=> Fixed OLS-673-related issues

docs/openapi.json, ols/app/endpoints/health.py, ols/app/models/models.py, runner.py, tests/e2e/test_api.py, tests/integration/test_liveness_readiness.py, tests/integration/test_openapi.py, tests/unit/app/endpoints/test_health.py, tests/unit/app/models/test_models.py
Add index check to readiness probe.
=> OLS-488: Readiness probe - index loading check

ols/app/metrics/metrics.py
Code simplification
(it is also faster, but in this case we don't care)
=> Code simplification

ols/app/endpoints/ols.py, tests/unit/app/endpoints/test_ols.py
- Function to redact attachments
- Backed by unit tests
- Closes #
=> OLS-624: function to redact attachments

OWNERS
=> Add Xavier, remove Erik from approvers
