ols/user_data_collection/README.md

Fix diagram path in data collection docs

OLS-533: Fix diagram path in data collection docs

---

ols/user_data_collection/data_collector.py

Use existing variable for wait indication in collector

Use existing variable for wait indication in collector

---

pdm.lock
pyproject.toml

Bump-up Gradio - security fix

---

tests/config/cluster_install/ols_manifests.yaml

Add resource limits to E2E testing as defined by our operator.

Add resource limits to E2E testing

---

ols/user_data_collection/data_collector.py

OLS-692: OOM fix

---

ols/utils/redactor.py

Do not shadow Python builtin functions
-  Related Issue: #[OLS-624](https://issues.redhat.com//browse/OLS-624)

OLS-624: Do not shadow Python builtin functions

---

ols/app/endpoints/ols.py
ols/src/query_helpers/attachment_appender.py
tests/unit/query_helpers/test_attachment_appender.py

- Attachments appender to query from user.
- Backed by unit tests
- (not integrated yet, so no integration tests)
- Closes #

OLS-624: Attachments appender

---

pdm.lock
pyproject.toml

Bump-up Pydantic to version 2.7.3

Bump-up Pydantic to version 2.7.3

---

ols/app/endpoints/ols.py

Added TODO for [OLS-697](https://issues.redhat.com//browse/OLS-697)

OLS-624: Added TODO for OLS-697

---

ols/user_data_collection/data_collector.py

Trivial refactoring: don't use magic constant for HTTP status code

Trivial refactoring: don't use magic constant for HTTP status code

---

tests/config/valid_config.yaml
tests/config/valid_config_with_query_filter.yaml
tests/config/valid_config_without_query_filter.yaml
tests/unit/app/models/test_config.py

Remove deprecated config options for providers for specific ols subparts.
These are long gone.

Remove deprecated config options for providers for specific ols subpart

---

tests/unit/query_helpers/test_attachment_appender.py

More unit tests for attachment appender
- Closes #

OLS-624: more unit tests for attachment appender

---

tests/config/valid_config.yaml
tests/integration/test_ols.py
tests/unit/utils/test_config.py

Integration tests for attachment appender
- Closes #

OLS-624: Integration tests for attachment appender

---

tests/scripts/utils.sh

Fix junit setup template variable name reference

---

ols/constants.py

Event is valid attachment type

OLS-624: Event is valid attachment type

---

pyproject.toml
tests/mock_classes/mock_llm_chain.py

Enable new Ruff rules on CI

---

tests/integration/test_feedback.py

Integration test for checking handling improper conversation ID
(to check uncovered part of the model)

Integration test for checking handling improper conversation ID

---

tests/unit/app/models/test_config.py

Full error message match test
(trivial, but I got this exception, and was unable to find the exception message string in tests, so was fooled thinking we are not testing this situation)

Full error message match test

---

ols/app/models/config.py

Fix: added missing f-string in log message

Fix: added missing f-string

---

pyproject.toml

Fix project settings for Konflux

Fix project settings for Konflux

---

tests/integration/test_ols.py

Rest of integration tests for attachments
- Closes #

OLS-624: Rest of integration tests for attachments

---

examples/olsconfig.yaml

Update example olsconfig.yaml to better suit for local OLS run.

Update example olsconfig.yaml to better suit for local OLS run

---

tests/e2e/utils/response_evaluation.py
tests/test_data/question_answer_pair.json

Capability to include multiple answers as list in QnA json file. 
LLM may generate responses with some variations, but meaning can still be the same. 
To handle this:
- we can have flexible cut-off score (already present). It can handle minor variations.
- 2nd option is to add other variations as valid responses (this pr). We can compare model response to each of those answers and if one of the answers matches then we will mark evaluation as success. This will enable us to avoid very high cut-off.
Currently this is done for couple QnAs for openai/gpt. After running multiple times, 2nd viable viable answer was added.

multiple eval answers to handle llm randomness

---

ols/app/endpoints/health.py

Previous PR was merged before I addressed this comment.

Improve isinstance check in llm_is_ready function

---

tests/integration/test_ols.py

Integration test to test if token counter checker is in place

Integration test to test if token counter checker is in place

---

tests/integration/test_config.py

Integration test for missing config file

Integration test for missing config file

---

tests/integration/test_ols.py

[OLS-624](https://issues.redhat.com//browse/OLS-624): test for testing too long/large attachment handling

OLS-624: test for testing too long/large attachment handling

---

Makefile

Target to check package list completeness
This target will and should be run before step to build package list for Konflux. Because packages build is time consuming (several hours, possibly days) it is needed to be 100% sure that at least the list is 100% completed.
- Closes #

OLS-721: Target to check package list completeness

---

pyproject.toml

[OLS-721](https://issues.redhat.com//browse/OLS-721): specify build system

OLS-721: specify build system

---

docs/openapi.json
ols/app/endpoints/ols.py
ols/app/models/models.py

Kubernetes-compatible YAML in docs

Kubernetes-compatible YAML in docs

---

tests/unit/app/endpoints/test_ols.py
tests/unit/cache/test_postgres_cache.py

Removed leftovers (concatenated empty strings)

Removed leftovers (concatenated empty strings)

---

ols/app/endpoints/ols.py
tests/e2e/utils/response_evaluation.py
tests/integration/query_helpers/test_query_docs.py
tests/unit/app/endpoints/test_feedback.py

Removed assignment to variable before return

Removed assignment to variable before return

---

scripts/data_collection/user_data_aggregator.py

Fixed unit test parametrization

Fixed unit test parametrization

---

examples/olsconfig.yaml
ols/app/models/config.py
ols/constants.py
ols/src/llms/providers/provider.py
ols/src/query_helpers/docs_summarizer.py
ols/src/query_helpers/question_validator.py
ols/utils/token_handler.py
tests/config/valid_config.yaml
tests/integration/test_ols.py
tests/unit/app/models/test_config.py
tests/unit/llms/providers/test_watsonx.py
tests/unit/query_helpers/test_question_validator.py
tests/unit/utils/test_config.py
tests/unit/utils/test_token_handler.py

OLS-490: Sync Max response token for token handler with model parameter

---

ols/utils/token_handler.py

Idiomatic loop counter usage

---

tests/e2e/utils/decorators.py

Idiomatic re-raise without specifying the exception variable

Idiomatic re-raise without specifying the exception variable

---

ols/app/endpoints/ols.py
ols/utils/redactor.py
tests/e2e/test_api.py

OLS-642: Redacted content should never be displayed in logs

---

requirements.txt

Sync requirements.txt file with list of packages to prefetch
(the last update needed right now)
- Closes #

OLS-721: Sync requirements.txt file with list of packages to prefetch

---

Makefile
tests/e2e/conftest.py
tests/e2e/test_api.py
tests/e2e/utils/wait_for_ols.py
tests/scripts/utils.sh

OLS-581: Move the program logic to wait for OLS

---

tests/unit/app/endpoints/test_health.py

Added missing unit tests for readiness endpoint

Added missing unit tests for readiness endpoint

---

examples/olsconfig.yaml
ols/app/models/config.py
ols/src/query_helpers/docs_summarizer.py
tests/config/valid_config.yaml
tests/unit/app/models/test_config.py
tests/unit/utils/test_config.py

Add model_parameters config option.

OLS-490: Add model_parameters config option

---

scripts/generate_packages_to_prefetch.py

Ability to create list of build packages

OLS-721: ability to create list of build packages

---

pdm.lock
pyproject.toml

Bump-up Ruff to version 0.4.10

Bump-up Ruff to version 0.4.10

---

tests/integration/test_authorized.py

Autouse `_setup` fixture

---

tests/e2e/test_api.py

Simpler assertion in e2e test

---

tests/integration/test_liveness_readiness.py
tests/integration/test_metrics.py
tests/integration/test_openapi.py

Fixed rest of `_setup` fixtures usage

Fixed rest of _setup fixtures usage

---

ols/src/llms/providers/azure_openai.py
tests/unit/llms/providers/test_azure_openai.py

Add cache for azure AD token depending on expiration

OLS-679: Azure token refresh

---

Containerfile

Copy license file into container

OLS-702: Copy license file into container

---

pdm.lock
pyproject.toml

Bump-up Bandit

---

ols/user_data_collection/data_collector.py
ols/utils/auth_dependency.py
ols/utils/config.py
tests/unit/app/endpoints/test_ols.py
tests/unit/prompts/test_prompt_generator.py

Minor fixes for issues found in our sources

Minor fixes for issues found in our sources

---

ols/app/models/config.py
tests/unit/app/models/test_config.py
tests/unit/ui/test_gradio_ui.py
tests/unit/utils/test_logging.py

Refactor logging config

---

scripts/data_collection/user_data_aggregator.py

[OLS-756](https://issues.redhat.com//browse/OLS-756): attachments on Google sheet table
- Related Issue #[OLS-756](https://issues.redhat.com//browse/OLS-756)

OLS-756: attachments on Google sheet table

---

pdm.lock
pyproject.toml

Bump-up `types-requests` used by pytest

Bump-up types-requests used by pytest

---

tests/unit/cache/test_postgres_cache.py

Removed dead code from test

---

ols/user_data_collection/data_collector.py

Log JSONDecodeError in collector

Fix JSONDecodeError in collector

---

tests/unit/app/models/test_config.py

Don't test for 'any' exception, we should be more specific

Don't test for 'any' exception, we should be more specific

---

pdm.lock
pyproject.toml

Pandas is now direct dependency

Pandas is now direct dependency

---

tests/e2e/test_api.py

Disable collector script by default for other than collector tests. Hopefully, it will help with the e2e tests flakiness and pinpointing errors.

Disable collector script by default for other than collector tests

---

scripts/data_collection/user_data_aggregator.py

Fixed wrong type hint
(that is actually my code -> and my sorry)

Fixed wrong type hint

---

tests/e2e/test_api.py

Minor e2e tests improvements:
- removed unreachable code
- check for possibly unbound variable
- test the whole payload

Minor e2e tests improvements

---

tests/test_data/question_answer_pair.json

Update ground-truth answer. [OLS-431](https://issues.redhat.com//browse/OLS-431)

Update ground-truth answer

---

tests/test_data/question_answer_pair.json

Add recent user query to the question pool (Few queries are similar to existing query but with minor variation)

OLS-431: add new query to question pool

---

ols/app/endpoints/ols.py
tests/e2e/test_api.py
tests/unit/app/endpoints/test_ols.py

Add attachments to transcript.

OLS-734: Add attachments to transcript

---

ols/app/main.py

[OLS-775](https://issues.redhat.com//browse/OLS-775): import GradiIO just in devel mode
- Related Issue #[OLS-775](https://issues.redhat.com//browse/OLS-775)

OLS-775: import GradiIO just in devel mode

---

tests/e2e/test_api.py

Remove duplicated tests for health endpoints. There are basically the same tests at the top (also with metrics).

Remove duplicated tests for health endpoints

---

ols/app/endpoints/ols.py

Improve note about query redaction

Improve note about query redaction

---

tests/e2e/test_api.py

e2e: Bit more precise attachment check

e2e: Bit more precise attachment check

---

ols/app/endpoints/ols.py
ols/src/llms/llm_loader.py
ols/src/llms/providers/openai.py

Removed now-unused type check disable flags

Removed now-unused type check disable flags

---

ols/constants.py
pyproject.toml
runner.py

- No global skips for Bandit security checks
- Explicit skips in the code on few places only

No global skips for Bandit security checks

---

tests/e2e/conftest.py
tests/unit/app/models/test_config.py

(Trivial) Simpler logging config init
(Trivial) Simpler import

Simpler logging config init

---

tests/e2e/test_api.py
tests/e2e/utils/client.py
tests/e2e/utils/response.py

Refactor: client-utils and response-utils

Refactor: client-utils and response-utils

---

.snyk
pdm.lock
pyproject.toml
scripts/evaluation/README.md
scripts/evaluation/__init__.py
scripts/evaluation/driver.py
scripts/evaluation/response_evaluation.py
tests/e2e/conftest.py
tests/e2e/test_api.py
tests/e2e/utils/constants.py

Make evaluation a standalone script.
Use f1 score for evaluation.
Ability to use additional QnA from a parquet file.

OLS-409: Evaluation - standalone script & f1 score

---

tests/config/key
tests/config/password
tests/unit/app/models/test_config.py

`TLSConfig` loading unit tests

TLSConfig loading unit tests

---

tests/unit/app/models/test_models.py

Added unit test to check if ReferencedDocuments can be deserialized from string containing JSON

Added unit test to check if ReferencedDocuments can be deserialized from string containing JSON

---

tests/scripts/test-e2e-cluster.sh

Switch to azure gpt35-16k for ci e2e

Switch to azure gpt35-16k for ci e2e

---

ols/src/llms/providers/provider.py
ols/src/llms/providers/watsonx.py
pdm.lock
pyproject.toml
tests/unit/llms/providers/test_watsonx.py

Migrate to Watsonx AI
- Related Issue #[OLS-809](https://issues.redhat.com//browse/OLS-809)

OLS-809: Migrate to Watsonx AI

---

README.md

Info about Azure OpenAI alternative creds. settings
- Related Issue #[OLS-547](https://issues.redhat.com//browse/OLS-547)

OLS-547: Info about Azure OpenAI alternative creds. settings

---

pdm.lock
pyproject.toml
scripts/evaluation/driver.py
tests/e2e/utils/client.py
tests/e2e/utils/cluster.py

OLS-804: Prepare for new Ruff version

---

ols/utils/config.py

Simpler and more modern superclass constructor call

Simpler and more modern superclass constructor call

---

scripts/generate_packages_to_prefetch.py

Fix build script
- Related Issue #[OLS-832](https://issues.redhat.com//browse/OLS-832)

OLS-832: Fix build script

---

Containerfile

Update labels for EC
Should fix:
```
{
"msg": "The \"com.redhat.component\" label should not be inherited from the parent image",
"metadata": {
"code": "labels.disallowed_inherited_labels",
"collections": [
"redhat"
],
"description": "Check that certain labels on the image have different values than the labels from the parent image. If the label is inherited from the parent image but not redefined for the image, it will contain an incorrect value for the image. Use the rule data `disallowed_inherited_labels` key to set the list of labels to check, or the `fbc_disallowed_inherited_labels` key for fbc images. To exclude this rule add \"labels.disallowed_inherited_labels:com.redhat.component\" to the `exclude` section of the policy configuration.",
"solution": "Update the image build process …
```

OLS-821: Update labels for EC

---

scripts/data_collection/README.md
scripts/data_collection/print_acls.py

Script to print bucket ACLs
(we need to have tooling that allow us to display and use these information)

OLS-598: Script to print bucket ACLs

---

scripts/evaluation/response_evaluation.py

- Minor refactoring
- Increased LLM call retry count (it was unstable on Friday, so 3 attemts was not much)

Minor refactoring + increase LLM call retry count

---

scripts/data_collection/README.md
scripts/data_collection/print_ownership_controls.py

Print bucket ownership controls
(IIRC the last tool we need ATM)

OLS-598: Print bucket ownership controls

---

ols/app/models/config.py
ols/utils/auth_dependency.py
tests/unit/app/models/test_config.py
tests/unit/utils/test_config.py

OLS-648: Fix DevConfig types

---

ols/app/models/config.py

Fixed return value type

---

ols/app/models/models.py

Unfortunately return type of validator is of `Self` type, so being more "precise" (would be nice) does not work correctly there.

Fixed validator return type

---

tests/e2e/test_api.py

Repeat unstable e2e test

---

tests/config/cluster_install/ols_configmap.yaml

Removed dev-config from e2e test config completely - to be 'compatile' with customers settings

Removed dev-config completely - to be 'compatible' with customers settings

---

pdm.lock
pyproject.toml

OLS-833: Gradio is dev dependency

---

.tekton/lightspeed-service-pull-request.yaml
.tekton/lightspeed-service-push.yaml

upgrade ecosystem-cert-preflight-checks due fixing EC issues
resolved conflicts from https://github.com/openshift/lightspeed-service/pull/1272

upgrade ecosystem-cert-preflight-checks due fixing EC issues

---

.tekton/lightspeed-service-pull-request.yaml
.tekton/lightspeed-service-push.yaml

Specify buildah-6gb version

---

pdm.lock
pyproject.toml
scripts/evaluation/driver.py
tests/e2e/utils/client.py
tests/e2e/utils/decorators.py

Bump-up Ruff to version 0.5.2
- Related Issue #[OLS-833](https://issues.redhat.com//browse/OLS-833)

OLS-833: Bump-up Ruff to version 0.5.2

---

ols/app/endpoints/feedback.py
ols/app/endpoints/ols.py
ols/utils/errors_parsing.py
tests/integration/test_ols.py
tests/unit/app/endpoints/test_ols.py

Better HTTPException error content.
- handling for llm errors
- error type in the message

OLS-774: Better HTTPException error content

---

pdm.lock
pyproject.toml
scripts/upload_artifact_s3.py

Adding function to upload artifacts to s3 so they can be send to report portal. This is related to [OLS-592](https://issues.redhat.com/browse/OLS-592)

Adding upload_artifact_s3

---

.tekton/lightspeed-service-pull-request.yaml
.tekton/lightspeed-service-push.yaml

Bump-up `task-source-build`:
```
"key": "oci://quay.io/konflux-ci/tekton-catalog/task-source-build:0.1",
"value": [
{
"effective_on": "2024-08-23T00:00:00Z",
"ref": "sha256:1cb3423593145e899b784000f6ae90e121763ce98c26f6fc049f5dee2310f805"
},
{
"effective_on": "2024-08-15T00:00:00Z",
"expires_on": "2024-08-23T00:00:00Z",
"ref": "sha256:9eee3cf280d33106ea5a0a25f48ca54478d4120594c0e1b5a7849d3566cef670"
},
{
"effective_on": "2024-08-10T00:00:00Z",
"expires_on": "2024-08-15T00:00:00Z",
"ref": "sha256:5e34db0e73dcb92495b918119818cd02e57d22dfa112fad45464e57547766478"
},
```

Bump-up task-source-build

---

Containerfile

Added vendor label
- Related Issue #[OLS-567](https://issues.redhat.com//browse/OLS-567)

OLS-567: Added vendor label

---

CONTRIBUTING.md

Added link to JUnit test framework

Added link to JUnit test framework

---

.tekton/lightspeed-service-pull-request.yaml
.tekton/lightspeed-service-push.yaml

Bump-up buildah-6g again

---

.tekton/lightspeed-service-pull-request.yaml
.tekton/lightspeed-service-push.yaml

Bump-up `task-git-clone` to latest available

Bump-up task-git-clone to latest available

---

.snyk

Update SNYK configuration

---

ols/app/metrics/metrics.py

Idiomatic iteration over dictionary keys

Idiomatic iteration over dictionary keys

---

pdm.lock
pyproject.toml

Bump-up `faiss-cpu` package to 1.8.0.post1

Bump-up faiss-cpu package to 1.8.0.post1

---

README.md

Info about RHELAI as OLS provider
- Related Issue #[OLS-772](https://issues.redhat.com//browse/OLS-772)

OLS-772: Info about RHELAI as OLS provider

---

pdm.lock
pyproject.toml

Bump-up Ruff tool to 0.5.4

---

ols/app/endpoints/ols.py

Ability to log processing durations
Used to create https://docs.google.com/spreadsheets/d/1MY8xaf9O8Ko9ZKef5V26bAMWW3FjXicZPxAnmmW8vGQ/edit?gid=2012502775#gid=2012502775

Ability to log processing durations

---

ols/app/main.py

Fixes [OLS-898](https://issues.redhat.com//browse/OLS-898) - NPE
- Related Issue #[OLS-898](https://issues.redhat.com//browse/OLS-898)

Fixes OLS-898 - NPE

---

pdm.lock
pyproject.toml

Added reportportal packages

---

Makefile

Fix Black issue on CI
- Related Issue #[OLS-899](https://issues.redhat.com//browse/OLS-899)

OLS-899: Fix Black issue on CI

---

pdm.lock
pyproject.toml

Bump-up Ruff to version 0.5.5

---

tests/unit/utils/test_errors_parsing.py

Added missing unit tests for error parsing module

Added missing unit tests for error parsing module

---

ols/src/rag_index/index_loader.py

Removed TODO for closed [OLS-380](https://issues.redhat.com//browse/OLS-380)

Removed TODO for closed OLS-380

---

tests/unit/app/models/test_config.py

Added missing unit test for TLS secrets

Added missing unit test for TLS secrets

---

tests/unit/app/endpoints/test_ols.py

Removed leftover from tests

---

tests/unit/llms/providers/test_watsonx.py

Added unit test for `project_id` existence checking

Added unit test for `project_id` existence checking

---

pdm.lock
pyproject.toml

Bump-up Ruff to version 0.5.6

---

scripts/upload_artifact_s3.py

Fix: unbound variable was used

Fix: unbound variable was used

---

pdm.lock
pyproject.toml

OLS-906: Package for benchmarking

---

tests/unit/utils/test_errors_parsing.py

Unit tests for multiple exception states

Unit tests for multiple exception states

---

tests/e2e/test_api.py

Fix issue [OLS-909](https://issues.redhat.com//browse/OLS-909) - symbols must be bound
- Related Issue #[OLS-909](https://issues.redhat.com//browse/OLS-909)

Fix issue OLS-909 - symbols must be bound

---

README.md

Info about RHOAI
- Related Issue #[OLS-772](https://issues.redhat.com//browse/OLS-772)

OLS-772: Info about RHOAI

---

ols/src/prompts/prompts.py

Update the latest OCP version in the prompt to 4.16
- Closes #

Update the latest OCP version in the prompt to 4.16

---

docs/openapi.json
ols/app/main.py

Updated service version

---

CONTRIBUTING.md

OLS-906: Benchmarks: documentation

---

tests/e2e/conftest.py
tests/scripts/test-e2e-cluster.sh

Disable BAM e2e temporarily

---

pdm.lock
pyproject.toml

CVE fix in NLTK library
- Related Issue #[OLS-818](https://issues.redhat.com//browse/OLS-818)

OLS-818: CVE fix in NLTK library

---

tests/benchmarks/test_question_validator.py

More benchmarks for QuestionValidator

OLS-906: More benchmarks for QuestionValidator

---

pdm.lock
pyproject.toml

Fix [OLS-921](https://issues.redhat.com//browse/OLS-921): security issue
- Related Issue #[OLS-921](https://issues.redhat.com//browse/OLS-921)

Fix OLS-921: security issue

---

tests/benchmarks/test_question_validator.py
tests/benchmarks/test_token_handler.py

Benchmarks for token handling routines

OLS-906: Benchmarks for token handling routines

---

README.md

Token truncation algorithm in doc

Token truncation algorithm in doc

---

tests/e2e/conftest.py

Changing azure model identifier.

eval: change azure model identifier

---

tests/benchmarks/test_config_loader.py

OLS-906: Config loader benchmarks

---

docs/openapi.json
ols/app/main.py
pyproject.toml

OLS 0.1.2 version update
- Closes #

OLS 0.1.2 version update

---

README.md

Added architecture diagram into documentation

Added architecture diagram into documentation

---

ols/constants.py
scripts/questions_gen.py
tests/integration/test_ols.py
tests/unit/app/models/test_config.py

Remove model that was removed from BAM
- Related Issue #[OLS-928](https://issues.redhat.com//browse/OLS-928)

OLS-928: remove model that was removed from BAM

---

tests/benchmarks/test_prompt_generator.py

Benchmarks for PromptGenerator

OLS-906: Benchmarks for PromptGenerator

---

.tekton/lightspeed-service-push.yaml

[](konflux: avoid nudging yaml files in lightspeed-catalog.* directories)
- Closes #

konflux: avoid nudging yaml files in lightspeed-catalog.* directories

---

tests/benchmarks/test_docs_summarizer.py

Benchmark for `DocsSummarizer` class

OLS-906: Benchmark for DocsSummarizer

---

pdm.lock
pyproject.toml

Bump torch to 2.3.1+cpu
- [x ] Bump-up dependent library

Bump torch to 2.3.1+cpu

---

pdm.lock
pyproject.toml

[OLS-934](https://issues.redhat.com//browse/OLS-934): temporary fix CI
- Related Issue #[OLS-934](https://issues.redhat.com//browse/OLS-934)

OLS-934: temporary fix CI

---

README.md

Info: BAM is not officially supported

Info: BAM is not officially supported

---

scripts/evaluation/response_evaluation.py

Make e2e more stable

---

tests/benchmarks/test_attachment_appender.py

Benchmark for attachment appender

OLS-906: Benchmark for attachment appender

---

README.md

Documentation: LLM providers parameters

---

tests/benchmarks/test_attachment_appender.py

More attachment appender benchmarks
- Closes #

OLS-906: More attachment appender benchmarks

---

README.md

Restructured documentation + added Table of Content

Restructured documentation + added Table of Content

---

CONTRIBUTING.md

- Added Table of Content
- Restructured contributing guide

ToC and restructured contributing guide

---

README.md

(Trivial) change grammar

---

docs/openapi.json
ols/app/main.py
pyproject.toml

OLS 0.1.3 version update
- Closes #

OLS 0.1.3 version update

---

tests/benchmarks/test_redactor.py

OLS-906: Benchmarks for `Redactor`

---

constraints.txt

Removed `constraints.txt`, not needed anymore

Removed `constraints.txt`, not needed anymore

---

.tekton/lightspeed-service-push.yaml

revert the new nudge filter, it seems not to be working as expected
- Closes #

Revert Nudge filter 

---

Makefile

Use default Mypy installation

---

tests/benchmarks/test_config_loader.py

More benchmarks for loading config code

OLS-906: More benchmarks for loading config code

---

tests/benchmarks/test_prompt_generator.py

More benchmarks for prompt generator

OLS-906: More benchmarks for prompt generator

---

tests/benchmarks/test_errors_parsing.py

Benchmarks for errors parsing functionality

OLS-906: Benchmarks for errors parsing functionality

---

ols/src/query_helpers/docs_summarizer.py

Enable langchain verbose to see the prompt, when log level is debug.

enable langchain verbose in debug mode

---

docs/openapi.json
ols/app/main.py
pyproject.toml

OLS 0.1.4 version update
- Closes #

OLS 0.1.4 version update

---

scripts/evaluation/response_evaluation.py

Note about fixes made in model evaluation script
- Related Issue #[OLS-858](https://issues.redhat.com//browse/OLS-858)

OLS-858: Note about fixes made in model evaluation script

---

.tekton/lightspeed-service-push.yaml

more simple konflux nudge patterns, update files in  config/ and bundle/ directories only.
- Closes #

konflux: nudge files in config/ and bundle/ directories only

---

ols/app/models/config.py
ols/user_data_collection/README.md
ols/user_data_collection/data_collector.py
ols/utils/config.py
tests/e2e/test_api.py
tests/e2e/utils/cluster.py
tests/scripts/must_gather.py
tests/unit/app/models/test_config.py
tests/unit/user_data_collection/test_data_collector.py

Make data collector configurable via olsconfig.yaml.
Tests should work after - https://github.com/openshift/lightspeed-operator/pull/324

OLS-514: Make data collector configurable via olsconfig.yaml

---

scripts/data_collection/download_ols_archive.py

Use more concrete exception

---

Makefile

Revert Mypy update

---

scripts/data_collection/update_google_sheet.py

Refactoring: don't interpolate in log function (deprecated technique)

Refactoring: don't interpolate in log function (deprecated technique)

---

ols/user_data_collection/data_collector.py

Refactoring: better code structure

Refactoring: better code structure

---

README.md
examples/olsconfig.yaml

Info about RHOAI + added it into example configuration
- Related Issue #[OLS-974](https://issues.redhat.com//browse/OLS-974)

OLS-974: Info about RHOAI + added it into example configuration

---

pdm.lock
pyproject.toml

Bump-up Ruff to 0.6.2

---

scripts/data_collection/list_objects_in_ceph.py

Refactored: `list_objects_in_ceph.py` helper script

Refactored: `list_objects_in_ceph.py` helper script

---

scripts/data_collection/user_data_aggregator.py

Refactoring: don't raise general exception

Refactoring: don't raise general exception

---

tests/integration/test_ols.py

Refactor `test-ols` integration tests:
- unused parameter names
- multiple imports are not needed

Refactor `test-ols` integration tests

---

ols/app/endpoints/ols.py
ols/app/models/config.py
ols/src/llms/llm_loader.py
tests/e2e/test_api.py
tests/integration/test_ols.py
tests/unit/app/endpoints/test_ols.py
tests/unit/app/models/test_config.py

- Disable query val by default.
- Necessary modification to test cases
- Validate provider/model sent through request payload separately to have proper error message.

OLS-941: disable query val by default

---

.tekton/lightspeed-service-pull-request.yaml
.tekton/lightspeed-service-push.yaml

This resolves the Enterprise Contract violation:
```json
{
"msg": "No source image references found",
"metadata": {
"code": "source_image.exists",
"collections": [
"redhat"
],
"description": "Verify the source container image exists. To exclude this rule add \"source_image.exists\" to the `exclude` section of the policy configuration.",
"effective_on": "2024-06-05T00:00:00Z",
"title": "Exists"
}
}
```
When we resolved the hermetic build issues, we can add 2 more parameters:
```yaml
- name: prefetch-input
value: '{"type": "pip", "path": "."}'
- name: hermetic
value: "true"
```
- Related Issue # [OLS-889](https://issues.redhat.com//browse/OLS-889)
- Closes #
- How were the fix/results from this change verified? …

konflux: activate build-source-image

---

tests/benchmarks/test_errors_parsing.py
tests/benchmarks/test_token_handler.py

Fixed benchmarks: use passed parameters

Fixed benchmarks: use passed parameters

---

pdm.lock
pyproject.toml

 OLS-757: Use torch with GPU support

---

.tekton/lightspeed-service-push.yaml

we try full text match this time. 
- Closes #

konflux: nudge update

---

.tekton/lightspeed-service-pull-request.yaml
.tekton/lightspeed-service-push.yaml

Increase workspace size to 10GiB

OLS-757: Increase workspace size to 10GiB

---

.tekton/lightspeed-service-pull-request.yaml
.tekton/lightspeed-service-push.yaml

OLS-757: Volume size: 2GB

---

.tekton/lightspeed-service-pull-request.yaml
.tekton/lightspeed-service-push.yaml

Volume size: 5GB

---

.tekton/lightspeed-service-pull-request.yaml
.tekton/lightspeed-service-push.yaml

Volume size limit to 7Gi

---

.tekton/lightspeed-service-pull-request.yaml
.tekton/lightspeed-service-push.yaml

OSL-757: Volume size set to 10GB

---

.tekton/lightspeed-service-pull-request.yaml
.tekton/lightspeed-service-push.yaml

Increase volume for prefetch build

OLS-757: Increase volume for prefetch build

---

requirements.txt

Updated list of packages for Cachi2

OLS-757: Updated list of packages for Cachi2

---

scripts/evaluation/eval_data/question_answer_pair.json

increase consistency cut-off for openai due to randomness.. (eval4)
[reference](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_lightspeed-service/1516/pull-ci-openshift-lightspeed-service-main-e2e-ols-cluster-4-15/1830542504726892544)

eval: increase consistency cut-off for openai

---

tests/unit/app/models/test_config.py

Fixed comments for RHOAI VLLM-specific unit tests

Fixed comments for RHOAI VLLM-specific unit tests

---

README.md
examples/olsconfig.yaml

[OLS-985](https://issues.redhat.com//browse/OLS-985): Info about RHELAI + added it into example configuration
- Related Issue #[OLS-985](https://issues.redhat.com//browse/OLS-985)

OLS-985: Info about RHELAI + added it into example configuration

---

README.md

Updated doc about RHELAI
- Related Issue #[OLS-985](https://issues.redhat.com//browse/OLS-985)

OLS-985: Updated doc about RHELAI

---

ols/src/llms/providers/provider.py
ols/src/llms/providers/rhelai_vllm.py
tests/unit/llms/providers/test_providers.py
tests/unit/llms/providers/test_rhelai_vllm.py

RHELAI VLLM as provider for OLS
- Related Issue #[OLS-985](https://issues.redhat.com//browse/OLS-985)

OLS-985: RHELAI VLLM as provider for OLS

---

tests/config/config_for_integration_tests.yaml

Updated config file for integration tests
- Related Issue #[OLS-985](https://issues.redhat.com//browse/OLS-985)

OLS-985: Updated config file for integration tests

---

pdm.lock
pyproject.toml

Bump-up fastapi

---

README.md

Fixed README.md rendering

---

.tekton/lightspeed-service-pull-request.yaml
.tekton/lightspeed-service-push.yaml

Enable prefetch build for the service

OLS-757: Enable prefetch build for the service

---

README.md

readme - typo fix

---

ols/app/endpoints/health.py

Follow happy path: removed else blocks that are not needed

Refactoring: follow happy path: removed else blocks that are not needed

---

ols/utils/errors_parsing.py

Use class pattern in pattern matching

Refactor: use class pattern in pattern matching

---

examples/olsconfig-local-ollama.yaml

Add olsconfig sample for local ollama server
- Related Issue # n/a
- Closes # n/a
- Please provide detailed steps to perform tests related to this code change. n/a
- How were the fix/results from this change verified? Please provide relevant screenshots or results. n/a

Add olsconfig sample for local ollama server

---

tests/e2e/utils/postgres.py

Refactoring: remove global variable reference

Refactoring: remove global variable reference

---

ols/utils/token_handler.py

Refactoring: lazy docstring format in token handler code

Refactoring: lazy docstring format in token handler code

---

.tekton/lightspeed-service-pull-request.yaml
.tekton/lightspeed-service-push.yaml

Bump-up prefetch dependencies task

Bump-up prefetch dependencies task

---

README.md

Documentation: mention local ollama server

Documentation: mention local ollama server

---

scripts/evaluation/driver.py
scripts/evaluation/response_evaluation.py
tests/e2e/conftest.py
tests/e2e/test_api.py

- Refactoring of eval script
- more modularisation to have single flow for different eval types.
- More parallelisation using pandas apply (with progress bar) instead of iterating over json.
- Easy to add new scores.
- Simplify score summary calculation.
- arg to control which plot/graph needs to be created.
- Modified e2e assert to get simplified error message

eval: eval script refactoring

---

tests/e2e/utils/decorators.py

Refactoring: use build-in standard function, not special method

Refactoring: use build-in standard function, not special method

---

.tekton/lightspeed-service-pull-request.yaml
.tekton/lightspeed-service-push.yaml

Bump-up buildah-8g
- [OLS-1031](https://issues.redhat.com//browse/OLS-1031)

OLS-1031: Bump-up buildah-8g

---

.tekton/lightspeed-service-pull-request.yaml
.tekton/lightspeed-service-push.yaml

Use buildah-10g
- Related Issue #[OLS-1031](https://issues.redhat.com//browse/OLS-1031)

OLS-1031: Use buildah-10g

---

pdm.lock
pyproject.toml

OLS-1032: Bump-up Torch to 2.4.1

---

ols/app/models/config.py
ols/constants.py
tests/config/valid_config_without_certificate_directory.yaml
tests/unit/app/models/test_config.py
tests/unit/utils/test_config.py

Certificates directory configuration option
- Related Issue #[OLS-1015](https://issues.redhat.com//browse/OLS-1015)

OLS-1015: Certificates directory configuration option

---

.tekton/lightspeed-service-pull-request.yaml
.tekton/lightspeed-service-push.yaml

Override limits for build-source-image task
- Related Issue #[OLS-1030](https://issues.redhat.com//browse/OLS-1030)

OLS-1030: Override limits for build-source-image task

---

pdm.lock
pyproject.toml

Fix vulnerability in `zipp` package
- Related Issue #[OLS-1044](https://issues.redhat.com//browse/OLS-1044)

OLS-1044: Fix vulnerability in zipp package

---

ols/__init__.py
runner.py

Don't import config on toplevel

Refactoring: don't import config on toplevel

---

pdm.lock
pyproject.toml

Fix CVE in scikit-learn package
- [x ] Bump-up dependent library
- Related Issue #[OLS-1052](https://issues.redhat.com//browse/OLS-1052)

OLS-1052: Fix CVE in scikit-learn package

---

tests/unit/utils/test_errors_parsing.py

Refactoring + fix: Proper status checks

---

ols/constants.py
runner.py
tests/unit/extra_certs/test_extra_certs.py
tests/unit/utils/test_errors_parsing.py

Create new certification store
- Related Issue #[OLS-1015](https://issues.redhat.com//browse/OLS-1015)

OLS-1015: Create new certification store

---

ols/utils/redactor.py

Lazy log formatting in redactor.py

Refactoring: lazy log formatting in redactor.py

---

ols/app/models/config.py
tests/unit/app/models/test_config.py
tests/unit/utils/test_config.py

Store certificate path
- Related Issue #[OLS-1015](https://issues.redhat.com//browse/OLS-1015)

OLS-1015: Store certificate path

---

pdm.lock
pyproject.toml

Bump-up langchain community to 0.2.16

OLS-1032: Bump-up langchain community to 0.2.16

---

scripts/upload_artifact_s3.py

Trivial refactor: constants in uppercase

Trivial refactor: constants in uppercase

---

pdm.lock
pyproject.toml
scripts/data_collection/user_data_aggregator.py

Use `with` for working with resource

Refactor: use `with` for working with resource

---

scripts/evaluation/README.md
scripts/evaluation/driver.py
scripts/evaluation/response_evaluation.py
scripts/evaluation/utils.py
tests/e2e/conftest.py

Ability run evaluation against vanilla model & just OLS parameters / OLS prompt / OLS RAG.
Config to control this flow.. Default is just `ols`

eval: options for just model/param/prompt/rag

---

ols/src/llms/providers/provider.py

Refactoring: removed letfover

---

ols/src/cache/postgres_cache.py

Better program logic in Postgres interface

Better program logic in Postgres interface

---

CONTRIBUTING.md

Info about package update and lockfile

Info about package update and lockfile

---

pdm.lock
pyproject.toml

OLS-1032: Bump-up Pydantic

---

scripts/evaluation/response_evaluation.py
scripts/evaluation/utils/__init__.py
scripts/evaluation/utils/constants.py
scripts/evaluation/utils/models.py
scripts/evaluation/utils/plot.py
scripts/evaluation/utils/rag.py
scripts/evaluation/utils/response.py
scripts/evaluation/utils/score.py
tests/e2e/test_api.py

Move different helper modules/constants to individual files.

eval: refactoring

---

docs/openapi.json
ols/app/main.py

update version to 0.1.6
- Closes #

OLS update version to 0.1.6

---

README.md

Info about local deployment

---

tests/e2e/utils/cluster.py

Placeholder instead of unused variable

Placeholder instead of unused variable

---

tests/e2e/utils/decorators.py

Trivial: specify `maxsplit` value

Trivial: specify `maxsplit` value

---

Makefile

- Related Issue #[OLS-1085](https://issues.redhat.com//browse/OLS-1085)
- Closes #

OLS-1085: Install PDM 2.18.1

---

README.md

Note about auth.

---

Containerfile

Install correct PDM version
- Related Issue #OLS-1085
- Closes #

OLS-1085: Install correct PDM version

---

README.md

Intro structure with providers info

OLS-86: Intro structure with providers info

---

README.md

Info how to get API key to LLM
- Closes #

OLS-86: Info how to get API key to LLM

---

README.md

OLS-86: Correct info about providers

---

README.md

Overall service architecture
- Related Issue #OLS-86

OLS-86: Overall service architecture

---

pdm.lock
pyproject.toml

Fixed issue [OLS-1082](https://issues.redhat.com//browse/OLS-1082)
- Related Issue #[OLS-1082](https://issues.redhat.com//browse/OLS-1082)

OLS-1082: Fixed issue OLS-1082

---

ols/src/cache/postgres_cache.py

Refactoring: better exception context

---

README.md

- Doc about cache
- Updated ToC

OLS-86: Doc about cache

---

tests/e2e/test_api.py

Wait longer for getting clusterversion
- Closes #

Wait longer for getting clusterversion

---

runner.py

Better import

---

tests/mock_classes/mock_k8s_api.py

Refactor: simpler program logic

Refactor: simpler program logic

---

scripts/generate_packages_to_prefetch.py

Command line args to process special packages

OLS-1001: Command line args to process special packages

---

README.md

OLS-86: Some grammar fixes

---

scripts/generate_packages_to_prefetch.py

Ability to specify work directory

OLS-1001: Ability to specify work directory

---

ols/app/metrics/metrics.py
tests/config/operator_install/olsconfig.crd.azure_openai.yaml
tests/e2e/pytest.ini
tests/e2e/test_api.py
tests/scripts/test-e2e-cluster.sh

OLS-992: Add Entra ID test

---

pdm.lock
pyproject.toml

Bump-up SQLAlchemy to fix prefetch build task

Bump-up SQLAlchemy to fix prefetch build task

---

scripts/generate_packages_to_prefetch.py

Cleanup and preparation for package filtering

OLS-1001: Cleanup and preparation for package filtering

---

README.md

OLS-86: Doc about additional tools

---

tests/e2e/test_api.py

OLS-1058 - Adding exception to operator installation for konflux

---

scripts/generate_packages_to_prefetch.py

Ability to filter packages for given platform

OLS-1001: Ability to filter packages for given platform

---

README.md

Added known issue into documentation

OLS-1001: Added known issue into documentation

---

ols/src/prompts/prompt_generator.py

(Trivial) more idiomatic if-else

(Trivial) more idiomatic if-else

---

ols/utils/auth_dependency.py

Better exception handling in auth. module

Better exception handling in auth. module

---

ols/src/llms/providers/azure_openai.py
ols/src/llms/providers/bam.py
ols/src/llms/providers/fake_provider.py
ols/src/llms/providers/openai.py
ols/src/llms/providers/rhelai_vllm.py
ols/src/llms/providers/rhoai_vllm.py
ols/src/llms/providers/watsonx.py
scripts/evaluation/utils/models.py

Fixed pydocstyle
- Related Issue #[OLS-1105](https://issues.redhat.com//browse/OLS-1105)

OLS-1105: Fixed pydocstyle

---

scripts/evaluation/eval_data/question_answer_pair.json

Updating QnA dataset to handle changes to 4.17 doc.
[Reference](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/57074/rehearse-57074-periodic-ci-openshift-lightspeed-service-main-e2e-ols-cluster-4-17/1841716379934265344)

eval: changes for 4.17

---

docs/openapi.json
ols/app/main.py

OLS version 0.1.7
- Closes # https://issues.redhat.com/browse/OLS-1083

OLS version 0.1.7

---

tests/integration/test_project_version_consistency.py

Integration test to ensure project version consistency

Integration test to ensure project version consistency

---

.tekton/lightspeed-service-push.yaml
ols/src/prompts/prompts.py

OLS-1072: Include OCP 4.17

---

ols/src/query_helpers/docs_summarizer.py

Removed unused `**kwargs` argument

Removed unused **kwargs argument

---

ols/user_data_collection/data_collector.py
tests/unit/user_data_collection/test_data_collector.py

Catch and log when there is something wrong in get of refresh token.

Handle decode error

---

ols/src/rag_index/index_loader.py

Removed unused `global` declaration

Removed unused `global` declaration

---

tests/e2e/test_api.py
tests/e2e/utils/retry.py

E2e refactoring: retry mechanisms

E2e refactoring: retry mechanisms

---

ols/app/endpoints/ols.py

Refactored OLS handler main file

Refactored OLS handler main file

---

pdm.lock
pyproject.toml

Bump-up Black
- Related Issue #[OLS-1144](https://issues.redhat.com//browse/OLS-1144)

OLS-1144: Bump-up Black

---

tests/e2e/test_api.py
tests/e2e/utils/cluster.py

for multiple test runs
- Closes #

OLS-1058 - Addind check for existing users, config and secrets

---

tests/config/operator_install/olsconfig.crd.rhoai_vllm.yaml

RHOAI VLLM for e2e tests
- Related Issue #[OLS-988](https://issues.redhat.com//browse/OLS-988)

OLS-988: RHOAI VLLM for e2e tests

---

ols/app/metrics/token_counter.py

Marked false alarm as disabled

Marked false alarm as disabled

---

tests/scripts/test-e2e-cluster.sh

Smoketests against RHOAI VLLM
- Related Issue #[OLS-988](https://issues.redhat.com//browse/OLS-988)

OLS-988: Smoketests against RHOAI VLLM

---

pdm.lock
pyproject.toml

Proper `starlette` package with locked version in project file

Proper starlette package with locked version in project file

---

tests/e2e/test_api.py
tests/e2e/utils/constants.py
tests/e2e/utils/ols_installer.py

Independent OLS installer

---

scripts/generate_packages_to_prefetch.py

Refactoring prefetch packages script - no `elif` needed

Refactoring prefetch packages script - no `elif` needed

---

pdm.lock
pyproject.toml

Bump-up Ruff

---

ols/src/ui/gradio_ui.py

- Fix gradio UI initialization
- Logging w/o f-strings
- Logging history lentgth

Fix gradio UI initialization

---

tests/e2e/test_api.py
tests/integration/test_authorized.py
tests/integration/test_feedback.py
tests/integration/test_liveness_readiness.py
tests/integration/test_metrics.py
tests/integration/test_ols.py
tests/integration/test_openapi.py
tests/integration/test_redis.py
tests/mock_classes/mock_llm_chain.py

Various fixes in tests

---

README.md

Doc about system prompt
- Related Issue #[OLS-1121](https://issues.redhat.com//browse/OLS-1121)

OLS-1121: Doc about system prompt

---

scripts/sync_repos.py

Script to sync upstream repository with downstream one
- Related Issue #[OLS-1120](https://issues.redhat.com//browse/OLS-1120)

OLS-1120: Script to sync upstream repository with downstream one

---

pdm.lock
pyproject.toml

Bump-up starlette - fix DoS
- Related Issue #[OLS-1160](https://issues.redhat.com//browse/OLS-1160)

OLS-1160: Bump-up starlette - fix DoS

---

ols/utils/tls.py

TLS-related structures and constants

OLS-1099: TLS-related structures and constants

---

ols/src/llms/providers/provider.py

Allow `http_client` parameter for RHOAI and RHELAI

Allow http_client parameter for RHOAI and RHELAI

---

ols/app/endpoints/health.py
ols/app/models/config.py
ols/src/llms/llm_loader.py
ols/src/prompts/prompts.py

Fixed minor issues found by linters

Fixed minor issues found by linters

---

OWNERS

Add Josh as an approver
- Closes #

Add Josh as an approver

---

ols/app/models/config.py
ols/utils/tls.py
tests/unit/app/models/test_config.py

- TLS security profile in config
- TLS values validation
- New code 100% covered by unit tests

OLS-1099: TLS security profile in `ols` config

---

docs/openapi.json
ols/app/endpoints/health.py
ols/app/models/models.py
tests/integration/test_liveness_readiness.py
tests/integration/test_metrics.py
tests/unit/app/endpoints/test_health.py

Change readiness status code in case of check issue

OLS-1155: Change readiness status code in case of check issue

---

ols/user_data_collection/data_collector.py

Log status code and response text

Log status code and response text

---

pdm.lock
pyproject.toml

sentence-transformers==3.0.1 to sentence-transformers==3.1.1
[OLS-1142](https://issues.redhat.com//browse/OLS-1142)

Bump up sentence-transformers

---

ols/app/models/config.py
tests/integration/test_authorized.py
tests/integration/test_feedback.py
tests/integration/test_liveness_readiness.py
tests/integration/test_metrics.py
tests/integration/test_ols.py
tests/integration/test_openapi.py
tests/integration/test_project_version_consistency.py

Better import (make linters happy)

Better import (make linters happy)

---

Makefile

Disable Mypy temporarily

---

Makefile
pyproject.toml

Bump-up Mypy to latest version

Bump-up Mypy to latest version

---

README.md
examples/olsconfig.yaml

Doc about TLS security profile

Doc about TLS security profile

---

examples/olsconfig.yaml
ols/app/models/config.py
tests/config/config_for_integration_tests.yaml
tests/unit/app/models/test_config.py
tests/unit/utils/test_config.py

Provider specific tls profile configuration

OLS-1099: Provider specific tls profile configuration

---

tests/e2e/utils/cluster.py
tests/e2e/utils/metrics.py
tests/e2e/utils/ols_installer.py

Fixed issues found by linters

---

pdm.lock
pyproject.toml

Bump-up Ruff to version 0.7.0

---

ols/app/endpoints/health.py

Simpler logic

---

ols/src/llms/providers/provider.py

No string interpolation for logger in `provider.py`

No string interpolation for logger in provider.py

---

pyproject.toml

Bump-up Mypy to 1.13.0

---

tests/unit/utils/test_auth_dependency.py

Fix: auth-dependency is test-global variable

Fix: auth-dependency is test-global variable

---

CONTRIBUTING.md

Info about running test

---

CONTRIBUTING.md

Updating info about _Bandit_

---

README.md

Info about downloading RAG

---

tests/config/operator_install/imagedigestmirrorset.yaml

Updated the mirror to tech-preview for the Test Config
- [ x] Bug fix
- Closes #

updated the mirror to tech-preview

---

scripts/evaluation/response_evaluation.py

Fix errors during data concatenation. (Missed to push local changes earlier)

eval: fix errors while data concatenation

---

ols/src/prompts/prompts.py

Removing note for the prompt (not applicable anymore)

chore: remove prompt note - not applicable anymore

---

scripts/build-container.sh

Proper image version

---

docs/config.puml
examples/olsconfig-local-ollama.yaml
examples/olsconfig.yaml
examples/openshift-lightspeed-tls.yaml
ols/app/models/config.py
runner.py
tests/benchmarks/test_config_loader.py
tests/config/valid_config.yaml
tests/unit/utils/test_config.py

Number of workers to scale up

---

pdm.lock

Update lockfile version

---

ols/utils/tls.py
tests/unit/utils/test_tls.py

TLS security profile handling support functions + unit tests (100% new code coverage)

OLS-1099: TLS security profile handling support functions + tests

---

pdm.lock
pyproject.toml

Bump-up huggingface-hub package to fix vulnerability

Bump-up huggingface-hub package to fix vulnerability

---

ols/constants.py
runner.py

Explicitly specify SSL version and supported ciphers

OLS-1099: Explicitly specify SSL version and supported ciphers

---

ols/src/llms/providers/provider.py

[OLS-1106](https://issues.redhat.com//browse/OLS-1106): TLS security profile for outgoing LLM calls
- Related Issue #[OLS-1106](https://issues.redhat.com//browse/OLS-1106)

OLS-1106: TLS security profile for outgoing LLM calls

---

README.md

[OLS-1106](https://issues.redhat.com//browse/OLS-1106): Updated README.md accordingly
- Related Issue #[OLS-1106](https://issues.redhat.com//browse/OLS-1106)

OLS-1106: Updated README.md accordingly

---

runner.py
tests/unit/utils/test_errors_parsing.py

[OLS-1099](https://issues.redhat.com//browse/OLS-1099): Fully configurable TLS security profile for incoming connections
(documented already)

OLS-1099: Fully configurable TLS security profile for incoming connections

---

pdm.lock
pyproject.toml

OLS-1174: Bump-up PDM tool to 2.19.3

---

scripts/evaluation/eval_data/question_answer_pair.json

Adjusting eval QnA.
[Reference](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_lightspeed-service/1846/pull-ci-openshift-lightspeed-service-main-e2e-ols-cluster-4-15/1853754501530390528)

eval: adjust eval2 for azure

---

scripts/evaluation/utils/constants.py
scripts/evaluation/utils/response.py

Changes for ollama/local inference.
Include additional in-scope models

eval: changes for ollama/local inference

---

scripts/sync_repos.py

Explicit `check` parameter for `subprocess.run`

Explicit `check` parameter for `subprocess.run`

---

pdm.lock
pyproject.toml

Bump-up PDM tool to version 2.20.0.post1

OLS-1174: Bump-up PDM tool to version 2.20.0.post1

---

examples/olsconfig.yaml
ols/app/models/config.py
ols/constants.py
tests/unit/app/models/test_config.py

Auth module configuration
- Related Issue #[OLS-1204](https://issues.redhat.com//browse/OLS-1204)

OLS-1204: Auth module configuration

---

README.md

Documentation update - number of workers configuration option

(Sync with upstream)(Doc) number of workers

---

requirements.txt

OLS-1174: Update list of packages for Konflux build

---

examples/olsconfig.yaml

Updated configuration example file: info about validation methods

Updated configuration example file: info about validation methods

---

ols/app/endpoints/authorized.py
ols/app/endpoints/feedback.py
ols/app/endpoints/ols.py
ols/app/metrics/metrics.py
ols/src/auth/auth.py
ols/src/auth/auth_dependency_interface.py
ols/src/auth/k8s.py
ols/src/auth/noop.py
tests/unit/app/endpoints/test_authorized.py

- fully-configuratble authentication dependency
- Related Issue #[OLS-1204](https://issues.redhat.com//browse/OLS-1204)

OLS-1204: fully-configuratble authentication dependency

---

ols/utils/tls.py

(Minor) Logger in TLS module

---

requirements.txt

Azure identity as Konflux package
- Related Issue #[OLS-1074](https://issues.redhat.com//browse/OLS-1074)

OLS-1074: Azure identity as Konflux package

---

ols/src/auth/auth.py
ols/src/auth/auth_dependency_interface.py
tests/unit/auth/test_auth.py
tests/unit/auth/test_noop_auth_dependency.py

OLS-1099: Check auth dependency config

---

Containerfile

Updated RAG SHA-256

---

ols/utils/ssl.py
runner.py
tests/unit/utils/test_ssl.py

Refactor `runner.py` - SSL-related utility functions
- Related Issue #[OLS-1229](https://issues.redhat.com//browse/OLS-1229)

OLS-1229: Refactor runner.py - SSL-related utility functions

---

ols/src/query_helpers/docs_summarizer.py

Refactored: deleted unused code
- Related Issue #[OLS-1233](https://issues.redhat.com//browse/OLS-1233)

OLS-1233: Refactored: deleted unused code

---

pyproject.toml

PDM command to generate `requirements.txt`

PDM command to generate requirements.txt

---

pdm.lock
pyproject.toml
requirements.txt

[OLS-1218](https://issues.redhat.com//browse/OLS-1218): HTTPX client in `requirements.txt`
- Related Issue #[OLS-1218](https://issues.redhat.com//browse/OLS-1218)

OLS-1218: HTTPX client in requirements.txt

---

tests/e2e/utils/ols_installer.py

OLS-1110 - Commenting out update-ols-config

---

examples/olsconfig.yaml
ols/app/main.py
ols/app/models/config.py
ols/src/auth/k8s.py
tests/integration/test_authorized.py
tests/integration/test_metrics.py
tests/unit/app/models/test_config.py

[Upstream] Optionally to suppress Prometheus metrics and auth checks warnings in log

[Upstream] Optionally to suppress Prometheus metrics and auth checks warnings in log

---

tests/integration/test_authorized.py
tests/integration/test_metrics.py

Fixed integration tests (two previous merges conflicted in package names)

Fixed integration tests

---

ols/utils/environments.py
runner.py
tests/unit/utils/test_environments.py

[OLS-1229](https://issues.redhat.com//browse/OLS-1229): HuggingFace environment settings
New unit tests created
- Related Issue #[OLS-1229](https://issues.redhat.com//browse/OLS-1229)

OLS-1229: HuggingFace environment settings

---

ols/app/main.py
ols/app/metrics/__init__.py
ols/src/cache/redis_cache.py
pdm.lock
pyproject.toml
tests/e2e/__init__.py

Update Ruff to version 0.8.0
Fixed newly found issues too

Update Ruff to version 0.8.0

---

tests/unit/app/models/test_config.py

Added missing unit tests for model configuration module
- Related Issue #[OLS-1233](https://issues.redhat.com//browse/OLS-1233)

OLS-1233: Added missing unit tests for model configuration module

---

tests/config/config_for_integration_tests.yaml
tests/integration/test_runners.py

[OLS-1233](https://issues.redhat.com//browse/OLS-1233): Integration tests for runners
- Related Issue #[OLS-1233](https://issues.redhat.com//browse/OLS-1233)

OLS-1233: Integration tests for runners

---

Makefile

Makefile target to generate LLMs classes UML diagram

Makefile target to generate LLMs classes UML diagram

---

.tekton/lightspeed-service-pull-request.yaml
.tekton/lightspeed-service-push.yaml

Add project and org to the Konflux Snyk task so Snyk scan results are sent to snyk.io.
- Related Issue # https://issues.redhat.com/browse/OLS-1271
- Closes #

OLS-1271: Add project and org to the Konflux Snyk task

---

tests/scripts/test-e2e-cluster-periodics.sh

and removing model evaluation from precommit tests
- Closes #

OLS-1252 - Adding a script file for periodic 

---

tests/integration/random_payload_generator.py
tests/integration/test_config.py

Minor fixes in integration tests

Minor fixes in integration tests

---

requirements.txt

Updated NVidia CUDA and PyTorch packages in `requirements.txt`

Updated NVidia CUDA and PyTorch packages in `requirements.txt`

---

ols/src/rag_index/index_loader.py

Added missing types

---

tests/unit/llms/providers/test_fake_provider.py

[OLS-1273](https://issues.redhat.com//browse/OLS-1273): proper fakelist LLM import
- Related Issue #[OLS-1273](https://issues.redhat.com//browse/OLS-1273)

OLS-1273: proper fakelist LLM import

---

tests/benchmarks/test_redactor.py
tests/unit/app/endpoints/test_feedback.py
tests/unit/extra_certs/test_extra_certs.py
tests/unit/llms/providers/test_azure_openai.py
tests/unit/llms/providers/test_rhelai_vllm.py
tests/unit/llms/providers/test_rhoai_vllm.py
tests/unit/query_helpers/test_attachment_appender.py

Consistent Pytest fixture usage in tests
Either removing unnecessary parentheses _or_ requiring them for all
fixtures is fine, but it's best to be consistent. It is better to
removing unnecessary parentheses, to match the documentation of the
official `pytest` projects.

Consistent Pytest fixture usage in tests

---

tests/e2e/test_api.py
tests/e2e/test_query_endpoint.py
tests/e2e/test_user_feedback.py
tests/integration/test_ols.py
tests/integration/test_redis.py
tests/unit/auth/test_k8s.py

Consistent Pytest marks in tests

Consistent Pytest marks in tests

---

scripts/generate_packages_to_prefetch.py
scripts/sync_repos.py

Added missing test for `None` value

Added missing test for `None` value

---

ols/app/models/models.py
tests/unit/app/endpoints/test_ols.py
tests/unit/app/models/test_models.py

Remove unused ReferencedDocument method

OLS-39: Remove unused ReferencedDocument method

---

ols/app/main.py
ols/version.py
tests/integration/test_project_version_consistency.py

Version in one place in sources
- Related Issue #[OLS-1168](https://issues.redhat.com//browse/OLS-1168)

OLS-1168: Version in one place in sources

---

pdm.lock
pyproject.toml

Pylint as devel dependency

---

scripts/evaluation/response_evaluation.py

Unititialized variable fix

---

Makefile

Enable Pylint on CI

---

tests/e2e/test_api.py
tests/e2e/utils/ols_installer.py

Modifying tests to fix issue with pod creation

---

scripts/generate_openapi_schema.py
scripts/questions_gen.py

Fixed imports in scripts
- [OLS-1034](https://issues.redhat.com//browse/OLS-1034)

OLS-1034: Fixed imports in scripts

---

tests/e2e/test_api.py

Test should not return anything
- Related Issue #[OLS-1034](https://issues.redhat.com//browse/OLS-1034)

OLS-1034: Test should not return anything

---

scripts/data_collection/user_data_aggregator.py

Open tarball as resource - avoid resource leak
- Related Issue #[OLS-1034](https://issues.redhat.com//browse/OLS-1034)

OLS-1034: Open tarball as resource

---

pyproject.toml

[OLS-1277](https://issues.redhat.com//browse/OLS-1277): basic support for Python 3.12
- Related Issue #[OLS-1277](https://issues.redhat.com//browse/OLS-1277)

OLS-1277: basic support for Python 3.12

---

tests/e2e/utils/cluster.py

OLS-1290 - Added better method to check if containers are ready

---

Makefile

OLS-1254 - Adding retry logic to dependencies installations in makefile

---

tests/benchmarks/test_config_loader.py

Fixed config loader benchmark

---

Containerfile

deps: upgrade RAG image to f97ead5ca7fb58f7edcfde9b5fd4c088051646d8a857bef326a3a663d8081c5f
- Closes #

deps: upgrade RAG image

---

tests/benchmarks/test_prompt_generator.py

[OLS-1298](https://issues.redhat.com//browse/OLS-1298): fix prompt generator benchmark
- Related Issue #[OLS-1298](https://issues.redhat.com//browse/OLS-1298)

OLS-1298: fix prompt generator benchmark

---

build.args

Updated konflux rag image with safetensor file  PR : https://github.com/openshift/lightspeed-rag-content/pull/181
- Closes #

Updated konflux rag image with safetensor file 

---

pdm.lock
pyproject.toml

bump up ibm-watsonx-ai to 1.1.25
[OLS-1278](https://issues.redhat.com//browse/OLS-1278)

dep: bump up ibm-watsonx-ai to 1.1.25

---

pdm.lock
pyproject.toml
requirements.txt

bump up starlette to 0.41.3
[OLS-1278](https://issues.redhat.com//browse/OLS-1278)

dep: bump up starlette to 0.41.3

---

ols/utils/token_handler.py
pyproject.toml
scripts/questions_gen.py

Don't overwrite loop variable

---

ols/app/endpoints/feedback.py
ols/app/main.py
ols/src/cache/postgres_cache.py
ols/src/llms/providers/azure_openai.py
ols/src/llms/providers/registry.py
ols/src/query_helpers/docs_summarizer.py

Remove f-strings from logging statements in OLS sources

Remove f-strings from logging statements in OLS sources

---

ols/app/models/config.py
ols/constants.py
ols/src/llms/llm_loader.py
ols/user_data_collection/data_collector.py
runner.py
scripts/generate_openapi_schema.py
scripts/questions_gen.py
tests/e2e/utils/ols_installer.py
tests/integration/test_config.py
tests/scripts/must_gather.py
tests/unit/llms/test_llm_loader.py

[OLS-1308](https://issues.redhat.com//browse/OLS-1308): config file name specified on one place
- Related Issue #[OLS-1308](https://issues.redhat.com//browse/OLS-1308)

OLS-1308: config file name specified on one place

---

ols/constants.py
ols/user_data_collection/data_collector.py
runner.py
scripts/generate_openapi_schema.py
scripts/questions_gen.py
tests/integration/test_liveness_readiness.py
tests/integration/test_metrics.py
tests/integration/test_openapi.py

[OLS-1308](https://issues.redhat.com//browse/OLS-1308): environment variable with config file on one place
- Related Issue #[OLS-1308](https://issues.redhat.com//browse/OLS-1308)

OLS-1308: environment variable with config file on one place

---

README.md

[OLS-1277](https://issues.redhat.com//browse/OLS-1277): Correct Python version in README.md
- Related Issue #[OLS-1277](https://issues.redhat.com//browse/OLS-1277)

OLS-1277: Correct Python version in README.md

---

Makefile

Better way to generate requirements.txt

OLS-1311: Better way to generate requirements.txt

---

scripts/evaluation/utils/models.py
scripts/generate_openapi_schema.py
scripts/questions_gen.py

Proper pylint settings for scripts

Proper pylint settings for scripts

---

Makefile
scripts/data_collection/user_data_aggregator.py
scripts/generate_packages_to_prefetch.py
scripts/print_ec_failures.py
scripts/questions_gen.py

Enable Pylint for scripts + fix all Pylint-related issues

Enable Pylint for scripts + fix all Pylint-related issues

---

tests/e2e/test_api.py
tests/e2e/utils/cluster.py
tests/scripts/test-e2e-cluster-periodics.sh
tests/scripts/test-e2e-cluster.sh

OLS-587 - Adding test_generated_service_certs_rotation

---

tests/e2e/conftest.py
tests/e2e/test_api.py
tests/e2e/utils/cluster.py
tests/integration/test_config.py
tests/integration/test_openapi.py
tests/integration/test_project_version_consistency.py

Specify encoding in all file `open` operation in tests

Specify encoding in all file open operation in tests

---

ols/app/models/config.py
tests/unit/app/models/test_config.py

DevConfig `__eq__` special method

OLS-1323: DevConfig `__eq__` special method

---

Makefile

OLS-1323: Enable Pylint for tests

---

tests/unit/app/models/test_config.py

Unit tests: QueryFilter equality checks

OLS-1323: Unit tests: QueryFilter equality checks

---

CONTRIBUTING.md

OLS-1323: Updated info about linters

---

README.md

[OLS-1276](https://issues.redhat.com//browse/OLS-1276): doc about system prompt override mechanism
- Related Issue #[OLS-1276](https://issues.redhat.com//browse/OLS-1276)

OLS-1276: doc about system prompt override mechanism

---

README.md
examples/olsconfig.yaml
ols/constants.py
scripts/evaluation/driver.py
scripts/evaluation/eval_data/question_answer_pair.json
scripts/evaluation/utils/constants.py
scripts/questions_gen.py
tests/benchmarks/test_prompt_generator.py
tests/config/auth_config.yaml
tests/config/config_for_integration_tests.yaml
tests/config/config_for_integration_tests_8443.yaml
tests/config/minimal_config.yaml
tests/config/operator_install/olsconfig.crd.bam.yaml
tests/config/operator_install/olsconfig.crd.watsonx.yaml
tests/config/test_app_endpoints.yaml
tests/e2e/conftest.py
tests/e2e/test_api.py
tests/e2e/test_query_endpoint.py
tests/e2e/utils/metrics.py
tests/integration/test_ols.py
tests/scripts/test-e2e-cluster-periodics.sh
tests/scripts/test-e2e-cluster.sh
tests/unit/app/models/test_config.py
tests/unit/prompts/test_prompt_generator.py

use granite3 reference instead of granite2
[OLS-1269](https://issues.redhat.com//browse/OLS-1269)

use granite3 reference instead of granite2

---

scripts/generate_packages_to_prefetch.py

Ability to filter packages by architecture
- Related Issue #[OLS-1325](https://issues.redhat.com//browse/OLS-1325)

OLS-1325: Ability to filter packages by architecture

---

.tekton/lightspeed-service-push.yaml

konflux pipeline nudges related_images.json
- Closes #

config: konflux pipeline nudges related_images.json

---

scripts/evaluation/eval_data/question_answer_pair.json

modified ans (eval2) for granite3

eval: modified ans (eval2) for granite3

---

pdm.lock

[OLS-1331](https://issues.redhat.com//browse/OLS-1331): sync PDM lockfile
- Related Issue #[OLS-1331](https://issues.redhat.com//browse/OLS-1331)

OLS-1331: sync PDM lockfile

---

README.md
runner.py

[OLS-1335](https://issues.redhat.com//browse/OLS-1335): Ability to print actual configuration
- Related Issue #[OLS-1335](https://issues.redhat.com//browse/OLS-1335)

OLS-1335: Ability to print actual configuration

---

Makefile
runner.py

Pylint for runner.py

---

README.md

Info about Redoc page

---

tests/unit/ui/test_gradio_ui.py

System prompt UI widget unit test

System prompt UI widget unit test

---

ols/app/endpoints/ols.py

Fixed type hints in code introduced in #2014

Fixed type hints in streaming endpoint-related changes

---

README.md

Docs: query mechanisms

---

ols/app/models/config.py
tests/unit/app/models/test_config.py

Bug fix: `OLSConfig` equality

---

tests/e2e/pytest.ini
tests/e2e/test_api.py

Adding new tag for user_data_collection test to not run in konflux

---

tests/e2e/test_query_endpoint.py
tests/e2e/test_streaming_query_endpoint.py

Constant query endpoints

---

Makefile

Fixed UML diagrams command

---

ols/app/endpoints/feedback.py
ols/utils/tls.py
tests/e2e/test_api.py

Don't redeclare outer scope vars by local ones

Don't redeclare outer scope vars by local ones

---

ols/app/endpoints/health.py
ols/app/endpoints/ols.py
ols/src/llms/llm_loader.py
ols/src/query_helpers/docs_summarizer.py
ols/src/query_helpers/query_helper.py
ols/src/query_helpers/question_validator.py
tests/mock_classes/mock_llm_loader.py
tests/unit/query_helpers/test_docs_summarizer.py
tests/unit/query_helpers/test_query_helper.py
tests/unit/query_helpers/test_question_validator.py

Pass `streaming` parameter to LLM loader

Pass `streaming` parameter to LLM loader

---

pyproject.toml

New commands to verify sources and packages

New commands to verify sources and packages

---

ols/app/endpoints/health.py
ols/src/llms/llm_loader.py
ols/src/llms/providers/azure_openai.py
ols/src/llms/providers/openai.py
ols/src/llms/providers/provider.py
ols/src/llms/providers/rhelai_vllm.py
ols/src/llms/providers/rhoai_vllm.py
tests/unit/llms/providers/test_providers.py

Pass streaming parameter to LLM providers explicitly

Pass streaming parameter to LLM providers explicitly

---

Containerfile

to avoid falling into network issues
- Closes #

OLS-1339 - Adding retry logic to the pip install command in dockerfile 

---

README.md

[doc] Added new commands into README.md

[doc] Added new commands into README.md

---

README.md

- Doc auth user validation
- Fixed MIME type for streaming endpoint
- Related Issue #[OLS-1377](https://issues.redhat.com//browse/OLS-1377)

OLS-1377: Doc auth user validation

---

scripts/generate_packages_to_prefetch.py

Fixed package to prefetch generator

Fixed package to prefetch generator

---

scripts/codecov.sh

Fixed `codecov.sh` problems found by linter

Fixed `codecov.sh` problems found by linter

---

pdm.lock
pyproject.toml

Fix CI job failure

---

docs/openapi.json
ols/app/endpoints/authorized.py
ols/app/endpoints/ols.py
ols/app/endpoints/streaming_ols.py
ols/app/models/models.py
ols/src/auth/auth_dependency_interface.py
ols/src/auth/k8s.py
ols/src/auth/noop.py
ols/src/cache/cache.py
ols/src/cache/in_memory_cache.py
ols/src/cache/postgres_cache.py
ols/src/cache/redis_cache.py
tests/integration/test_authorized.py
tests/integration/test_authorized_noop.py
tests/unit/app/endpoints/test_authorized.py
tests/unit/app/endpoints/test_ols.py
tests/unit/auth/test_k8s.py
tests/unit/auth/test_noop_auth_dependency.py
tests/unit/cache/test_in_memory_cache.py
tests/unit/cache/test_redis_cache.py

[OLS-1375](https://issues.redhat.com//browse/OLS-1375): Skip user id check for noop auth module
- Related Issue #[OLS-1375](https://issues.redhat.com//browse/OLS-1375)

OLS-1375: Skip user id check for noop auth

---

ols/app/models/models.py
tests/unit/app/models/test_models.py

Message encoders and decoders

---

README.md

Rewritten section fine tuning to correctly reflect the subject

[upstream] Rewritten section fine tuning to correctly reflect the subject

---

ols/app/endpoints/ols.py

Better logging + info about auth module
- [OLS-1355](https://issues.redhat.com//browse/OLS-1355)

OLS-1355: Better logging + info about auth module

---

tests/e2e/test_streaming_query_endpoint.py

Hopefully some improvement in tests flakiness

Enfore http/1.0 to reedice flakines

---

scripts/evaluation/response_evaluation.py
scripts/evaluation/utils/prompts.py
scripts/evaluation/utils/relevancy_score.py
scripts/evaluation/utils/similarity_score_llm.py

- Fix relevancy prompt for other models
- Store calculated score to avoid re-calculation if script fails between models.

eval: fix prompt & save temp score

---

pdm.lock
pyproject.toml

[OLS-1419](https://issues.redhat.com//browse/OLS-1419): Security fix: cryptography module > 4.0.0
- Related Issue #[OLS-1419](https://issues.redhat.com//browse/OLS-1419)

OLS-1419: Security fix: cryptography module > 4.0.0

---

Makefile

OLS-1414 - Adding the mypy command from check types to verify

---

requirements.txt

Fixed [OLS-1425](https://issues.redhat.com//browse/OLS-1425): CVE
- Related Issue #[OLS-1425](https://issues.redhat.com//browse/OLS-1425)

Fixed OLS-1425: CVE

---

tests/benchmarks/test_docs_summarizer.py
tests/benchmarks/test_prompt_generator.py
tests/benchmarks/test_question_validator.py
tests/benchmarks/test_token_handler.py

Fix issues in benchmarks

---

tests/e2e/utils/ols_installer.py

OLS-1433 - Adding logging to the olsconfig creation failure.

---

ols/app/models/models.py
tests/unit/app/models/test_models.py

Unit tests for message encoders and decoders
- Related Issue #[OLS-1376](https://issues.redhat.com//browse/OLS-1376)

OLS-1376: Unit tests for message encoders and decoders

---

ols/app/endpoints/ols.py
ols/app/endpoints/streaming_ols.py
ols/app/models/models.py
tests/integration/test_ols.py
tests/unit/app/endpoints/test_ols.py

Refactored query processor: use Pydantic dataclass
Fixed integration tests (were broken and we did not caught it)
Fixed unit test (was broken and we did not caught it)

Refactored query processor: use Pydantic dataclass

---

tests/scripts/test-e2e-cluster-periodics.sh

adapting periodic tests calling to cluster awareness changes
- Closes #

OLS-1433 - Fixing periodic tests

---

docs/openapi.json
ols/version.py
scripts/build-container.sh

Bump to version 0.3.1 for OLS release
- Closes #

Bump to version 0.3.1

---

tests/unit/app/models/test_config.py

Added missing unit tests for reference content configuration

Added missing unit tests for reference content configuration

---

ols/src/cache/cache_factory.py

Fixed comment: Postgres cache was missing

Fixed comment: Postgres cache was missing

---

scripts/evaluation/utils/rag.py
scripts/evaluation/utils/response.py

- Fix error due to recent history format change.
- Remove deprecated LLMChain.

eval: change according to latest history format

---

ols/app/endpoints/ols.py
ols/app/endpoints/streaming_ols.py

Refactoring: token counter updaters
(will be used later by quota checkers)

Refactoring: token counter updaters

---

ols/app/models/config.py

Added missing eq comparator

---

tests/unit/utils/test_config.py

Added missing tests: user data collection attributes

Added missing tests: user data collection attributes

---

ols/app/models/config.py
ols/user_data_collection/data_collector.py

Storing all user data collection parameters in config
Sync with upstream
#[OLS-1467](https://issues.redhat.com//browse/OLS-1467)

OLS-1467: Storing all user data collection parameters in config

---

CONTRIBUTING.md
Makefile

Simplifying test run 

---

tests/unit/app/test_routers.py

Unit tests for routers

---

ols/src/quota/__init__.py
ols/src/quota/cluster_quota_limiter.py
ols/src/quota/quota_exceed_error.py
ols/src/quota/quota_limiter.py
ols/src/quota/revokable_quota_limiter.py
ols/src/quota/user_quota_limiter.py
tests/unit/quota/__init__.py
tests/unit/quota/test_cluster_quota_limiter.py
tests/unit/quota/test_quota_exceed_error.py
tests/unit/quota/test_user_quota_limiter.py

[OLS-1390](https://issues.redhat.com//browse/OLS-1390): Quota limiters implementation
- Related Issue #[OLS-1390](https://issues.redhat.com//browse/OLS-1390)

OLS-1390: Quota limiters implementation

---

ols/src/prompts/prompts.py

Outcome of https://redhat-internal.slack.com/archives/C068JAU4Y0P/p1741089250418629

OLS-1472: Update tool calling instructions

---

tests/benchmarks/test_question_validator.py

update query validator benchmark script to remove LLMChain mocking

update query validator benchmark script

---

ols/app/models/config.py
ols/utils/config.py
tests/unit/utils/test_config.py

[OLS-1390](https://issues.redhat.com//browse/OLS-1390): Quota limiter as config property
- Related Issue #[OLS-1390](https://issues.redhat.com//browse/OLS-1390)

OLS-1390: Quota limiter as config property

---

tests/e2e/conftest.py
tests/e2e/pytest.ini
tests/e2e/test_api.py
tests/e2e/test_query_endpoint.py

Even if a single test is called in that session.
- Closes #

OLS-1404 - Move setup to conftest to run before any session starts. 

---

tests/e2e/test_api.py

OLS-1360 - Removing not konflux tag from user-data-collection test

---

ols/runners/uvicorn.py

Added missing logging info for Uvicorn runner

Added missing logging info for Uvicorn runner

---

pdm.lock
pyproject.toml
requirements.txt

Bump all dependecies
- Closes #

OLS-1307: Bump deps

---

ols/app/models/config.py
tests/unit/app/models/test_config.py
tests/unit/utils/test_config.py

Quota limiter config tests

---

tests/e2e/utils/ols_installer.py

OLS-1489 - Adding option to install bundle via provided image

---

ols/app/endpoints/ols.py
ols/src/quota/quota_limiter.py
tests/unit/app/endpoints/test_ols.py

Check token usage + consume tokens functionality
- Related Issue #[OLS-1390](https://issues.redhat.com//browse/OLS-1390)

OLS-1390: Check token usage + consume tokens functionality

---

docs/openapi.json
ols/app/endpoints/streaming_ols.py
tests/unit/app/endpoints/test_streaming_ols.py

[OLS-1462](https://issues.redhat.com//browse/OLS-1462) - fixed mismatch between API documentation and actual behaviour
- Related Issue #[OLS-1462](https://issues.redhat.com//browse/OLS-1462)

OLS-1462 - fixed mismatch between API documentation and actual behaviour

---

README.md
ols/src/query_helpers/docs_summarizer.py
ols/src/tools/oc_cli.py
ols/src/tools/tools.py
tests/integration/test_ols.py
tests/unit/query_helpers/test_docs_summarizer.py
tests/unit/tools/test_oc_cli.py
tests/unit/tools/test_tools.py

Use user token directly in oc tools

OLS-1459: Token in oc

---

.tekton/lightspeed-service-pull-request.yaml
.tekton/lightspeed-service-push.yaml
Containerfile
artifacts.lock.yaml
build.args
redhat.repo
rpms.in.yaml
rpms.lock.yaml

Fetch openshift-clients from RHEL subscription content
- [] Configuration Update
- Closes #

Fetch openshift-clients from RHEL subscription content

---

tests/unit/llms/providers/test_azure_openai.py
tests/unit/llms/providers/test_providers.py
tests/unit/llms/providers/test_watsonx.py

HTTPX client unit test

---

ols/app/endpoints/streaming_ols.py

Explicitly set HTTP code for streaming response

[minor] Explicitly set HTTP code for streaming response

---

Makefile

Make target to render configuration diagram

Make target to render configuration diagram

---

ols/src/tools/oc_cli.py

Update oc tools docs
- Closes #

Update oc tools

---

ols/runners/quota_scheduler.py
runner.py
tests/config/config_for_integration_tests_quota_limiters.yaml
tests/integration/test_runners.py
tests/unit/runners/test_quota_scheduler_runner.py

[OLS-1390](https://issues.redhat.com//browse/OLS-1390): Quota scheduler
- Related Issue #[OLS-1390](https://issues.redhat.com//browse/OLS-1390)

OLS-1390: Quota scheduler

---

tests/e2e/conftest.py
tests/e2e/test_api.py

Readd the artifact gathering to the tests

---

scripts/evaluation/rag_eval.py
scripts/evaluation/response_evaluation.py
scripts/evaluation/utils/constants.py
scripts/evaluation/utils/plot.py
scripts/evaluation/utils/prompts.py

One of the approach to evaluate retrieval using penalised score for 1st chunk.
[OLS-1457](https://issues.redhat.com//browse/OLS-1457)

eval: add chunk eval

---

ols/app/models/config.py
ols/runners/quota_scheduler.py
ols/src/quota/quota_limiter_factory.py
ols/utils/config.py
tests/config/config_for_integration_tests_quota_limiters.yaml
tests/unit/app/models/test_config.py
tests/unit/quota/test_quota_limiter_factory.py
tests/unit/runners/test_quota_scheduler_runner.py
tests/unit/utils/test_config.py

[OLS-1486](https://issues.redhat.com//browse/OLS-1486): quota limiters to quota handlers
- Related Issue #[OLS-1486](https://issues.redhat.com//browse/OLS-1486)

OLS-1486: quota limiters to quota handlers

---

ols/app/endpoints/streaming_ols.py

[OLS-1486](https://issues.redhat.com//browse/OLS-1486): Consume tokens for streaming endpoint
- Related Issue #[OLS-1486](https://issues.redhat.com//browse/OLS-1486)

OLS-1486: Consume tokens for streaming endpoint

---

ols/src/llms/providers/azure_openai.py
tests/unit/llms/providers/test_azure_openai.py

Fix the cache value for azure token expiration
- Closes #

OLS-1386: Fix the cache value for azure token expiration

---

ols/app/endpoints/ols.py
ols/app/endpoints/streaming_ols.py
ols/app/models/config.py
ols/src/quota/token_usage_history.py
ols/utils/config.py
tests/unit/app/endpoints/test_ols.py
tests/unit/quota/test_token_usage_history.py

[OLS-1486](https://issues.redhat.com//browse/OLS-1486): Token usage history
- Related Issue #[OLS-1486](https://issues.redhat.com//browse/OLS-1486)

OLS-1486: Token usage history

---

.coveragerc

Do not measure coverage for type checks imports

Do not measure coverage for type checks imports

---

ols/constants.py
scripts/evaluation/utils/models.py
tests/e2e/test_query_endpoint.py
tests/e2e/test_streaming_query_endpoint.py
tests/unit/app/models/test_config.py

Increase default context window size
- Closes #

OLS-1405: Increase default context window size

---

ols/app/endpoints/ols.py
ols/app/endpoints/streaming_ols.py
ols/app/models/models.py
ols/src/query_helpers/docs_summarizer.py
tests/e2e/test_api.py
tests/unit/app/endpoints/test_ols.py
tests/unit/app/models/test_models.py
tests/unit/query_helpers/test_docs_summarizer.py

Add tool info in transcripts
- Closes #

OLS-1402: Add tool info in transcripts

---

.github/dependabot.yml

Remove dependabot configuration. We no longer need this.
- Closes #

OLS-1524: Remove dependabot configuration

---

pdm.lock
requirements.txt

OLS-1307: Bump dependecies

---

.tekton/lightspeed-service-pull-request.yaml
.tekton/lightspeed-service-push.yaml
Containerfile
rpms.lock.yaml
ubi.repo

[OLS-1256](https://issues.redhat.com//browse/OLS-1256): Add OLS ARM builds to Konflux
- Related Issue # https://issues.redhat.com//browse/OLS-1256
- Closes #

OLS-1256: Add OLS ARM builds to Konflux

---

docs/openapi.json
ols/app/endpoints/ols.py
ols/app/endpoints/streaming_ols.py
ols/app/models/models.py
ols/src/quota/quota_limiter.py
ols/src/quota/revokable_quota_limiter.py
tests/integration/test_ols.py
tests/unit/app/endpoints/test_streaming_ols.py
tests/unit/app/models/test_models.py

[OLS-1518](https://issues.redhat.com//browse/OLS-1518): token limits in REST API responses
- Related Issue #[OLS-1518](https://issues.redhat.com//browse/OLS-1518)

OLS-1518: token limits in REST API responses

---

renovate.json

Add renovate config
- Closes #

OLS-1524: Add renovate.json

---

tests/unit/quota/test_cluster_quota_limiter.py
tests/unit/quota/test_token_usage_history.py
tests/unit/quota/test_user_quota_limiter.py

[OLS-1519](https://issues.redhat.com//browse/OLS-1519): mocked timestamps created via context manager

OLS-1519: mocked timestamps created via context manager

---

ols/app/main.py
tests/integration/test_metrics.py

This fix avoid gathering metrics from querying undefined routes.
- Closes # [OLS-1549](https://issues.redhat.com/browse/OLS-1549)

OLS-1549: fix - no metrics are gathered from serving undefined routes

---

ols/app/main.py

Fixed import sorting

---

CONTRIBUTING.md

Modifying section on patching to discourage use of decorators

Modifying section on patching to discourage use of decorators

---

renovate.json

Updated version of renvoate config
- Closes #

Update renovate.json config

---

scripts/evaluation/response_evaluation.py

eval: fix issue post pandas upgrade

---

docs/openapi.json
ols/version.py
scripts/build-container.sh

Prepare release 0.3.3
- Closes #

Bump to version 0.3.3

---

tests/unit/app/endpoints/test_ols.py

Added missing unit tests for OLS helper functions

Added missing unit tests for OLS helper functions

---

ols/src/cache/postgres_cache.py
tests/unit/cache/test_postgres_cache.py

Fix PG issue
Conversion retrieved values from memoryview to string before deserialization
#[ols-1627](https://issues.redhat.com//browse/ols-1627)

OLS-1627: Fix PG issue

---

.tekton/lightspeed-service-pull-request.yaml
.tekton/lightspeed-service-push.yaml

config: add to konflux pipeline: sast-shell-check-oci-ta, sast-unicode-check-oci-ta.
This fixes the EC violation below:
```
✕ [Violation] tasks.required_tasks_found
ImageRef: quay.io/redhat-user-workloads/crt-nshift-lightspeed-tenant/ols/lightspeed-service@sha256:d8571ce72d6de777ebb22954a3e853b503da693fc444330af1220f0951fcaade
Reason: One of "sast-unicode-check", "sast-unicode-check-oci-ta" tasks is missing
Title: All required tasks were included in the pipeline
Description: Ensure that the set of required tasks are included in the PipelineRun attestation. To exclude this rule add one or
more of "tasks.required_tasks_found:sast-unicode-check", "tasks.required_tasks_found:sast-unicode-check-oci-ta" to the `exclude`
section of the policy configuration.
Solution: Make sure all required tasks …
```

EC violations fix, add 2 sast checks

---

ols/app/endpoints/ols.py
ols/app/endpoints/streaming_ols.py
ols/app/models/models.py
ols/constants.py
ols/customize/__init__.py
ols/customize/ols/prompts.py
ols/src/prompts/prompt_generator.py
ols/src/query_helpers/query_helper.py
ols/src/query_helpers/question_validator.py
ols/src/ui/gradio_ui.py
tests/integration/test_ols.py
tests/unit/app/endpoints/test_ols.py
tests/unit/app/endpoints/test_streaming_ols.py
tests/unit/prompts/test_prompt_generator.py

[OLS-1615](https://issues.redhat.com//browse/OLS-1615): Customized prompts
- Related Issue #[OLS-1615](https://issues.redhat.com//browse/OLS-1615)

OLS-1615: Customized prompts

---

tests/mock_classes/mock_llama_index.py
tests/mock_classes/mock_redis_client.py

Note about `@patch` decorator deprecation
- Related Issue #[OLS-1615](https://issues.redhat.com//browse/OLS-1615)

OLS-1615: Note about @patch decorator deprecation

---

ols/src/tools/tools.py
tests/unit/tools/test_tools.py

- It may contain secret information.
Don't capture the literal error in case of wrong tool args
- Closes #

Don't capture the literal error in case of wrong tool args

---

ols/customize/__init__.py
ols/customize/ols/reranker.py
ols/src/query_helpers/docs_summarizer.py
tests/unit/query_helpers/test_docs_summarizer.py

Reranker as customized part
It is no-op for OLS
- Related Issue #[OLS-1615](https://issues.redhat.com//browse/OLS-1615)

OLS-1615: Reranker as customized part

---

tests/benchmarks/test_question_validator.py

Fixed QuestionValidator benchmark
- Related Issue #[OLS-1647](https://issues.redhat.com//browse/OLS-1647)

OLS-1647: Fixed QuestionValidator benchmark

---

pdm.lock
requirements.txt

OLS-1307: Update dependencies

---

docs/openapi.json
ols/app/main.py
ols/customize/__init__.py
ols/customize/ols/metadata.py
tests/e2e/test_api.py
tests/integration/test_openapi.py

Customizable service name
- Related Issue #[OLS-1615](https://issues.redhat.com//browse/OLS-1615)

OLS-1615: customizable service name

---

tests/e2e/utils/cluster.py
tests/e2e/utils/ols_installer.py
tests/e2e/utils/retry.py
tests/scripts/must_gather.py

Ability to debug e2e service startup issues

Ability to debug e2e service startup issues

---

pdm.lock
pyproject.toml
requirements.txt
scripts/evaluation/taxonomy_eval.py
scripts/evaluation/utils/prompts.py

- Context
- Flag to check if context is valid as per the query.
- Context relevancy score against the answer.
- Answer
- Answer relevancy score against the query.
- Answer ground-ness score against the context
Both custom & ragas implementation are done to check answer & context.
Script to automate the process with taxonomy file
[OLS-1368](https://issues.redhat.com//browse/OLS-1368)

eval: taxonomy - context & answer relevancy

---

tests/unit/plugins/test_plugins.py

More unit tests for plugin loader

More unit tests for plugin loader

---

scripts/generate_openapi_schema.py
scripts/olsconfig.yaml

Fixed issue #[OLS-1639](https://issues.redhat.com//browse/OLS-1639)
- Related Issue #[OLS-1639](https://issues.redhat.com//browse/OLS-1639)

Fixed issue #1639 - ability to generate schema without full configuration file in place

---

README.md
pdm.lock
pyproject.toml

[LCORE-61](https://issues.redhat.com//browse/LCORE-61): Proper Python version
- Related Issue #[LCORE-61](https://issues.redhat.com//browse/LCORE-61)

LCORE-61: Proper Python version

---

tests/e2e/test_query_endpoint.py
tests/e2e/test_streaming_query_endpoint.py

In the OCP docs version test, check the URL and not the title of the "Welcome" page
- Closes #

In the OCP docs version test, check the URL

---

scripts/olsconfig.yaml

Fix make-schema target

---

README.md

Updated docs: quota limits

---

Makefile

Changing the default make target to be the help

---

ols/constants.py
ols/src/auth/auth.py
ols/src/auth/noop_with_token.py
tests/unit/auth/test_auth.py
tests/unit/auth/test_noop_with_token.py

Noop with token auth module
- Closes #

Noop with token auth module

---

docs/openapi.json
ols/app/endpoints/ols.py
ols/app/endpoints/streaming_ols.py
ols/app/metrics/token_counter.py
ols/app/models/models.py
ols/src/query_helpers/docs_summarizer.py
ols/src/tools/oc_cli.py
ols/src/tools/tools.py
tests/e2e/test_streaming_query_endpoint.py
tests/integration/test_ols.py
tests/mock_classes/mock_llm_loader.py
tests/unit/app/endpoints/test_ols.py
tests/unit/app/endpoints/test_streaming_ols.py
tests/unit/app/metrics/test_token_counter.py
tests/unit/app/models/test_models.py
tests/unit/query_helpers/test_docs_summarizer.py
tests/unit/tools/test_oc_cli.py
tests/unit/tools/test_tools.py

OLS-1454: Enable introspection for both endpoints

---

ols/app/models/config.py
ols/src/llms/providers/fake_provider.py
ols/src/llms/providers/provider.py
tests/unit/llms/providers/test_fake_provider.py

Support Fake Streaming list LLM

Support Fake Streaming list LLM

---

examples/olsconfig.yaml
ols/app/endpoints/health.py
ols/app/endpoints/ols.py
ols/app/models/config.py
ols/src/query_helpers/docs_summarizer.py
ols/src/rag_index/index_loader.py
ols/utils/config.py
tests/config/auth_config.yaml
tests/config/config_for_integration_tests.yaml
tests/config/config_for_integration_tests_8443.yaml
tests/config/config_without_logging.yaml
tests/config/invalid_config.yaml
tests/config/minimal_config.yaml
tests/config/test_app_endpoints.yaml
tests/config/valid_config.yaml
tests/config/valid_config_postgres.yaml
tests/config/valid_config_redis.yaml
tests/config/valid_config_with_query_filter.yaml
tests/config/valid_config_without_certificate_directory.yaml
tests/config/valid_config_without_query_filter.yaml
tests/e2e/utils/ols_installer.py
tests/unit/app/models/test_config.py
tests/unit/query_helpers/test_docs_summarizer.py
tests/unit/rag_index/test_index_loader.py
tests/unit/utils/test_config.py

This PR goes together with [this PR on the operator side](https://github.com/openshift/lightspeed-operator/pull/668).
This PR changes the config structure that supports multiple RAG indexes using the same embedding model. 
- Related Issue # [OLS-1418](https://issues.redhat.com//browse/OLS-1418)
- Closes #

OLS-1418: Config + IndexLoader update of multiple RAG support.

---

ols/src/cache/postgres_cache.py
ols/src/quota/cluster_quota_limiter.py
ols/src/quota/quota_limiter.py
ols/src/quota/revokable_quota_limiter.py
ols/src/quota/user_quota_limiter.py
ols/utils/connection_decorator.py
tests/unit/cache/test_postgres_cache.py
tests/unit/utils/test_connection_decorator.py

[OLS-1654](https://issues.redhat.com//browse/OLS-1654): `Connection.connect` refactoring, connection decorator, updated unit tests accordingly
- Related Issue #[OLS-1654](https://issues.redhat.com//browse/OLS-1654)

OLS-1654: Connection.connect refactoring + connection decorator

---

docs/openapi.json
ols/version.py
scripts/build-container.sh

prepare for release 0.3.4
- Related Issue # [OLS-1643](https://issues.redhat.com//browse/OLS-1643)
- Closes #

OLS-1643: Bump to version 0.3.4

---

ols/src/quota/quota_limiter.py
ols/src/quota/revokable_quota_limiter.py
ols/src/quota/token_usage_history.py
tests/unit/quota/test_cluster_quota_limiter.py
tests/unit/quota/test_token_usage_history.py
tests/unit/quota/test_user_quota_limiter.py

[OLS-1654](https://issues.redhat.com//browse/OLS-1654) recconnection for quota limiters
- Related Issue #[OLS-1645](https://issues.redhat.com//browse/OLS-1645)

OLS-1654 recconnection for quota limiters

---

tests/e2e/test_streaming_query_endpoint.py
tests/e2e/utils/ols_installer.py

OLS-1662 - Changing timeout for streaming tests

---

README.md

Quota limit docs update

---

tests/e2e/test_query_endpoint.py

fix: e2e number chunks retrieved check
as 4.15 & 4.16 index return 4 chunks (less than expected max of 5)

fix: e2e number chunks retrieved check

---

tests/e2e/test_query_endpoint.py
tests/e2e/test_streaming_query_endpoint.py

add streaming rag for introspection.
remove multiple introspection rag related test case.. keeping one rag test case for both streaming/non-streaming.

e2e: add streaming rag for introspection

---

tests/unit/rag_index/test_index_loader.py

Fixed [OLS-1631](https://issues.redhat.com//browse/OLS-1631): tests should not perform any API calls
- Related Issue #[OLS-1631](https://issues.redhat.com//browse/OLS-1631)

Fixed OLS-1631: tests should not perform any API calls

---

scripts/evaluation/taxonomy_eval.py

Save result to different file based on taxonomy eval method to avoid accidentally replacing.

eval: taxonomy eval-save to diff file based on method

---

Makefile
pyproject.toml

Ruff rule ignores in project file

Ruff rule ignores in project file

---

ols/app/models/models.py
ols/src/prompts/prompt_generator.py
ols/src/quota/quota_exceed_error.py

Added missing type annotations

Added missing type annotations

---

ols/runners/quota_scheduler.py

Proper `AppConfig` parameter type to start quota runner

Proper AppConfig parameter type to start quota runner

---

ols/src/tools/oc_cli.py
ols/src/tools/tools.py
tests/integration/test_ols.py
tests/mock_classes/mock_tools.py
tests/unit/query_helpers/test_docs_summarizer.py
tests/unit/tools/test_oc_cli.py
tests/unit/tools/test_tools.py

- More robust tool execution.
- Redaction of token.
- Small changes in tools (renaming).
- Closes #

Tools improvements

---

ols/src/llms/providers/azure_openai.py
ols/src/llms/providers/openai.py
ols/src/llms/providers/provider.py
ols/src/llms/providers/rhelai_vllm.py
ols/src/llms/providers/rhoai_vllm.py
ols/src/llms/providers/watsonx.py
tests/unit/llms/providers/test_providers.py
tests/unit/llms/test_llm_loader.py

Changed types for LLM providers chat objects

Changed types for LLM providers chat objects

---

tests/unit/llms/providers/test_azure_openai.py
tests/unit/utils/test_config.py

Updated unit tests

---

tests/benchmarks/test_errors_parsing.py
tests/unit/utils/test_errors_parsing.py

Use proper `Response` objects in tests

Use proper Response objects in tests

---

ols/plugins/__init__.py
tests/integration/test_authorized.py
tests/integration/test_metrics.py
tests/mock_classes/mock_retrievers.py
tests/unit/extra_certs/test_extra_certs.py

Minor fixes 

---

tests/e2e/conftest.py
tests/e2e/test_api.py
tests/e2e/test_attachments.py
tests/e2e/test_query_endpoint.py
tests/e2e/test_streaming_query_endpoint.py
tests/e2e/test_user_feedback.py

Handling custom `pytest` attributes by linters

Handling custom pytest attributes by linters

---

ols/app/endpoints/ols.py
ols/app/metrics/metrics.py
ols/src/quota/quota_limiter.py

[OLS-1714](https://issues.redhat.com//browse/OLS-1714) sync with upstream + pg2 errors handler

OLS-1714 sync with upstream + pg2 errors handler

---

tests/unit/cache/test_postgres_cache.py
tests/unit/quota/test_cluster_quota_limiter.py
tests/unit/quota/test_token_usage_history.py
tests/unit/quota/test_user_quota_limiter.py

[OLS-1714](https://issues.redhat.com//browse/OLS-1714): Postgres storage unit tests hardening
- Related Issue #[OLS-1714](https://issues.redhat.com//browse/OLS-1714)

OLS-1714: Postgres storage unit tests hardening

---

tests/e2e/evaluation/test_evaluation.py

Fixed minor issues in evaluation tests script

Fixed minor issues in evaluation tests script

---

docs/openapi.json
ols/version.py
scripts/build-container.sh

version bump to prepare release 0.3.5.
- Related Issue # [OLS-1734](https://issues.redhat.com//browse/OLS-1734)
- Closes #

OLS-1734: Bump to version 0.3.5

---

mcp_local/openshift.py

Update oc_logs description with namespace

Update oc_logs description with namespace

---

tests/e2e/utils/ols_installer.py

Minor fixes in OLS installer

---

tests/integration/test_authorized.py
tests/integration/test_feedback.py
tests/integration/test_liveness_readiness.py
tests/integration/test_metrics.py
tests/integration/test_ols.py
tests/integration/test_openapi.py

[minor] Silence Pyright's improper linting error

[minor] Silence Pyright's improper linting error

---

tests/mock_classes/mock_retrieved_node.py

Fixed mock retrieved node class

Fixed mock retrieved node class

---

tests/unit/app/models/test_config.py
tests/unit/utils/test_redactor.py

Fixed tools config tests

---

scripts/evaluation/rag_eval.py
scripts/evaluation/response_evaluation.py
scripts/evaluation/taxonomy_eval.py
scripts/evaluation/utils/models.py
scripts/evaluation/utils/relevancy_score.py
scripts/evaluation/utils/response.py
scripts/evaluation/utils/score.py
scripts/evaluation/utils/similarity_score_llm.py

Minor fixes in evaluation scripts

Minor fixes in evaluation scripts

---

tests/unit/app/endpoints/test_ols.py

Proper model constructor for `RagChunk`

Proper model constructor for RagChunk

---

pdm.lock
requirements.txt

Bump mypy to 1.16.0
- Closes #

Bump mypy to 1.16.0

---

ols/utils/errors_parsing.py
tests/unit/app/endpoints/test_streaming_ols.py

Improve default error message
- Closes #

OLS-1774: Improve default error message

---

ols/src/query_helpers/docs_summarizer.py
ols/src/tools/tools.py
pdm.lock
requirements.txt
tests/integration/test_ols.py
tests/mcp_local/test_openshift.py
tests/unit/query_helpers/test_docs_summarizer.py
tests/unit/tools/test_tools.py

Bump langchain-mcp-adapters to 0.1.1
- Closes #

Bump langchain-mcp-adapters to 0.1.1

---

tests/config/operator_install/olsconfig.crd.azure_openai_tool_calling.yaml
tests/config/operator_install/olsconfig.crd.openai_tool_calling.yaml
tests/config/operator_install/olsconfig.crd.watsonx_tool_calling.yaml
tests/e2e/utils/ols_installer.py

Use CRD introspection flag to enable tool calling - trying reraise
- Closes #

Use CRD introspection flag to enable tool calling

---

docs/openapi.json
ols/version.py
scripts/build-container.sh

Bump to version 0.3.6

---

tests/unit/app/models/test_config.py

Trigger building a new snapshot after [EC rule updates ](https://gitlab.cee.redhat.com/releng/konflux-release-data/-/merge_requests/6775//diffs#d4abc29a7e77b3a790a731d7e45e8b1435226587_37_37)

trigger konflux build a new snapshot

---

README.md

Update doc about quota limiters

Update doc about quota limiters

---

docs/openapi.json
ols/version.py
scripts/build-container.sh

update version to 1.0.1. prepare for new release.
- Closes #

OLS-1857: set version to 1.0.1

---

ols/src/tools/tools.py
tests/unit/tools/test_tools.py

Disallow specific args in tools
- Closes #

OLS-1797: Disallow specific args in tools

---

ols/src/tools/tools.py
tests/unit/tools/test_tools.py

Execute tools in parallel
- Closes #

OLS-1407: Execute tools in parallel

---

Makefile
tests/config/operator_install/olsconfig.crd.watsonx_byok1.yaml
tests/config/operator_install/olsconfig.crd.watsonx_byok2.yaml
tests/e2e/pytest.ini
tests/e2e/test_query_endpoint.py
tests/e2e/utils/ols_installer.py
tests/scripts/test-e2e-cluster-periodics.sh
tests/scripts/test-e2e-cluster.sh
tests/scripts/test-evaluation.sh
tests/scripts/utils.sh

- Added BYOK test suites
- Test case to check prioritization [OLS-1876](https://issues.redhat.com/browse/OLS-1876)
- Additionally refactor the test set up script to easily add new suites.

e2e: additional config test - refactoring + byok

---

docs/openapi.json
ols/version.py
scripts/build-container.sh

- Related Issue # https://issues.redhat.com/browse/OLS-1954
- Closes #

OLS-1954: Bump to version 1.0.3

---

ols/app/endpoints/ols.py
ols/app/endpoints/streaming_ols.py
ols/src/query_helpers/docs_summarizer.py

Functionality has been added to improve the structuring/formatting of the logs. New data is also being called in and structured to provide more insights.
- Related Issue [# [OLS-1769](https://issues.redhat.com//browse/OLS-1769) ](Enhance "verbosity" of logging at INFO level for conversations)
- Closes #
Requests can be sent to the OLS service, either locally or through cluster and the logs of conversations can be tested.
Queries were put in for the llm and responses were inspected for structure and information.
LLM query
Tool Calling

OLS-1769 - Enhance "verbosity" of logging at INFO level for conversations

---

pdm.lock
pyproject.toml

Bump langchain packages
- Closes #

OLS-2069: Bump langchain packages

---

CLAUDE.md

Adds a CLAUDE.md, which Claude code reads by default, detailing this project's coding standards and practices.
N/A
N/A
N/A

adds standards and practices for Claude to follow
