- modules/task_processor.py
- modules/yaml_generator.py
> Improve yaml gen prompt to ensure only single yaml object response

- Containerfile
With the integration of gradio into fastapi and moving into modules directory, the ./gradio dir no longer exists so it needs to be removed from the Containerfile definition.
- Closes #
> Fix Containerfile looking for legacy ./gradio folder

- Makefile
- scripts/transform_coverage_report.py
Converting python code coverage report to GO coverage.out format that is consumed by PROW. Because currently PROW only supports GO coverage report and more details on its [parsing logic](https://github.com/kubernetes/test-infra/blob/master/gopherage/cmd/html/static/parser.ts#L172)
Docs on spyglass reads coverage files: https://docs.prow.k8s.io/docs/spyglass/#example-configuration
Code pointers:
* https://github.com/openshift/release/blob/c472a857643c0f6f479bf1cecce0e9f3b9199693/core-services/prow/02_config/_config.yaml#L147-L152
* https://github.com/openshift/release/blob/c472a857643c0f6f479bf1cecce0e9f3b9199693/core-services/prow/02_config/_config.yaml#L157-L160
- Related Issue: https://issues.redhat.com/browse/OLS-48 
Tested and verified in local. Preview
```
mode: set …
```
> Adding coverage transformer for PROW

- src/query_helpers/yes_no_classifier.py
- tests/mock_classes/llm_chain.py
- tests/unit/query_helpers/test_yes_no_classifier.py
- utils/logger.py
Creates a first example of how to test our internal modules.
* yes_no_classifier test, an extremely basic one
* mock class for LLMChain which is used by all our modules - takes an argument to simulate whatever response you want to guarantee so that you can base your tests off of it
* fixes a bug in the Logging class
* fixes a bug in the yes_no_classifier
N/A
`make test` succeeded.
> Unit test skeleton for our internal modules

- src/cache/cache.py
- src/cache/cache_factory.py
- src/cache/in_memory_cache.py
- src/cache/redis_cache.py
- tests/unit/test_cache_factory.py
- `Cache` class in separate source file to avoid cycles during import
- Fixed type hints - now `RedisCache` and `InMemoryCache` are really inherited from `Cache`
- That fixed `CacheFactory.conversation_cache` type issue
- Two new unit tests for `CacheFactory` to check the behaviour
- Partially tested by unit tests (`InMemoryCache`)
- Added two new unit tests for `CacheFactory` too
> Refactor cache and correct type hints

- default.env
- requirements.txt
- src/llms/llm_loader.py
- src/llms/requirements.txt
- utils/logger.py
Abstracts the way we instantiate llms to a single module.
This needs a lot of followup work.
1) nothing is leveraging this to instantiate the LLMs at runtime
2) the configuration of the loader is lacking (e.g. you can't load multiple models per provider)
but this needs to get landed so I can include it when i land my config work.
Replaces https://github.com/openshift/lightspeed-service/pull/36 because William is on PTO and i don't want to sit on his PR over the break.
- Closes #
> introduce llm loader abstraction

- src/ui/gradio_ui.py
During response payload retrieval and deserialization, any JSON deserialization exception can be thrown. We don't know/care which JSON library is used (it can be `simplejson` or `json`), but luckily for us, the ancestor of such exceptions is `ValueError`. So all we have to, is to catch this one.
- Integration tests are not available right now
> Catch JSON deserialization error for payload reading

- utils/logger.py
Fix: log file size must be number, not a string
How to check (using the same class `RotatingFileHandler` as in sources):
```bash
export LOG_FILE_SIZE=1234
```
```python
import os
from logging.handlers import RotatingFileHandler
logfile_maxSize = os.getenv("LOG_FILE_SIZE", (1048576 * 100))
print(logfile_maxSize, type(logfile_maxSize))
1234 <class 'str'>
RotatingFileHandler("some file", maxBytes=logfile_maxSize)
```
Throws/raises:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib/python3.8/logging/handlers.py", line 146, in __init__
if maxBytes > 0:
TypeError: '>' not supported between instances of 'str' and 'int'
```
- Set the enviromnent variable `LOG_FILE_SIZE` and run the code
> Fix: log file size must be number, not a string

- src/ui/gradio_ui.py
- tests/integration/test_ols.py
Use proper HTTP protocol-related constants instead of magic constants
It will be checked by linters soon
- The change is also part of integration tests, so will be tested itself ;)
> Use proper HTTP protocol-related constants instead of magic constants

- pyproject.toml
Linters are able to detect some old and now non-standard patterns in the code. In order to do this its need to know the target Python version. So let's start with Python 3.11 as documented.
- Will be done on CI
- You can use `make verify` as usual
> Verify project sources with Python 3.11 expected idioms

- app/endpoints/ols.py
- app/main.py
- app/models/config.py
- pyproject.toml
- src/cache/cache_factory.py
- src/docs/docs_summarizer.py
- src/llms/llm_loader.py
- src/query_helpers/happy_response_generator.py
- src/query_helpers/question_validator.py
- src/query_helpers/yaml_generator.py
- src/query_helpers/yes_no_classifier.py
- tests/integration/test_ols.py
- tests/unit/test_cache_factory.py
- utils/config.py
- Imports statements are sorted according to common Python standards (see below)
- Added new linter rule, so `make verify` will check for this problem
This rule is derived from the **isort** linter.
De-duplicates, groups, and sorts imports based on the provided `isort` settings.
Consistency is good. Use a common convention for imports to make your code
more readable and idiomatic.
```python
import pandas
import numpy as np
```
Use instead:
```python
import numpy as np
import pandas
```
- To be performed on CI
> Imports statements are sorted + added new linter rule

- Makefile
Help in Makefile shown using `make help` phony target:
```$ make help
Usage: make <OPTIONS> ... <TARGETS>
Available targets are:
images                    Build container images
install-deps              Install all required dependencies needed to run the service
install-deps-test         Install all required dependencies needed to test the service
run                       Run the service locally
test                      Run all tests
test-unit                 Run the unit tests
test-integration          Run integration tests tests
format                    Format the code into unified format
verify                    Verify the code using various linters
help                      Show this help screen
```
- Just use `make help` from CLI
> Help in Makefile shown using `make help` phony target

- scripts/transform_coverage_report.py
Prevent double call of `file.close()`
Actually Python ignores this call for already closed file, i.e. exception is not raised. But it is not correct to call close two times.
- N/A, not covered by tests
> Prevent double call of `file.close()`

- src/query_helpers/question_validator.py
Use explicit kwarg (with default) instead of plain **kwargs. Once there is a need to make the `LLMChain` indirectly configurable via **kwargs, those should be passed directly to it (and documented in docstring) to avoid unnecessary complexity.
- Closes #
> Use explicit verbose kwarg in question validator

- .gitignore
- Makefile
- New Makefile target to export code coverage report into interactive HTML
- It can then be viewed locally
- No need to export the resulting HTML
- Run `make coverage-report` on CLI
> Ability to export coverage report into interactive HTML

- app/models/config.py
- utils/config.py
- Integer values should be really converted into integers
- It will make the failure on the right place (during init+setup), not later
- Try to set incorrect env. variable value and see...
> Integer values should be really converted into integer

- pyproject.toml
- src/constants.py
Really check line length on CI
The max.length has been set for CI not to fail for this moment.
- Related Issue #OCP-83
- Done on CI or during `make verify`
> Really check line length on CI

- tests/unit/query_helpers/test_question_validator.py
- tests/unit/query_helpers/test_yes_no_classifier.py
- tests/unit/test_cache.py
- tests/unit/test_cache_factory.py
…ests
Added proper docstrings (that can be linted) into all existing unit tests
- Ruff with `[D]` rules enabled can do it: `ruff tests/unit`
> Added proper docstrings (that can be linted) into all existing unit tests

- tests/integration/test_feedback.py
- tests/integration/test_ols.py
Docstrings in all integration tests
- Ruff with `[D]` rules enabled can do it: `ruff tests/unit`
> Docstrings in all integration tests

- tests/mock_classes/__init__.py
- tests/mock_classes/langchain_interface.py
- tests/mock_classes/llm_chain.py
- tests/mock_classes/llm_loader.py
Docstrings in all mocks classes
- Ruff with `[D]` rules enabled can do it: `ruff tests/unit`
> Docstrings in all mocks classes

- tests/unit/utils/test_logger.py
`pathlib` offers a high-level API for path manipulation, as compared to
the lower-level API offered by `os`. When possible, using `Path` object
methods such as `Path.joinpath()` or the `/` operator can improve
readability over the `os` module's counterparts (e.g., `os.path.join()`).
- [Python documentation: `PurePath.joinpath`](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.joinpath)
- [Python documentation: `os.path.join`](https://docs.python.org/3/library/os.path.html#os.path.join)
- [PEP 428](https://peps.python.org/pep-0428/)
- [Correspondence between `os` and `pathlib`](https://docs.python.org/3/library/pathlib.html#correspondence-to-tools-in-the-os-module)
- [Why you should be using pathlib](https://treyhunner.com/2018/12/why-you-should-be-using-pathlib/)
- [No …
> Use Path module

- ols/app/models/config.py
- ols/src/indexer/indexer.py
- ols/src/llms/llm_loader.py
- ols/utils/config.py
- Don't need to use aliases during import
Using the `from` keyword to import the submodule is more concise and
readable.
- N/A
> Don't need to use aliases during import

- ols/src/docs/docs_summarizer.py
- ols/src/llms/llm_loader.py
- ols/src/query_helpers/happy_response_generator.py
- ols/src/ui/gradio_ui.py
Don't need to call `str` inside f-strings
f-strings support dedicated conversion flags for these types, which are
more succinct and idiomatic. In many cases, calling `str()` within an f-string is
unnecessary and can be removed entirely, as the value will be converted
to a string automatically,
- [ x PR has passed all pre-merge test jobs.
> Don't need to call `str` inside f-strings

- tests/unit/query_helpers/test_question_validator.py
PoC: use patch instead of monkeypatch
> OLS-186: Use `@patch` instead of monkeypatch

- ols/src/cache/cache.py
- No `pass` for abstract methods
- Actually those methods have bodies - the docstring (it is regular expression)
- Unit test and integration test code coverage will be more precise (higher ;)
> OLS-186: No `pass` for abstract methods

- ols/app/endpoints/ols.py
This might seem to be tricky one, but this change helps a lot linters and other code analyzers. Those tools are unable to infer that there are only two states: valid and invalid. So they write an error that the function does not contains `return` or `raise` in all possible branches. This fix fixes it and make clear, that exception is raised in all conditions that are not strictly valid.
- Integration tests take this into case (at least partially)
> OLS-83: Fixed logic in invalid state checks

- pyproject.toml
No all docstrings are present in the code, so it is the right time to enable docstyle checks on CI and also during `make verify`. All what is needed is to enable all `D` rules in Ruff.
- Done on CI
- Use `make verify`
> OLS-83: Docstyle checks on CI

- tests/mock_classes/mock_llama_index.py
- tests/mock_classes/mock_query_engine.py
- tests/mock_classes/mock_summary.py
- tests/unit/docs/test_doc_summarizer.py
- Docs sumarizer unit tests + required mock objects
- Actually the DocsSummarizer just call several constructors and methods in top-down approach w/o any control flow. So it is hard to actually test it's correct behavior (probably with better mocks later?). I'd suggest to have better integration tests instead.
- Unit tests on CI
> OLS-186: Docs summarizer unit tests

- ols/src/query_helpers/yaml_generator.py
- ols/utils/logger.py
It is now required (PEP-484) that all optional types need to be specified explicitly.
Additionally, log level can be specified as int or as string
This PR fixes some errors reported by mypy/Pyright
- Use mypy or Pyright
> OLS-83: Specify optional types where it is needed

- tests/mock_classes/langchain_interface.py
- tests/mock_classes/llm_chain.py
- tests/mock_classes/llm_loader.py
- tests/mock_classes/mock_llama_index.py
- tests/mock_classes/mock_query_engine.py
- tests/mock_classes/mock_summary.py
- tests/mock_classes/redis.py
[OLS-83](https://issues.redhat.com//browse/OLS-83): Use imperative mood in mock classes: according PEP 257
This will allow us to enable the last missing docstyle check: D401
- Closes #
- N/A
> OLS-83: Use imperative mood in mock classes: according PEP 257

- tests/unit/utils/test_logger.py
Logging unit tests are affected by environment variables such as `LOG_LEVEL`. 
These env vars can come from the `.env` file for local testing. Renaming the `.env` file everytime we run the unit test is not convenient. 
This patch on the logger unit test will set `LOG_LEVEL` per test case. 
So we can run the unit tests without restoring the env vars and `.env` file. 
None
> clean env vars before logging unit test

- ols/src/llms/llm_loader.py
- tests/unit/llms/test_llm_loader.py
- Improved improper LLM model configuration checks. Specific exceptions are much better than bare `Exception` and can be decided later. Even in unit tests it's better to check which condition occurs (because errors in unit tests itself will raise `Exception` so it's tricky to catch them).
- Added some logging too.
- And checked by new unit tests
- `make test-unit` will do the trick
> OLS-83: Improved improper LLM model configuration checks

- ols/src/llms/llm_loader.py
We are not able to send question to OpenAI model. This is due to an invalid parameter for ChatOpenAI has been passed. We are not updating any parameters for OpenAI with this fix. We have to see if there is a need to do override and then make a better way to ensure that the passed parameters are valid for specific model.
- Related Issue [OLS-211](https://issues.redhat.com/browse/OLS-211)
> OLS-211: Removed LLMLoader param override for OpenAI

- pyproject.toml
Finally we have 'clean' docstrings everywhere! So it's possible to enable the last docstrings-related check D401. That one needs to be enabled explicitly in Ruff.
- See CI
- Use `make verify` - everything should be fine
> OLS-83: Enable D401 check on CI

- tests/unit/query_helpers/test_yes_no_classifier.py
Use `@patch` in unit tests for yes-no classifier
- Look at CI
- Use `make test-unit`
> OLS-83: Use @patch in unit tests for yes-no classifier

- tests/unit/query_helpers/test_yaml_generator.py
[OLS-83](https://issues.redhat.com//browse/OLS-83): Use `@patch` it test-yaml-generator
- Look at CI
- Use `make test-unit`
> OLS-83: Use `@patch` it test-yaml-generator

- ols/constants.py
We have constants, let's use them.
Merge after https://github.com/openshift/lightspeed-service/pull/148
> OLS-155: Use constants in prompt template

- default.env
- ols/app/main.py
- ols/app/models/config.py
- ols/utils/config.py
Enabling `/ui` via env is broken now. There are three different envs in different parts of the code that should do the trick and enable the ui. 
```
OLS_ENABLE_UI=false
ENABLE_DEBUG_UI=false
ENABLE_DEV_UI=true
```
but just `ENABLE_DEV_UI` is actually used for configuration.
We should fix this regardless of [config refactoring PR](https://github.com/openshift/lightspeed-service/pull/166).
> Fix enabling dev ui via env

- CONTRIBUTING.md
- Makefile
- pyproject.toml
- requirements-test.txt
[OLS-153](https://issues.redhat.com//browse/OLS-153): Ability to perform type checks from CLI
Note: it is not part of `make verify` on purpose because type checks are very slow + the code has just few type hints (need be updated step-by-step later)
- Related Issue #[OLS-153](https://issues.redhat.com//browse/OLS-153)
- Install Mypy + run `make check-types`
> OLS-153: Ability to perform type checks from CLI

- ols/src/llms/llm_loader.py
Added missing type info for all LLM constructors
- Related Issue #[OLS-153](https://issues.redhat.com//browse/OLS-153)
- Use `make check-types`
> OLS-153: Added missing type info for all LLM constructors

- Makefile
- tests/e2e/pytest.ini
- tests/e2e/test_api.py
Experiment with testing the api server end to end (i.e. with backend llm invocation).
Note: refactors the generic `/raw_prompt` endpoint slightly because the existing code was insufficiently agnostic about the LLM instance (llmloader returns a `ChatOpenAI` instance for openai and a `LangChainInterface` for BAM, these two types have different invocation parameter expectations.  The Langchain wrapper seems to resolve this but it's an area to keep an eye on as langchain has fundamentally distinct concepts of "chat" vs "generation" invocations, even if the backend LLMs don't have distinct api endpoints)
Currently this PR only passes e2e testing for openai because when used with the BAM models, the models are returning a truncated response for question validation.  This isn't a failure of the …
> Initial skeleton for e2e testing with live OLS instance + real llm backend

- CONTRIBUTING.md
Doc update: An example how 'raises:' should be written in docstrings
- N/A
> Doc update: An example how 'raises:' should be written in docstrings

- ols/app/models/config.py
- ols/constants.py
- tests/unit/test_app_endpoints.py
- tests/unit/test_models.py
- tests/unit/utils/test_app_utils.py
This PR improves unit test coverage of ols.app module.
The current coverage is 90%+ for ols.app module and 90% overall.
- Related Issue [OLS-185](https://issues.redhat.com//browse/OLS-185), [OLS-89](https://issues.redhat.com//browse/OLS-89)
- Closes [OLS-185](https://issues.redhat.com//browse/OLS-185)
> OLS-185: improve unit test coverage of ols.app module.

- tests/unit/ui/test_gradio_ui.py
(Trivial) Use lowercase local vars
[PEP 8] recommends that all function variables use lowercase names:
> Function names should be lowercase, with words separated by underscores as necessary to
> improve readability. Variable names follow the same convention as function names. mixedCase
> is allowed only in contexts where that's already the prevailing style (e.g. threading.py),
> to retain backwards compatibility.
- N/A
> (Trivial) Use lowercase local vars

- ols/src/llms/llm_loader.py
- tests/unit/llms/test_llm_loader.py
Contains two commits:
- Custom errors class naming is formatted according to google's standards.
- Adds parent configuration error to make catching these errors easy on the endpoint side (except just parent instead of 5 different ones.)
- the assumption here is that all those errors are the same from the user's perspective -> 422 unprocessable entity
> OLS-40: Llm loader parent error

- .github/dependabot.yml
DependaBot is a tool provided by Github that can check for dependencies needed updates and upgrade and automate the management of it, for that i have added the config of Dependabot to the project so it can get enabled.
- Closes #[OLS-85](https://issues.redhat.com//browse/OLS-85)
to test the changes without merging them, you will need them to persist in a fork, so you can see a Dependabot job has been started successfully.
i have tested the config on my own fork, and it did scheduled a Dependabot job that analyzed the entire project dependencies
> added config for weekly dependency checks for dependabot

- ols/src/llms/llm_loader.py
- tests/unit/llms/test_llm_loader.py
This is a small step towards [OLS-233](https://issues.redhat.com/browse/OLS-233).
I've removed the parametrized test (as it was testing the same thing) and added new tests instead.
Watson loader seems to be incompatible a bit with the rest of the LLMLoader code. I can't peek around because I don't have credentials for it (or BAM).
Merge after https://github.com/openshift/lightspeed-service/pull/199
> OLS-233: Llmloader unify error handling

- tests/unit/llms/test_llm_loader.py
Use lowercase local vars in LLM loader tests
[PEP 8] recommends that all function variables use lowercase names:
> Function names should be lowercase, with words separated by underscores as necessary to
> improve readability. Variable names follow the same convention as function names. mixedCase
> is allowed only in contexts where that's already the prevailing style (e.g. threading.py),
> to retain backwards compatibility.
- N/A
> Use lowercase local vars in LLM loader tests

- pyproject.toml
Enable more linters for `make verify` and for CI
- Clone upstream, switch to main branch and run `make verify`
> Enable more linters for `make verify` and for CI

- tests/unit/query_helpers/test_question_validator.py
- tests/unit/query_helpers/test_yes_no_classifier.py
- tests/unit/test_cache_factory.py
Unit tests improvements: exception checks should not be too broad.
`pytest.raises(Exception)` etc. will catch any `Exception` and may catch errors that are
unrelated to the code under test. To avoid this, `pytest.raises` should be called with a `match` parameter.
- `make test-unit`
> Unit tests improvements: exception checks should not be too broad

- ols/src/query_helpers/__init__.py
- ols/src/query_helpers/question_validator.py
- ols/src/query_helpers/yaml_generator.py
- ols/src/query_helpers/yes_no_classifier.py
- tests/unit/query_helpers/test_query_helper.py
- tests/unit/query_helpers/test_question_validator.py
- tests/unit/query_helpers/test_yaml_generator.py
- tests/unit/query_helpers/test_yes_no_classifier.py
This PR unifies the query helpers interface. If there is a need to configure provider/model per helper, we can still do something like this at the place where it's initialized (in ols endpoint now). 
```python
If config.yaml_provider:
yaml_gen = YamlGenerator(provider=config.yaml_provider, …)
```
Allows dependency injection in tests.
The `camel_to_snake` is there only to ensure the same logger name as before (it will be refactored eventually).
> Add QueryHelper parent

- tests/unit/test_config.py
Use more idiomatic `pytest.fail()` instead of `assert False`
- CI should still pass
> Use more idiomatic `pytest.fail()` instead of `assert False`

- tests/unit/test_config.py
Use `type` in Python 3.9 or above
> Use `type` in Python 3.9 or above

- ols/utils/config.py
- tests/unit/test_config.py
Raise exception when config file is missing - because in such situation the UI, REST API server etc. won't start properly either
- On CI or using `make test-unit`
> Raise exception when config file is missing

- requirements-test.txt
This fix a dependency conflict caused by `urllib3` : 
* latest version of  `types-requests` requires `urllib3 2.10` 
* ibm-cos-sdk-core 2.13.3 requires urllib3<1.27,>=1.26.18
Lowering the version of `type-requests` makes both packages accept the same version of `urllib3`. 
- Closes #
> pin package types-requests<2.31.0.7

- ols/src/query_helpers/query_docs.py
Fix: `VectorDB` parameter is not optional
> Fix: `VectorDB` parameter is not optional

- ols/app/models/config.py
- ols/utils/config.py
- tests/unit/test_models.py
Refactoring: don't use method name from superclass
> Refactoring: don't use method name from superclass

- ols/src/query_helpers/docs_summarizer.py
Fix error: `response` is string already
> Fix error: response is string already

- ols/src/query_helpers/query_docs.py
Update QueryDocs docstring
- Remove uneccesary types.
- Updates the code block example.
The original is a directive from reStructuredText (reST), which is often used in Python docstrings to provide richer formatting.
However, the more common convention in Python docstrings is to use triple backticks (```) for code blocks, as this is the syntax used by Markdown and it's also compatible with many tools that generate documentation from docstrings, like Sphinx and pydoc.
It also doesn't work with IDE preview
> Update QueryDocs docstring

- ols/app/models/config.py
- tests/config/config_without_logging.yaml
- tests/unit/test_config.py
- tests/unit/test_models.py
- Previously the code "accepts" config with missing logging info, but then fail on the first call of any log method
- Now default logging level will be used
- Unit tests and integration tests should pass
> Use default logging level if nothing is specified in config file

- ols/utils/logging.py
Setting logging level for other libs that pops up when logging is set to debug.
For context, with the previous logging implementation, those were silenced (IRC correctly) as we were not configuring the root logger.
Some examples
`2024-01-26 15:08:09,670 [langchain_community.chat_models.openai:openai.py:255] WARNING: WARNING! frequency_penalty is not default parameter.`
`2024-01-26 15:08:13,809 [openai:util.py:60] DEBUG: message='OpenAI API response' path=https://api.openai.com/v1/chat/completions processing_ms=88 request_id=41bb9…`
`2024-01-26 15:07:05,235 [fsspec.local:local.py:294] DEBUG: open file: /home/ometelka/projects/lightspeed-service/vector-db/ocp-product-docs/docstore.json`
`2024-01-26 15:09:17,906 [llama_index.storage.kvstore.simple_kvstore:simple_kvstore.py:74] DEBUG: Loading …
> Configure logging for other libraries

- ols/app/models/config.py
Use standard `dict`, not `types.Dict`
> Use standard `dict`, not `types.Dict`

- ols/app/endpoints/ols.py
- tests/unit/test_app_endpoints.py
conversation id when given empty string , it goes to the preexisting conversation id flow.
Fixed by checking for empty string . 
- Closes #
> fix empty conversation_id

- examples/olsconfig.yaml
Adds gpt turbo model to example config.
What would be the best approach here?
1. have all models that we allow (as we probably don't want to allow some, eg. gpt-4-vision-preview) listed in the example config
2. leave it to user - user needs to change default_model as well as make sure the model is listed under the correct provider
WDYT?
> Add gpt model to example config

- ols/app/endpoints/health.py
Missing return type in health endpoints handlers
> Missing return type in health endpoints handlers

- ols/app/endpoints/ols.py
- ols/src/cache/cache.py
- ols/src/cache/in_memory_cache.py
- ols/src/cache/redis_cache.py
- tests/e2e/test_api.py
- tests/integration/test_ols.py
- tests/unit/test_app_endpoints.py
- tests/unit/test_in_memory_cache.py
- tests/unit/test_redis_cache.py
- Keys to cache must contain user ID
- Requirements: Access to the conversation history must be based on user identity plus conversation uid so that users can’t guess someone else’s conversation uid and retrieve their conversation history.
- Now we don't (yet) have the user identity code built-in (see #267), but we can update existing code in advance. Later just one line would need to be changed (marked as `TODO` in this PR)
- Related Issue #[OLS-109](https://issues.redhat.com//browse/OLS-109)
- Both unit tests and integration tests checks the behaviour
> OLS-109: Keys to cache must contain user ID

- requirements.txt
> Pin Pydantic to version 2.6.0

- ols/app/endpoints/ols.py
- ols/app/models/models.py
- ols/src/ui/gradio_ui.py
- tests/integration/test_ols.py
- tests/unit/app/endpoints/test_ols.py
Adds provider and model to llm request.
Prerequisites:
- Start app `make run`, visit the `/ui`, and provide values (or not) to provider/model fields.
- or do posts to `/query` endpoint directly
> OLS-40: Add provider and model to llm request

- tests/integration/test_liveness_readiness.py
- tests/integration/test_ols.py
Refactoring: separate elementary REST API endpoints from OLS-related endpoints
- On CI, integration tests
> OLS-201: Refactoring: separate elementary REST API endpoints from OLS-related endpoints

- ols/app/main.py
Fix: No linefeed in OpenAPI JSON. That string is passed directly into OpenAPI endpoint, including all linefeeds etc. It makes it unreadable.
- Run the service and access `/openapi.json`
> OLS-201: Fix: No linefeed in OpenAPI JSON

- ols/app/endpoints/feedback.py
- ols/app/models/models.py
- tests/integration/test_feedback.py
- tests/unit/test_app_endpoints.py
- tests/unit/test_models.py
Fix: conversation ID is a string, not a number
- Both unit tests and integration tests was updated
> OLS-201: Fix: conversation ID is a string, not a number

- tests/unit/app/models/__init__.py
- tests/unit/app/models/test_config.py
- tests/unit/app/models/test_models.py
- tests/unit/utils/test_config.py
Just moving tests around to reflect the main package (unit tests should mirror that).
As we have modules with the same name, we need to have some __init__.py in tests, to avoid tests naming collision.
No code is changed here.
> OLS-157: Proper distribution of models unit tests

- ols/app/endpoints/ols.py
- ols/src/query_helpers/docs_summarizer.py
- tests/unit/docs/test_doc_summarizer.py
Pass conversation history to docs summarizer
- Related Issue #[OLS-109](https://issues.redhat.com//browse/OLS-109)
- Closes #[OLS-109](https://issues.redhat.com//browse/OLS-109)
- Unit tests and integration tests. Also can be run via curl/from UI
> OLS-109: Pass conversation history to docs summarizer

- ols/app/main.py
$ make run
uvicorn ols.app.main:app --reload --port 8080
INFO:     Will watch for changes in these directories: ['/home/bparees/git/gocode/src/github.com/openshift/lightspeed-service']
INFO:     Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:     Started reloader process [1009276] using StatReload
2024-01-31 14:48:40,144 [ols.app.main:main.py:24] INFO: Config loaded from olsconfig.yaml
2024-01-31 14:48:40,144 [ols.app.main:main.py:30] INFO: Embedded Gradio UI is disabled. To enable set enable_dev_ui: true in the dev section of the configuration file
INFO:     Started server process [1009278]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
- Closes #
- Please provide detailed steps to perform tests related to this …
> Log where we loaded the config file from

- tests/unit/app/models/test_config.py
Unit tests: missing credentials in config
> OLS-89: Unit tests: missing credentials in config

- tests/unit/app/models/test_config.py
- Unit tests: checking dark corners of config loading
- Refactored some existing checks to use `with raises(math="")`
> OLS-89: Unit tests: checking dark corners of config loading

- tests/integration/query_helpers/test_query_docs.py
The fixture setup_faiss is not deterministic in tests.
It either loads documents from a local store or uses predefined "fake" docs.
The switch condition does not check if the actual .index exists, just if there is a directory where it should live. This can lead to RuntimeError when running integration tests.
I've run the tests several times either by loading local index, or initializing using docs defined in the `list_of_documents`. The execution time is the same.
This PR removes the switch to ensure the fixture returns every time the same result (docs we create in tests).
> OLS-269: Always initialize index from test docs

- ols/src/cache/cache.py
- tests/unit/cache/test_in_memory_cache.py
- tests/unit/cache/test_redis_cache.py
In Redis, usually `:` is used as a separator for compound key. + make the code more readable by reducing magic constants.
> Standard compound key separator

- ols/app/endpoints/feedback.py
- ols/app/endpoints/health.py
- ols/app/endpoints/ols.py
- ols/app/models/models.py
- ols/src/query_helpers/docs_summarizer.py
- tests/e2e/test_api.py
- tests/integration/test_feedback.py
- tests/integration/test_liveness_readiness.py
- tests/integration/test_ols.py
- tests/unit/app/__init__.py
- tests/unit/app/endpoints/__init__.py
- tests/unit/app/endpoints/test_feedback.py
- tests/unit/app/endpoints/test_health.py
- tests/unit/app/endpoints/test_ols.py
- tests/unit/app/models/test_models.py
- tests/unit/docs/test_doc_summarizer.py
Adds request/response models for all endpoints.
I've removed the query from the response. It should be possible to track it via conversation_id. In theory, it might be a bit difficult to put those together in asynchronous scenarios, but hard to tell if it can happen.
I would like to hold it until https://github.com/openshift/lightspeed-service/pull/281 (don't want to fix tests that will be removed right after).
> OLS-157: Ensure endpoints have in/out models

- ols/src/cache/cache_factory.py
Fix comment: we don't use env.vars anymore
> Fix comment: we don't use env.vars anymore

- tests/unit/llms/test_llm_loader.py
I'm genuinely confused about this one. It fails on me locally, but it seems ok in CI.
Still, these tests seem to be obsolete.
There is no validation logic in `LLMLoader` regarding checking if there is an API key set.
Such validation should happen when the config is created, so it should fail on `config.init_config("tests/config/empty_openai_api_key.yaml")`, not when initializing `LLMLoader`.
Also, I can't find the place that actually raises an error with `"Did not find openai_api_key"`.
> Remove obsolete tests

- ols/src/ui/gradio_ui.py
- Closes # https://issues.redhat.com/browse/OLS-295
Before this fix, with logging_config.lib_log_level = debug, the following was logged:
$ uvicorn ols.app.main:app --reload --port 8080
INFO:     Will watch for changes in these directories: ['/home/syedriko/lightspeed-service']
INFO:     Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
INFO:     Started reloader process [40964] using StatReload
2024-02-07 23:25:51,539 [ols.app.main:main.py:29] INFO: Config loaded from /home/syedriko/lightspeed-service/olsconfig.yaml
2024-02-07 23:25:51,541 [httpx:_config.py:78] DEBUG: …
> OLS-295: Disable Gradio analytics

- ols/constants.py
- ols/src/query_helpers/docs_summarizer.py
- Added user query to the summarizer's prompt
- Removed embeddings' metadata from the summarizer's prompt
- "Referenced documents" in the summarizer's response are now OCP doc URLs
- Related Issue 
- Closes # https://issues.redhat.com/browse/OLS-268
For the following query:
$ curl -X 'POST' 'http://127.0.0.1:8080/v1/query' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{"query": "What is the NFD operator?"}'
the following request is sent to the LLM (note no file_path metadata):
2024-02-07 14:35:40,113 [openai._base_client:_base_client.py:439] DEBUG: Request options: {'method': 'post', …
> OLS-268: RAG: in OLS responses, support deep links into the OCP docs

- ols/src/llms/llm_loader.py
- pdm.lock
- pyproject.toml
langchain-community is deprecated for use with ChatOpenAI
- Closes #
> Switch to langchain-openai dep instead of langchain-community

- CONTRIBUTING.md
- Makefile
- ols/app/endpoints/ols.py
Overall code coverage computation.
We had a discussion with @syedriko that it would be useful to know code coverage for both unit tests and integration tests. It is logical as we don't want to cover literally everything from unit tests and in some cases it is not even possible (`ols/app/main.py` for example). On other hand we don't want to repeat the same checks in integration tests just to have nice code coverage (`config.py`). And additionally the overall code coverage might be very near 100% - and any part not covered is either dead code or our testing is not complete.
This is how the overall code coverage look like today. It is clear that some parts of `llm_loader.py` is not tested at all. And it is not a coincidence that this is most problematic part of our codebase:
```
Name …
```
> Overall code coverage computation

- ols/app/endpoints/ols.py
- Return response immediatelly to avoid type confusion
- Identifier `llm_response` was used in two context (totally different). That causes type checkers to identify type errors that were forcefully ignored by `#type ignore` comment. It is not needed now.
> OLS-254: Return response immediatelly to avoid type confusion

- tests/unit/app/endpoints/test_ols.py
Proper test for conversation ID from response
> OLS-254: Proper test for conversation ID from response

- ols/app/endpoints/ols.py
- ols/app/models/models.py
- ols/src/query_helpers/docs_summarizer.py
- tests/e2e/test_api.py
- tests/integration/test_ols.py
- tests/unit/app/endpoints/test_ols.py
- tests/unit/app/models/test_models.py
LLMResponse now includes a list of URLs for the embedding documents used to generate the response
- Closes # https://issues.redhat.com/browse/OLS-305
> OLS-305: Make LLMResponse include URLs for the embedding documents used to generate the response

- ols/app/endpoints/ols.py
- tests/unit/app/endpoints/test_ols.py
Refactor: retrieve previous input
+ new unit tests
> OLS-254: Refactor: retrieve previous input

- tests/e2e/test_api.py
checks to see that the response references some RAG content.  This confirms:
1) we are looking up related context information from the RAG db
2) we are returning the refs as part of the api response
- Closes #
> Add an e2e for rag content

- ols/app/endpoints/ols.py
- ols/app/models/models.py
- ols/src/query_helpers/docs_summarizer.py
- tests/e2e/test_api.py
- tests/integration/test_ols.py
- tests/integration/test_ols_debug.py
- tests/unit/app/endpoints/test_ols.py
- tests/unit/app/models/test_models.py
- tests/unit/docs/test_doc_summarizer.py
Truncating flag to be returned in response.
This need changes in model, changes in DocsSummarizer etc.
The trunsation itself is not implemented there. This is 1st step to avoid having huge PR that will need to be constantly rebased.
> OLS-58: Truncating flag to be returned in response

- .gitignore
- Containerfile
- Containerfile.rag
- Makefile
- examples/olsconfig.yaml
- ols/app/models/config.py
- ols/src/query_helpers/docs_summarizer.py
- ols/src/ui/gradio_ui.py
- scripts/download_embeddings_model.py
- tests/unit/utils/test_config.py
- Added ols_config.reference_content.embeddings_model_path to configuration to store the path to the embeddings model. If this path is specified, the OLS expects to find the embeddings model in that directory. Otherwise, the behavior is as before, the model is downloaded from HuggingFace on-demand and is cached locally.
- For everyday development, added `get-rag` make target that downloads both the embeddings model and database to the local directories.
- Added the embeddings model to the RAG'ged image via Containerfile.rag
- Related Issue # https://issues.redhat.com/browse/OLS-52
- Closes # https://issues.redhat.com/browse/OLS-332
- How were the fix/results from this change verified? Please provide relevant …
> OLS-332: avoid on-demand downloading of the embeddings model from HuggingFace

- ols/src/llms/llm_loader.py
- ols/src/query_helpers/__init__.py
- ols/src/query_helpers/docs_summarizer.py
- ols/src/query_helpers/question_validator.py
- tests/integration/test_ols.py
- tests/unit/docs/test_doc_summarizer.py
- tests/unit/llms/test_llm_loader.py
- tests/unit/query_helpers/test_query_helper.py
- tests/unit/query_helpers/test_question_validator.py
This PR contains a responsibility shift.
The `QueryHelper` knows which provider/model (and parameters) wants to use. It is its responsibility to set the correct inputs for `LLMLoader`. 
Resolving if the combo is actually valid input is responsibility the `LLMLoader`. It gets what provider, model, and additional parameters for llm along with the config against which the values will be validated.
> OLS-233: Make provider/model required inputs for LLMLoader

- ols/app/main.py
- ols/app/metrics.py
[OLS-113](https://issues.redhat.com//browse/OLS-113): REST API durations in metrics
Histogram values looks like
```
response_duration_seconds_bucket{le="0.005",path="/openapi.json"} 6.0
response_duration_seconds_bucket{le="0.01",path="/openapi.json"} 6.0
response_duration_seconds_bucket{le="0.025",path="/openapi.json"} 6.0
response_duration_seconds_bucket{le="0.05",path="/openapi.json"} 6.0
response_duration_seconds_bucket{le="0.075",path="/openapi.json"} 6.0
response_duration_seconds_bucket{le="0.1",path="/openapi.json"} 6.0
response_duration_seconds_bucket{le="0.25",path="/openapi.json"} 6.0
response_duration_seconds_bucket{le="0.5",path="/openapi.json"} 6.0
response_duration_seconds_bucket{le="0.75",path="/openapi.json"} 6.0
response_duration_seconds_bucket{le="1.0",path="/openapi.json" …
```
> OLS-113: REST API durations in metrics

- examples/olsconfig.yaml
- ols/app/models/config.py
- ols/src/llms/llm_loader.py
- tests/config/singleprovider.e2e.template.config.yaml
- tests/e2e/test_api.py
- tests/unit/utils/test_config.py
As those serve for dev purposes, it is not necessary to do the validation of the actual values.
Also, this allows more configuration without the explicit need to handle dev params.
> OLS-233: Nest dev_config llm_params

- scripts/test-e2e-standalone.sh
we're starting to hit the existing timeout (1 min), which is concerning and 
needs investigation, but for now this should keep the e2e jobs from failing due
to OLS taking more than 1 min to start.
- Closes #
> Bump the ols e2e startup timeout

- ols/app/endpoints/health.py
- tests/mock_classes/mock_retrievers.py
No need to explicitly return `None` value which is more idiomatic in this code.
Python implicitly assumes `return None` if an explicit `return` value is
omitted. Therefore, explicitly returning `None` is redundant and should be
avoided when it is the only possible `return` value across all code paths
in a given function.
> No need to explicitly return None value

- ols/app/models/config.py
- ols/utils/config.py
- scripts/download_embeddings_model.py
- scripts/transform_coverage_report.py
Using `open` in text mode without an explicit encoding can lead to
non-portable code, with differing behavior across platforms.
> Use explicit encoding when working with files

- ols/app/models/config.py
- ols/src/query_helpers/query_docs.py
When testing for membership in a static sequence, it is better to use a `set` literal over a `list` or `tuple`, as Python optimizes `set` membership tests.
> Member testing using sets

- Makefile
- README.md
- runner.py
Ability to start service from Python script
- Related Issue #[OLS-311](https://issues.redhat.com//browse/OLS-311)
- Simply start the new script: `python runner.py`
> OLS-311: Ability to start service from Python script

- examples/openshift-lightspeed-tls.yaml
Added an example manifest under examples dir, that makes use of Service Serving certs that would enable TLS certs
trusted by Openshift internal communication.
which also being used by OLS itself (provide to uvicorn)
- Closes #
> ols-241: - add TLS supported Example openshift manifest

- examples/openshift-lightspeed-tls.yaml
using ports < 1024 requires special permission
- Closes #
> Use port 8443 for tls so special permissions aren't needed

- tests/unit/app/endpoints/test_ols.py
Unit test for `reduct_query` function (happy path that was not covered)
> Unit test for reduct_query function for no filters, one filter, and two filters

- pyproject.toml
To avoid warnings about deprecated settings:
```
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `pyproject.toml`:
- 'extend-select' -> 'lint.extend-select'
- 'ignore' -> 'lint.ignore'
- 'select' -> 'lint.select'
- 'flake8-pytest-style' -> 'lint.flake8-pytest-style'
- 'pydocstyle' -> 'lint.pydocstyle'
```
> Update ruff settings

- ols/app/models/config.py
Removed `return` statement for calls that returns nothing
> Removed return statement for calls that returns nothing

- ols/src/llms/__init__.py
Fix: `module` is different type (`Module`) than module name (`Path`)
> Fix: `module` is different type (`Module`) than module name (`Path`)

- ols/app/endpoints/ols.py
- ols/app/main.py
- ols/src/query_helpers/docs_summarizer.py
- ols/src/rag_index/__init__.py
- ols/src/rag_index/index_loader.py
- ols/utils/config.py
- tests/integration/test_ols.py
- tests/unit/docs/test_doc_summarizer.py
- tests/unit/rag_index/__init__.py
- tests/unit/rag_index/test_index_loader.py
As loading vector index takes time, load this once instead of with every query.
- Related Issue # [OLS-271](https://issues.redhat.com//browse/OLS-271)
- Closes #
> OLS-271: Load vector db once

- ols/app/endpoints/ols.py
- tests/unit/app/endpoints/test_ols.py
Disable question validation for follow-up questions.
> OLS-272:  Disable question validation for follow-up questions

- scripts/download_embeddings_model.py
On HF, the BAAI/bge-base-en embeddings model is stored in two formats: [pickle'd](https://docs.python.org/3/library/pickle.html) pytorch_model.bin and [model.safetensors](https://huggingface.co/docs/safetensors/en/index). model.safetensors is preferable as more secure, so delete pytorch_model.bin after download and make RAG data smaller by 418MB.
- Related Issue # https://issues.redhat.com/browse/OLS-332
- Closes #
> OLS-332: remove pytorch_model.bin, load the embeddings model from model.safetensors

- pdm.lock
- pyproject.toml
Pytest-asyncio is needed by unit tests
Without it, some tests will be skipped
Before this fix:
```
tests/unit/utils/test_auth_dependency.py:27
/home/ptisnovs/lightspeed-service/tests/unit/utils/test_auth_dependency.py:27: PytestUnknownMarkWarning: Unknown pytest.mark.asyncio - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
@pytest.mark.asyncio
tests/unit/utils/test_auth_dependency.py:52
/home/ptisnovs/lightspeed-service/tests/unit/utils/test_auth_dependency.py:52: PytestUnknownMarkWarning: Unknown pytest.mark.asyncio - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
@pytest.mark.asyncio
```
> Pytest-asyncio is needed by unit tests

- ols/src/llms/providers/openai.py
Bug fix: `top_p` and `frequency_penalty` are model kwargs
> Bug fix: top_p and frequency_penalty are model kwargs

- Containerfile.rag
This is a fix for Containerfile.rag so it can consume the Containerfile as updated in https://github.com/openshift/lightspeed-service/pull/485
- Related Issue # https://issues.redhat.com/browse/OLS-369
- Closes #
> OLS-369: fix for Containerfile.rag to work with the updated Containerfile

- ols/app/models/config.py
The Python documentation recommends the use of `object` to "indicate that a
value could be any type in a typesafe manner", while `Any` should be used to
"indicate that a value is dynamically typed."
The semantics of `__eq__` and `__ne__` are such that the `obj` parameter
should be any type, as opposed to a dynamically typed value. Therefore, the
`object` type annotation is more appropriate.
> Use `object` type instead of `Any`

- ols/src/query_helpers/docs_summarizer.py
- ols/src/query_helpers/question_validator.py
[OLS-364](https://issues.redhat.com//browse/OLS-364): `llm-loader` is not keyword argument
> OLS-364: `llm-loader` is not keyword argument

- ols/app/endpoints/ols.py
- ols/src/cache/cache.py
- tests/unit/app/endpoints/test_ols.py
- tests/unit/cache/test_in_memory_cache.py
- tests/unit/cache/test_redis_cache.py
Now we know that user ID is proper UUID. It means that compound key to Redis can be checked more thorougly.
- Related Issue #[OLS-378](https://issues.redhat.com//browse/OLS-378)
> OLS-378: Check for proper user UUID

- ols/src/query_helpers/question_validator.py
- tests/unit/query_helpers/test_question_validator.py
```
E       TypeError: ols.src.query_helpers.query_helper.QueryHelper.__init__() got multiple values for keyword argument 'llm_params'
```
> OLS-364: Fix runtime error: got multiple values for keyword argument 'llm_params'

- ols/src/prompts/prompts.py
Chat prompt constructor based on messages only
- Related Issue #[OLS-364](https://issues.redhat.com//browse/OLS-364):
> OLS-364: Chat prompt constructor based on messages only

- pyproject.toml
Enable call-arg type checks on CI
- `make check-types` will do the trick
> OLS-364: Enable call-arg type checks on CI

- ols/src/cache/redis_cache.py
Removed leftover - the `dict` now has proper type allowing Boolean values
> Removed leftover - the dict now has proper type

- ols/app/endpoints/ols.py
- tests/unit/app/endpoints/test_ols.py
Use user ID retrieved from auth middleware
- Related Issue #[OLS-378](https://issues.redhat.com//browse/OLS-378)
> OLS-378: Use user ID retrieved from auth middleware

- pdm.lock
Correct content_hash in pdm.lock. Incorrect hash was merged by https://github.com/openshift/lightspeed-service/pull/485.
- Closes #
> Correct content_hash in pdm.lock

- examples/olsconfig.yaml
- ols/app/models/config.py
- ols/constants.py
- ols/src/llms/providers/azure_openai.py
- tests/config/singleprovider.e2e.template.config.yaml
- tests/unit/app/models/test_config.py
- tests/unit/llms/providers/test_azure_openai.py
This PR implements Azure OpenAI support using Langchain's `AzureChatOpenAI`
[OLS-53](https://issues.redhat.com//browse/OLS-53)
[OLS-281](https://issues.redhat.com//browse/OLS-281)
Added tests for:
```
tests/config/singleprovider.e2e.template.config.yaml
tests/unit/app/models/test_config.py
tests/unit/llms/providers/test_azure_openai.py
```
Although it seems like the e2e needs to be changed because of the requirements on a URL that Azure OpenAI brings.
> OLS-281: Implements azure openai support

- Makefile
Avoid Ruff warnings: use new invocation command
> Avoid Ruff warnings: use new invocation command

- Containerfile
- Makefile
Invoke pdm sync to make sure packages are installed according to pmd.lock
Added a separate target for "pdm install" for picking up pyproject.toml updates.
- Closes #
> Invoke pdm sync to make sure packages are installed according to pmd.lock

- runner.py
Setup Matplotlib temporary directory
- Related Issue #[OLS-301](https://issues.redhat.com//browse/OLS-301)
- Make the original directory not writable (it's `~/.config/matplotlib/`)
- Run the service
- Warning about Matplotlib should not be displayed
> OLS-301: Setup Matplotlib temporary directory

- tests/unit/cache/test_in_memory_cache.py
- tests/unit/cache/test_redis_cache.py
User UUID checks in cache implementations
- Related Issue #[OLS-378](https://issues.redhat.com//browse/OLS-378)
> OLS-378: User UUID checks in cache implementations

- pdm.lock
- pyproject.toml
LangChain through 0.1.10 allows ../ directory traversal by an actor who is able to control the final part of the path parameter in a load_chain call. This bypasses the intended behavior of loading configurations only from the hwchase17/langchain-hub GitHub repository. The outcome can be disclosure of an API key for a large language model online service, or remote code execution.
https://github.com/advisories/GHSA-h59x-p739-982c
> Vulnerability update: langchain

- Makefile
- scripts/generate_openapi_schema.py
Script to generate OpenAPI schema + Makefile target to call this script
- Related Issue #[OLS-230](https://issues.redhat.com//browse/OLS-230)
- Call `make schema` from command line to generate OpenAPI schema
> OLS-230: Script to generate OpenAPI schema + Makefile target to call this script

- ols/app/endpoints/ols.py
[OLS-58](https://issues.redhat.com//browse/OLS-58): Conversation history won't be `None`
This will make rest of code easier to deal with "special cases" (which won't occur)
- Related Issue #573
> OLS-58: Conversation history won't be None

- Makefile
- tests/config/cluster_install/ols_configmap.yaml
- tests/e2e/pytest.ini
- tests/e2e/test_api.py
- tests/scripts/test-e2e-cluster.sh
- tests/scripts/test-e2e-standalone.sh
- tests/scripts/utils.sh
This PR does a few things:
1) introduces the concept of marking our e2e tests with keywords that indicate what configuration/environment they require, if any
2) moves the test-e2e-standalone.sh script into our common test scripts directory (i already updated the e2e job to tolerate the script being in either location: https://github.com/openshift/release/pull/49695) (could have been its own PR but it's a small change)
3) refactors the test-e2e-cluster.sh script to be a bit more modular so we can rerun the steps easily (install ols, uninstall ols, execute a set of e2e tests against ols)
4) updates the test script to run against all 4 of our supported providers while providing a pattern to introduce new "test suite configurations" (such as a no-rag vs rag-enabled configuration)
> OLS-405: Refactor e2e so we can run tests against multiple providers in one shot

- Containerfile.rag
- Containerfile.rag-content
- scripts/asciidoctor-text/attributes.yaml
- scripts/asciidoctor-text/convert-it-all.py
- scripts/asciidoctor-text/text-converter.rb
- scripts/download_embeddings_model.py
- scripts/generate_embeddings.py
This is a part of https://github.com/openshift/lightspeed-service/pull/518 that introduces quay.io/openshift/lightspeed-rag-content:${OLS_VERSION} image.
A Containerfile and supporting scripts for multi-stage build of RAG content, to be run from OLS CI. Inputs into the process are OCP 4.15 docs from https://github.com/openshift/openshift-docs and an embedding model from HuggingFace. Produced image contains
- OCP docs plaintext, not intended for inclusion into OLS RAG but can be useful to look at
- embedding model
- Faiss vector database with embeddings generated from the OCP docs plaintext
The resulting image is intended for consumption during the OLS build process.
The other half of this work is in https://github.com/openshift/release/pull/49510. …
> OLS-81: Team ownership of RAG pipeline - RAG content image

- Containerfile.redis
[Bug fix] Adding a  command to keep redis container awake. Currently when a redis pod start it immediately get terminated as we do have a entrypoint command that keeps it awake. So fixing it with a sleep command and the actual redis server will be spun up with required SSL/TLS and auth args from operator's code.
Tested integrating with https://github.com/openshift/lightspeed-operator/pull/25
> [Bug fix] Add command to keep redis container awake

- ols/app/endpoints/ols.py
- ols/constants.py
- ols/src/query_helpers/docs_summarizer.py
- tests/e2e/test_api.py
- tests/integration/test_ols.py
- tests/unit/app/endpoints/test_ols.py
Use constants for default messages, so that we don't have to change in different places if there is a change in text.
- Closes #
> Use constants for default responses

- ols/src/cache/redis_cache.py
- Atomic insert-or-append for one process
- Don't compute key two times
- (for multiprocess atomicity we'll implement optimistic locking in separate PR)
> OLS-302: Atomic insert-or-append for one process

- Makefile
- tests/integration/pytest.ini
- tests/integration/test_redis.py
Redis tests as part of integration tests
(now not enabled as it needs changes in integration tests setup)
> OLS-302: Redis tests as part of integration tests

- examples/openshift-lightspeed-tls.yaml
Note: https://github.com/openshift/lightspeed-console/pull/51 must merge first.
- Closes #
> Deletes the old/badly named ols service definition.

- docs/openapi.json
- ols/app/metrics/__init__.py
- ols/app/metrics/metrics.py
- ols/app/routers.py
Switch the handling of Metrics endpoint from ASGI to FastAPI, so we can reuse the auth_dependency in that endpoint as is.
- Closes #
> OLS-365 switch metrics endpoint to FastAPI

- README.md
- docs/openapi.json
- ols/app/main.py
- ols/app/metrics/metrics.py
- scripts/generate_openapi_schema.py
- tests/e2e/test_api.py
- tests/integration/test_metrics.py
Change the metrics route from `/metrics/` to `/metrics`. 
`/metrics` is the conventional path to scrape metrics, moreover, there is no child path under `/metrics`
This PR follows the PR #601 
- Closes #
> Remove trailing slash for metrics route

- scripts/questions_gen.py
TL;DR; `raise` must be followed by an exception instance or an exception class,
and exceptions must be instances of `BaseException` or a subclass thereof.
Raising a literal will raise a `TypeError` at runtime.
> Fix: cannot raise literal

- ols/app/endpoints/ols.py
- ols/constants.py
As we removed file usage for keywords, this constant is not required.
- Related Issue # [OLS-353](https://issues.redhat.com//browse/OLS-353)
> Remove unused kw file constant

- scripts/validate_response.py
- tests/e2e/test_api.py
- tests/test_data/question_answer_pair.json
Validate any deviation in LLM response.
A stand alone python script to check responses for different scenario / different models. The json file must contain question/answer pair for given scenario & model.
- Load pre-defined question/answer pair from json file.
- Call API with question/query
- Check similarity between answer from file & llm response.
- Related Issue # [OLS-165](https://issues.redhat.com//browse/OLS-165)
- Closes #
> OLS-165: Response sanity check

- scripts/validate_response.py
Refactoring: argparser `type` don't have to be callabke
> Refactoring: argparser type don't have to be callabke

- ols/app/main.py
- ols/app/metrics/__init__.py
- ols/app/metrics/metrics.py
- tests/config/valid_config.yaml
- tests/e2e/test_api.py
- tests/integration/test_metrics.py
- tests/unit/utils/test_config.py
Expose model and provider metrics:
```
$ curl localhost:8080/metrics | grep provider
selected_provider_info{name="bam"} 1.0
selected_model_info{name="ibm/granite-13b-chat-v2"} 1.0
model_enabled{model="ibm/granite-13b-chat-v2",provider="bam"} 1.0
model_enabled{model="gpt-4-1106-preview",provider="openai"} 1.0
model_enabled{model="gpt-3.5-turbo",provider="openai"} 1.0
```
- Related Issue #[OLS-437](https://issues.redhat.com//browse/OLS-437)
> OLS-437: Expose model and provider metrics

- scripts/download_embeddings_model.py
- tests/config/singleprovider.e2e.template.config.yaml
- tests/e2e/test_api.py
- tests/scripts/test-e2e-standalone.sh
As we pivot to doing more testing on cluster installs, we will do less legwork to setup the standalone run.  In this case that means not worrying about providing RAG reference content to standalone testing.
- Closes #
> Remove rag testing from standalone.sh execution

- pdm.lock
- pyproject.toml
Bump-up `pytest-cov` version (devel library)
- Related Issue #[OLS-420](https://issues.redhat.com//browse/OLS-420)
> OLS-420: Bump-up pytest-cov version (devel library)

- tests/e2e/test_api.py
e2e trivial fix: Check for conversation ID in JSON response
> e2e trivial fix: Check for conversation ID in JSON response

- Containerfile.rag
- Makefile
- ols/constants.py
- ols/src/query_helpers/docs_summarizer.py
- ols/utils/token_handler.py
- tests/constants.py
- tests/mock_classes/mock_query_engine.py
- tests/mock_classes/mock_retrievers.py
- tests/unit/docs/test_doc_summarizer.py
- tests/unit/utils/test_token_handler.py
OLS now expects to find the complete URL to the page of OCP documentation in the docs_url metadata element attached to RAG embeddings. This is an optimization compared to how the docs url is currently assembled every time a RAG embedding is retrieved.
Needs https://github.com/openshift/lightspeed-rag-content/pull/3 to merge first and RAG content to get regenerated.
- [] Refactor
- Related Issue # 
- Closes # https://issues.redhat.com/browse/OLS-338
> OLS-338: Add docs_url metadata element while creating embedding index

- ols/src/llms/providers/azure_openai.py
- ols/src/llms/providers/openai.py
Now parameters don't have to be fixed in provider classes because the verification and filtering code is now part of provider registration logic.
- Related Issue #[OLS-363](https://issues.redhat.com//browse/OLS-363)
- Closes #
> OLS-363: Now parameters don't have to be fixed in provider classes

- examples/olsconfig.yaml
- ols/app/models/config.py
- tests/config/cluster_install/ols_configmap.yaml
- tests/config/singleprovider.e2e.template.config.yaml
- tests/scripts/test-e2e-standalone.sh
- tests/unit/app/models/test_config.py
Add transcripts capture configuration.
https://issues.redhat.com/browse/OLS-285 says:
> This is a post june task because we do not want to give OLS to anyone who's going to turn off data collection for now (the whole reason we are giving it to them is to get the data about how it performs)
My plan is to have it available in config, but hardcode it can't be turned off (just log a msg) later in the relevant place.
> OLS-214: Add transcripts capture configuration

- examples/openshift-lightspeed-tls.yaml
- ols/app/endpoints/authorized.py
- ols/app/endpoints/feedback.py
- ols/app/endpoints/ols.py
- ols/app/metrics/metrics.py
- ols/constants.py
- ols/utils/auth_dependency.py
- tests/config/cluster_install/ols_manifests.yaml
- tests/e2e/test_api.py
- tests/mock_classes/mock_k8s_api.py
- tests/scripts/utils.sh
- tests/unit/utils/test_auth_dependency.py
Refactor Authorization to include the following 2 features:
1) include Groups in the SAR Request:
this will allow roles assigned to groups that a user belongs to , to take effect in addition to the user directly assigned roles
2) fine-grained permissions support:
this will allow us to customize the dependency for each endpoint separately, where we now require diffrent permissions to access Metrics compared to the regular OLS endpoints
- Closes #
> OLS-417: add support for authorization groups and fine-grained permissions

- tests/integration/__init__.py
- tests/integration/query_helpers/test_query_docs.py
- tests/integration/test_feedback.py
- tests/integration/test_openapi.py
- tests/integration/test_redis.py
Minor changes in integration tests:
- proper usage of `pytest.mark`
- `__init__.py` to define module
- default open mode parameter not required
- `yield` was used instead of `return`
> Minor changes in integration tests

- ols/utils/auth_dependency.py
Trivial: `logger.warn()` call is deprecated
> Trivial: Logger.warn() call is deprecated

- ols/constants.py
- ols/src/query_helpers/docs_summarizer.py
- ols/utils/token_handler.py
- tests/unit/docs/test_doc_summarizer.py
- tests/unit/utils/test_token_handler.py
Use score to filter rag content.
Refactoring: remove additional methods, add constants to constant.py
logger info to debug
- Related Issue # [OLS-399](https://issues.redhat.com//browse/OLS-399)
> OLS-399: Use score to filter rag content

- ols/src/llms/providers/watsonx.py
- pdm.lock
- pyproject.toml
- tests/mock_classes/mock_watsonxllm.py
- tests/unit/llms/providers/test_watsonx.py
New WatsonxLLM used instead of deprecated one
It requires changes in code and tests too
> OLS-420: New WatsonxLLM used instead of deprecated one

- ols/app/main.py
- ols/app/metrics/__init__.py
- ols/app/metrics/metrics.py
- tests/e2e/metrics_utils.py
- tests/e2e/test_api.py
- tests/integration/test_liveness_readiness.py
- tests/integration/test_metrics.py
- tests/integration/test_ols.py
- tests/integration/test_ols_debug.py
- tests/integration/test_openapi.py
we will now have just a single provider/model metric:
```
provider_model_configuration{model="ibm/granite-13b-chat-v2",provider="bam"} 0.0
provider_model_configuration{model="gpt-3.5-turbo",provider="openai"} 0.0
provider_model_configuration{model="ibm/granite-13b-chat-v2",provider="watsonx"} 1.0
```
the value of 0.0 means configured but not enabled, the value of 1.0 means it is the enabled provider/model.
this is following recommendations from the monitoring team in order to reduce our timeseries for telemetry:
https://issues.redhat.com/browse/MON-3778?focusedId=24456791&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-24456791
> OLS-117: Refactor provider/model metrics

- tests/e2e/metrics_utils.py
- tests/e2e/test_api.py
e2e: Check for max default model+provider, to make sure the logic to setup metrics or config loading/validation is ok
> e2e: Check for max default model+provider

- tests/unit/utils/test_query_filter.py
Use regular `assert` statement consistently in all tests
To make use of `pytest`'s assertion rewriting, a regular `assert` statement
is preferred over `unittest`'s assertion methods.
> Use regular `assert` statement consistently in all tests

- ols/constants.py
As L2 is a distance metric, the value can be > 1. Faiss L2 index gives squared L2 as score. This is not normalized between 0 to 1.
Currently we are still using bge embedding model (for RAG), so it is not very evident but once we move to sentence-tranformers embedding model, we can see the value > 1
> Correct L2 score range info

- tests/unit/utils/test_query_filter.py
Fix [OLS-511](https://issues.redhat.com//browse/OLS-511): Bug when running `QueryFilter` unit tests alone
- Related Issue #[OLS-511](https://issues.redhat.com//browse/OLS-511)
- Closes #
> Fix OLS-511: Bug when running `QueryFilter` unit tests alone

- scripts/validate_response.py
Change back to original functionality of argparser type.. (reverting https://github.com/openshift/lightspeed-service/pull/750)
Same change worked for e2e argparser.. as there was no option to limit different acceptable values. But for response evaluation, it is there and [pj-rehearse](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/50793/rehearse-50793-periodic-ci-openshift-lightspeed-service-main-response-sanity-check/1780208105762590720) is failing for weekly job PR https://github.com/openshift/release/pull/50793..
We can implement this correctly later, if we want to avoid function for argparser `type`.
> revert argparser type change for resp eval

- runner.py
This fix will log access on HTTP endpoints unless the log level is set below info.
This avoid excessive logging on readiness and liveness probe.
- Closes #
> fix: only debug level logging includes access log

- ols/app/models/config.py
Iterating over dictionary keys, using
`key in dict` is more readable and efficient than `key in dict.keys()`,
while having the same semantics.
> Use idiomatic dict call

- ols/src/cache/postgres_cache.py
- ols/utils/auth_dependency.py
(Minor) added missing types for `__init__` methods
> (Minor) added missing types for `__init__` methods

- Containerfile
- Makefile
- docs/openapi.json
- ols/app/endpoints/ols.py
- ols/app/models/models.py
- ols/constants.py
- ols/src/query_helpers/docs_summarizer.py
- ols/utils/token_handler.py
- tests/e2e/test_api.py
- tests/mock_classes/mock_query_engine.py
- tests/mock_classes/mock_retrievers.py
- tests/unit/app/endpoints/test_ols.py
- tests/unit/app/models/test_models.py
- tests/unit/docs/test_doc_summarizer.py
- tests/unit/utils/test_token_handler.py
LLMResponse now contains referenced documents that are pairs of (docs_url, title). Title comes from the "title" element of metadata in embedding nodes, added in https://github.com/openshift/lightspeed-rag-content/pull/9, which needs to merge first.
RAG content is now based on the sentence-transformers/all-mpnet-base-v2 embedding model, which necessitated RAG_SIMILARITY_CUTOFF_L2 increase and changes to a few asserts about what documents are retrieved for what queries.
- Closes # https://issues.redhat.com/browse/OLS-413
> OLS-413: Make LLMResponse include page titles for referenced documents

- tests/e2e/test_api.py
Check HTTP status code first
It is much better for reading CI failures, because (for example) timeout errors are much easier to read when the status code (GatewayTimeout) is checked first.
> Check HTTP status code first

- Makefile
Ignore asserts in scripts the same way we ignored them in tests
Does not change `ols` checking at all
- Closes #
> Ignore asserts in scripts the same way we ignored them in tests

- tests/integration/test_ols.py
Integration tests stabilization
It does not bring any real value to have tests that depends on one Pydantic version (and the `url` field is changing from time to time with new Pydantic versions)
> Integration tests stabilization

- ols/app/main.py
- ols/constants.py
- tests/e2e/test_api.py
This is an improvement for https://github.com/openshift/lightspeed-service/pull/676 that adds redaction of sensitive HTTP headers, such as "authorization", "proxy-authorization", "cookie", "www-authenticate", "proxy-authenticate" and "set-cookie".
- [] Refactor
- Closes # https://issues.redhat.com/browse/OLS-375
Now sensitive header values are replaces with XXXXX:
```
2024-04-08 20:12:23,437 [ols.app.main:main.py:88] DEBUG: Request from 127.0.0.1:36978 Headers({"host":"127.0.0.1:8080", "user-agent":"curl/8.2.1", "authorization":"XXXXX", "accept":"application/json", …
```
> OLS-375: added redaction of sensitive headers

- ols/src/prompts/prompt_generator.py
- ols/src/prompts/prompts.py
- tests/e2e/test_api.py
- tests/integration/test_ols.py
- tests/unit/prompts/test_prompt_generator.py
Use freeform text as prompt. This is done to avoid ChatPromptTemplate, as granite was adding role tag to the response.. This also gives us more control how we want to modify prompt and add model specific prompt.
Currently the prompt has few granite specific tags.. GPT still works well with this prompt..
This is as per the experimentation done in [OLS-452](https://issues.redhat.com/browse/OLS-452)
Possible future works:
- As we are not using chat template anymore, we can think of alternate/more generic way of saving history.
- Model specific prompts.
> Use freeform prompt template for conversation

- scripts/feedback_aggregator.py
Feedback aggregator
An example of CSV file with aggregated feedbacks:
```
Cluster ID,User ID,Conversation ID,Question,LLM response,Sentiment,Feedback
00000000-0000-0000-0000-000000000001,c1143120-551e-4a47-ad47-2748d6f3c81c,00000000-0000-0000-0000-000000000000,testy test,bla,1,
00000000-0000-0000-0000-000000000002,11111111-551e-4a47-ad47-2748d6f3c81c,00000000-0000-0000-0000-000000000001,testy test,bla,1,that is awesome
00000000-0000-0000-0000-000000000003,22222222-551e-4a47-ad47-2748d6f3c81c,00000000-0000-0000-0000-000000000002,testy test,bla,2,that is really awesome
00000000-0000-0000-0000-000000000001,c1143120-551e-4a47-ad47-2748d6f3c81c,00000000-0000-0000-0000-000000000000,testy test,bla,1,
00000000-0000-0000-0000-000000000002,11111111-551e-4a47-ad47-2748d6f3c81c,00000000-0000-0000-0000 …
```
> OLS-137: Feedback aggregator

- ols/src/query_helpers/docs_summarizer.py
- tests/unit/docs/test_doc_summarizer.py
[OLS-524](https://issues.redhat.com//browse/OLS-524): default parameter for history
Added more unit tests to cover this situation + to cover truncation too
- Related Issue #[OLS-524](https://issues.redhat.com//browse/OLS-524)
> OLS-524: default parameter for history

- tests/mock_classes/mock_summary.py
[OLS-524](https://issues.redhat.com//browse/OLS-524): Don't use mutable default value in mock object
- Related Issue #[OLS-524](https://issues.redhat.com//browse/OLS-524)
- Closes #
> OLS-524: Don't use mutable default value in mock object

- ols/app/models/config.py
- ols/constants.py
- tests/unit/app/models/test_config.py
Context window size can be specified for provider + model
When provider+model is not known, the default size will be used.
(Please note that Azure OpenAI != OpenAI now!)
> Context window size can be specified for provider + model

- tests/e2e/test_api.py
Use more obvious invalid query for test case. This is done to avoid recent failure with azure..
We can try to modify the prompt, meanwhile just to get through CI..
> modify invalid query text for e2e test

- ols/utils/token_handler.py
- tests/unit/utils/test_token_handler.py
Better error message when token limit threshold is reached
- Closes #
> OLS-538: Better error message when token limit threshold is reached

- ols/constants.py
- ols/utils/auth_dependency.py
Keep default user UUID and set it to "nil" UUID
- Related Issue #[OLS-495](https://issues.redhat.com//browse/OLS-495)
> OLS-495: Keep default user UUID and set it to "nil" UUID

- ols/constants.py
- ols/utils/token_handler.py
- tests/unit/utils/test_token_handler.py
We are using precise context window now and token count is currently an approximation. So adding buffer to token count.
With this change we will increase token count by some weight.
Currently a single constant is used, but this can be extended further to have model/provider specific weights/percentage. Experimentation is required to understand in general how far off is our estimation.
Alternatively we could decrease context window by some buffer. But decided against that as error message may be confusing. Context window is well know and token calculation is an estimation anyway. So modifying count is more reasonable.
- Related Issue # [OLS-537](https://issues.redhat.com//browse/OLS-537)
cc: @bparees
> Add buffer to token count

- ols/src/query_helpers/docs_summarizer.py
[OLS-549](https://issues.redhat.com//browse/OLS-549): Strip whitespaces from response
(+ save one or more tokens in history)
> OLS-549: Strip whitespaces from response

- tests/e2e/pytest.ini
- tests/e2e/test_api.py
Remove redundant (last) standalone tests.
These test scenarios are covered in "cluster" alternatives.
This PR paves the road for the complete removal of the standalone CI suite (the "cluster" suite is running everything except "standalone").
> OLS-506: Remove redundant standalone tests

- ols/src/query_helpers/docs_summarizer.py
Check final token count before reaching LLM
That should avoid "Internal server error"
- Closes #
> OLS-538: Check final token count before reaching LLM

- ols/src/query_helpers/docs_summarizer.py
- ols/src/query_helpers/question_validator.py
- ols/utils/token_handler.py
- tests/unit/utils/test_token_handler.py
Refactor `get_token_handler method`. That method used to do two operations:
1. calculate available tokens
2. throws exception when no token are left
It leads to semantic misuse.
It's better to have two methods sharing the same code logic put into private method.
- Closes #
> OLS-538: Refactor get_token_handler method

- scripts/feedback_aggregator.py
Fix issue [OLS-553](https://issues.redhat.com//browse/OLS-553): process files with wrong paths gracefully
- Related Issue #[OLS-553](https://issues.redhat.com//browse/OLS-553)
- Run `pytest -v scripts/feedback_aggregator.py`
> Fix issue OLS-553: process files with wrong paths gracefully

- tests/unit/llms/providers/test_bam.py
- tests/unit/llms/providers/test_watsonx.py
Unit tests: handling known and unknown parameters by BAM and Watsonx providers
- Closes #
> OLS-447: Unit tests: handling known and unknown parameters by BAM and Watsonx providers

- Containerfile
- Makefile
Update RAG content, pick up the following updates: 
- [OLS-517](https://issues.redhat.com//browse/OLS-517) Handle encoded/image data in index
- [OLS-530](https://issues.redhat.com//browse/OLS-530) Use pdm to manage dependencies in the lightspeed-rag-content repo
- plaintext page exclusion
- OCP docs update as of 2024/04/26
- Related Issue # https://issues.redhat.com/browse/OLS-517, https://issues.redhat.com/browse/OLS-530
- Closes #
> Update RAG content: OLS-517, OLS-530, page exclusion, OCP docs update

- tests/unit/llms/providers/test_openai.py
Unit test: default params to None
Similar to tests we have for other providers already
- Closes #
> OLS-447: Unit test: default params to None

- tests/e2e/test_api.py
Just set global variable type, don't initialize to silly value
It is improper, these client will be always set **or** the test setup fails
Also it allows the IDEs and type checkers to infer the type correctly
> Just set global variable type, don't initialize to silly value

- tests/unit/utils/test_config.py
Check that query redactor is constructed before accessing it's attribute
The (possible) error message will be more specific and easier to find cause
> Check that query redactor is constructed before accessing it's attribute

- ols/src/llms/llm_loader.py
- tests/unit/llms/test_llm_loader.py
Check global provider configuration existence
Added unit test for this situation
- Closes #
> OLS-447: Check global provider configuration existence

- ols/constants.py
Currently L2 threshold score is set to a very low value. hence we are discarding relevant docs/chunks.
[OLS-571](https://issues.redhat.com/browse/OLS-571)
[Document](https://docs.google.com/spreadsheets/d/12dPNombnsYjP95yzWyoHxKMej7l5y9lX1pi7ZpffHeg/edit?usp=sharing)
Above file has few sample questions along with score for top matching chunk. Based on this Threshold score cut-off is increased to 1.4.
With this increase, it is possible that few irrelevant chunks will be included, but it is trade off
> increase l2 threshold cut-off

- tests/e2e/metrics_utils.py
Avoid NPE when metric is not parseable
> Avoid NPE when metric is not parseable

- ols/app/endpoints/feedback.py
This is actually an interesting bug that is not manifested because the `in` operator works for lists too (but in newer version of library it can fail).
- Related Issue #[OLS-586](https://issues.redhat.com//browse/OLS-586)
- Closes #
> OLS-586: Exclude parameter is of type set

- tests/mock_classes/mock_retrieved_node.py
- tests/mock_classes/mock_retrievers.py
- tests/unit/utils/test_token_handler.py
Refactoring: `MockRetrievedNode` moved into `mock_classes`
Previously it was used just in Token handler tests so it make sense to define it there. But nowadays it is imported by other
mock class, so we ended up having circular-like imports.
> Refactoring: MockRetrievedNode

- Makefile
Remove default test tag.
My intention was that cluster tests are omitted when running locally, but the result was that tests were omitted in CI too as the TEST_TAGS was set to "" -> default with "not cluster" was used.
> Fix: Remove default test tags

- ols/src/llms/providers/provider.py
`@abstractproperty` decorator is deprecated, use `@property`+`@abstractmethod` instead
> Abstractproperty decorator is deprecated, use property+abstractmethod

- tests/mock_classes/mock_watsonxllm.py
Watsonxllm mock class should have method headers compatible with real WatsonxLLM class
> Watsonxllm mock class should have method headers compatible with real WatsonxLLM class

- ols/app/main.py
Fixed type: `frozenset` is not compatible with `set`
> Fixed type: frozenset is not compatible with set

- ols/app/metrics/__init__.py
Fix: `metrics_app` does not exists anymore
> Fix: metrics_app does not exists anymore

- ols/user_data_collection/data_collector.py
Fix: `dockerconfig` technically is unbound variable in circumstances when `TypeError` is thrown from different statement
> Fix: `dockerconfig` technically is unbound variable in circumstances when `TypeError` is thrown from different statement

- ols/utils/auth_dependency.py
Type fix: attributes won't be `None` in runtime
> Type fix: attributes won't be `None` in runtime

- tests/e2e/test_api.py
Prolong wait interval for data collector in e2e test.
The cause of the "bug story" is because we collected logs too fast. As seen from the logs, the last log was about posting the payload. We pulled the logs before the post was completed and logged.
The issue might occur again, eg. when console.stage.redhat.com is responding slowly, but the wait in this PR should be enough for standard situations.
> OLS-595: Prolong wait interval for data collector in e2e test

- ols/app/models/config.py
`yaml_port` is used in `raise` block so it need to be defined outside `try` block
> `yaml_port` is used in `raise` block so it need to be defined outside `try` block

- Containerfile
- Makefile
- ols/constants.py
- ols/utils/token_handler.py
- tests/unit/query_helpers/test_docs_summarizer.py
- tests/unit/utils/test_token_handler.py
Change score threshold and cut-off logic check as per faiss IP index.
Index was changed from L2 to IP with this PR https://github.com/openshift/lightspeed-rag-content/pull/23.
With current index, score range is 0 to 1 and higher score is better. Cut-off is set to 0.3 based on top retrieved chunks score for [sample queries](https://docs.google.com/spreadsheets/d/1wjYk8FdX12BCfuoU-7cGDTB_hnla42eti07EsjyZwi0/edit?usp=sharing).
cc: @syedriko
> OLS-493: Change score as per faiss IP index

- tests/unit/ui/test_gradio_ui.py
Fix: history passed to chat UI can not be `None`
> Fix: history passed to chat UI can not be None

- ols/app/models/config.py
- tests/config/valid_config_with_azure_openai.yaml
- tests/config/valid_config_with_azure_openai_api_version.yaml
- tests/unit/app/models/test_config.py
- tests/unit/utils/test_config.py
Provider-specific configuration
Please note that discriminated unions are not used in the end. It would be possible to use them in following manner:
```python
class AzureOpenAIConfig(BaseModel):
url: str
api_key: str
class WatsonxConfig(BaseModel):
url: str
class ProviderSpecificConfig(RootModel):
root: Union[AzureOpenAIConfig, WatsonxConfig]
class ProviderConfig(BaseModel):
"""LLM provider configuration."""
name: Optional[str] = None
type: Optional[str] = None
provider_config: Optional[ProviderSpecificConfig] = None
```
but in the end we'll need to re-cast everytime config is used, no proper checks against type could be done and the type hints will become unusable at the same time. So I prefer to be dumb&specific, not overthink it;)
- Related Issue …
> OLS-622: provider-specific configuration

- ols/app/models/config.py
- tests/unit/utils/test_config.py
Display proper error messages for missing sections in `olsconfig.yaml`
- Related Issue #[OLS-654](https://issues.redhat.com//browse/OLS-654)
> OLS-654: proper error messages for missing sections in olsconfig.yaml

- docs/openapi.json
- ols/app/endpoints/ols.py
- ols/app/models/models.py
- ols/src/query_helpers/docs_summarizer.py
**For consideration.**
Change `ReferencedDocument` definition to pydantic dataclass (standard dataclass but with pydantic typing).
IMHO it is a better fit. You can also create an instance with direct args/kwargs instead of feeding it with dict.
> OLS-631: Switch ReferencedDocument from BaseModel to dataclass

- ols/app/models/config.py
- tests/unit/app/models/test_config.py
- Forbid unknown provider-specific parameters
- 100% backed by unit tests
- Closes #
> OLS-622: Forbid unknown provider-specific parameters

- ols/app/models/config.py
Don't need to explicitly specify default `None` value.
`None` is the default value for `dict.get()`, so it is redundant to pass it
explicitly.
> OLS-622: Don't need to explicitly specify default None value

- scripts/data_collection/list_objects_in_ceph.py
[OLS-550](https://issues.redhat.com//browse/OLS-550): Use f-strings instead of `str.format()`
- Related Issue #[OLS-550](https://issues.redhat.com//browse/OLS-550)
- Closes #
> OLS-550: Use f-strings instead of str.format()

- tests/e2e/test_api.py
Fix: leftover string literals in e2e tests
> Fix: leftover string literals in e2e tests

- ols/src/llms/providers/azure_openai.py
- ols/src/llms/providers/openai.py
- tests/unit/llms/providers/test_azure_openai.py
- tests/unit/llms/providers/test_openai.py
URL and credentials are part of provider objects
Will be used especially in Azure OpenAI where credentials might be `None`
- Closes #
> OLS-641: URL and credentials are part of provider objects

- ols/utils/config.py
Cache conversation_cache in config singleton instead of initializing it with every request.
Removed raise from config singleton as pydantic config will raise error if this sections is missing.
> OLS-488: Cache conversation_cache in config singleton

- pdm.lock
- pyproject.toml
Add `azure-identity` package that is needed by Azure OpenAI auth mechanism
- Related Issue #OSL-641
- Closes #
> OLS-641: Add azure-identity package that is needed by Azure OpenAI auth mechanism

- pdm.lock
- pyproject.toml
Bump-up Black devel dependency to 24.4.0
> Bump-up Black devel dependency to 24.4.0

- pdm.lock
- pyproject.toml
Bump-up devel tool Mypy to version 1.10.0
- Related Issue #[OLS-673](https://issues.redhat.com//browse/OLS-673)
> OLS-673: Bump-up devel tool Mypy to version 1.10.0

- tests/config/valid_config_with_azure_openai_2.yaml
- tests/config/valid_config_with_bam_2.yaml
- tests/config/valid_config_with_watsonx_2.yaml
- tests/unit/utils/test_config.py
Check if credentials path is loaded from provider config only
- Closes #
> OLS-641: Check if credentials path is loaded from provider config only

- ols/constants.py
- ols/user_data_collection/data_collector.py
- ols/utils/auth_dependency.py
- runner.py
- tests/config/cluster_install/ols_manifests.yaml
- tests/e2e/test_api.py
- tests/e2e/utils/cluster.py
- tests/mock_classes/mock_k8s_api.py
- tests/unit/utils/test_auth_dependency.py
> OLS-546: Use cluster id as user id

- ols/utils/auth_dependency.py
[OLS-648](https://issues.redhat.com//browse/OLS-648): added `type ignore` to silent Mypy on CI (and also when running locally as you can check)
Please note that it is not a proper bug fix, it needs to be done as part of the OSL-648 story
Additionally it allow us to merge https://github.com/openshift/lightspeed-service/pull/1018
- Related Issue #[OLS-648](https://issues.redhat.com//browse/OLS-648)
- Closes #
> OLS-648: added type ignore to silent Mypy on CI

- ols/utils/auth_dependency.py
Fix for currently unsupported Mypy multiple-line-statement behavior
It basically don't allow us to use `#types ignore` in conditions that spread over multiple lines.
(which is ugly and IMHO against PEP-8)
- Related Issue #[OLS-648](https://issues.redhat.com//browse/OLS-648)
- Closes #
> OLS-648: Fix for currently unsupported Mypy multiple-line-statement behavior

- docs/openapi.json
- ols/app/models/models.py
REST API schema for `/query` endpoint with optional list of attachments
- Closes #
- Start the OLS and go to `/docs`
- Try the new feature there in interactive UI
> OLS-624: REST API schema for /query endpoint with optional list of attachments

- examples/openshift-lightspeed-tls.yaml
Pull Request #882 introduced the need for additional ClusterRole permissions to be added to the openshift-lightspeed-tls.yaml file to enable the successful deployment of the OpenShift Lightspeed Service via that manifest
- [x ] Bug fix
- Closes #
- [x ] I have performed a self-review of my code.
> Update ols-tls yaml in example for new CR perms

- pdm.lock
- pyproject.toml
Bump-up langchain to 0.2.1
- Related Issue #[OLS-657](https://issues.redhat.com//browse/OLS-657)
- Closes #
> OLS-657: Bump-up langchain to 0.2.1

- docs/openapi.json
- ols/app/models/models.py
- tests/e2e/test_api.py
Disable additional properties + basic REST API tests with attachments
- Closes #
> OLS-624: Disable additional properties + basic REST API tests with attachments

- Containerfile
- Makefile
Pick up the RAG content image from https://github.com/openshift/lightspeed-rag-content/pull/39
- Closes #
https://issues.redhat.com/browse/OLS-639 "Retain section headers in RAG content"
https://issues.redhat.com/browse/OLS-660 "Include code block with identifier in plain text file"
https://issues.redhat.com/browse/OLS-662 "For the OCP docs, the adoc to plaintext conversion loses list continuations"
> Pick up RAG content generated with the new asciidoc to plaintext converter

- ols/src/cache/postgres_cache.py
- ols/utils/config.py
It's redundant to specify the exception name in a `raise` statement if the
exception is being re-raised.
> (Trivial) Removed redundant exception in raise

- pdm.lock
- pyproject.toml
Bump-up devel dependency: pytest to 8.2.2.
> Bump-up devel dependency: pytest to 8.2.2.

- pdm.lock
- pyproject.toml
Security fix: bump-up Gradio to 4.36.1
> Security fix: bump-up Gradio to 4.36.1

- tests/unit/utils/test_config.py
Currently the test `test_invalid_config` has approximately 550 lines and checks for multiple problems. If some changes are made in `config.py`, `model.py`, or provider-specific sources, and this test starts to fail, it is hard and time consuming to isolate the problem (and the fact that Pytest does not print line numbers make it even worse). So the test was splitted into logical parts - no new tests were added nor deleted.
> Split unit test for invalid config

- pdm.lock
- pyproject.toml
Security fix: bump-up Azure identity to 1.16.1
- Related Issue #[OLS-708](https://issues.redhat.com//browse/OLS-708)
- Closes #
> OLS-708: Security fix: bump-up Azure identity to 1.16.1

- ols/src/rag_index/index_loader.py
- ols/utils/config.py
- tests/config/cluster_install/ols_manifests.yaml
- tests/unit/rag_index/test_index_loader.py
With this, the memory consumption for the sidecar falls from 500MiB under 100MiB.
> OLS-694: Improve memory usage in collector script by lazily loading llama_index

- tests/integration/pytest.ini
- tests/integration/test_ols.py
Tag for attachments tests
Currently integration tests are a bit slow, so it is good to have the ability to select (or deselect) group of them based on marks. New mark is used for tests that sends (any) attachment to tested OLS service via mocked REST API.
- Closes #
> OLS-624: Tag for attachments tests

- ols/app/models/config.py
- tests/unit/app/models/test_config.py
Remove check for deployment name existence - it is optional and can be overwritten in azure-specific config section
> Remove check for deployment name existence

- tests/e2e/test_api.py
As we have added LLM call as part of readiness check (https://github.com/openshift/lightspeed-service/pull/1081). It will take more time to finish processing..
watsonx e2e readiness test case is failing as readiness call timeout value is very less. (failing for https://github.com/openshift/lightspeed-service/pull/1082 and other PR as well).
We could increase the timeout or do multiple retry. This PR contains both (we can remove one later, if we want)
> fix readiness e2e test case

- tests/config/cluster_install/ols_configmap.yaml
- tests/e2e/test_api.py
- tests/e2e/utils/cluster.py
- tests/scripts/utils.sh
Added a test to check that the version of OCP docs in the RAG database matches that of the cluster we're running on.
- Related Issue # https://issues.redhat.com/browse/OLS-644
- Closes #
> OLS-644: Use version-aligned OCP docs for RAG

- pdm.lock
- pyproject.toml
Bump-up Uvicorn in order to create build requirements
- Closes #
> OLS-721: Bump-up Uvicorn in order to create build requirements

- Makefile
Makefile target to generate `requirements.txt` file. That file will be used later by tooling (`pip_find_builddeps.py`) to generate `requirement-build.in` file used by Konflux for hermetic builds.
- Closes #
> OSL-721: Makefile target to generate requirements.txt file

- pdm.lock
- pyproject.toml
Security fix: bump-up `langchain` and `langchain-community` packages
- Related Issue #[OLS-739](https://issues.redhat.com//browse/OLS-739)
> OLS-739: Security fix: bump-up langchain and langchain-community

- pdm.lock
- pyproject.toml
Bump-up Ruff to 0.4.9 (devel dependency)
> Bump-up Ruff to 0.4.9

- scripts/data_collection/user_data_aggregator.py
- tests/unit/utils/test_redactor.py
Strings are concatenated implicitly, not need/want to use explicit concatenation
> Strings are concatenated implicitly, not need/want to use explicit concatenation

- Containerfile
- Makefile
Switch to the rag-content image with the alert runbooks added to it as per [OLS-617](https://issues.redhat.com//browse/OLS-617).
- Related Issue # https://issues.redhat.com/browse/OLS-617
- Closes #
> OLS-617: Add alert runbooks as a RAG content source

- ols/app/models/config.py
Use `OSError`, not `IOError`
`OSError` is the builtin error type used for exceptions that relate to the
operating system.
In Python 3.3, a variety of other exceptions, like `WindowsError` were
aliased to `OSError`. These aliases remain in place for compatibility with
older versions of Python, but may be removed in future versions.
Prefer using `OSError` directly, as it is more idiomatic and future-proof.
> Use `OSError`, not `IOError`

- ols/app/models/config.py
Remove deprecated Extra and replace it with literals.
In pydantic:
```python
@deprecated(
"Extra is deprecated. Use literal values instead (e.g. `extra='allow'`)", category=PydanticDeprecatedSince20
)
```
> OLS-490: Remove deprecated Extra and replace it with literals

- scripts/generate_packages_to_prefetch.py
Script to generate packages to prefetch in Cachi2
This script performs several steps:
1. removes torch+cpu dependency from project file
2. generates requirements.txt file from pyproject.toml + pdm.lock
3. removes all torch dependencies (including CUDA/Nvidia packages)
4. downloads torch+cpu wheel
5. computes hashes for this wheel
6. adds the URL to wheel + hash to resulting requirements.txt file
- Closes #
> OLS-721: Script to generate packages to prefetch in Cachi2

- ols/app/models/config.py
- tests/unit/app/models/test_config.py
- tests/unit/llms/providers/test_bam.py
- tests/unit/llms/providers/test_openai.py
- tests/unit/llms/providers/test_watsonx.py
- tests/unit/utils/test_config.py
Refactor ModelConfig.
Next step is to add `model_parameters`, eg.:
```yaml
models:
- name: ibm/granite-13b-chat-v2
context_window_size: 1000
model_parameters:
max_tokens_for_response: 20
```
> OLS-490: Refactor ModelConfig

- tests/integration/test_feedback.py
Don't have to pass `_setup` fixture, it is autoused
> Don't have to pass setup fixture, it is autoused

- tests/integration/test_openapi.py
Don't have to pass `setup` to test functions, it can be autoused for OpenAPI tests
> Don't have to pass `setup` to test functions for OpenAPI tests, it can be autoused

- Containerfile
Use non-root user in Containerfile
- Related Issue #[OLS-702](https://issues.redhat.com//browse/OLS-702)
- Closes #
> OLS-702: Use non-root user in Containerfile

- Makefile
[OLS-758](https://issues.redhat.com//browse/OLS-758): Fix CI job failures caused by newest Mypy version 1.10.1
We install Mypy with pinned version as configured in `pyproject.toml` and `pdm.lock`
> OLS-758: Fix CI job failures caused by newest Mypy version 1.10.1

- tests/integration/test_authorized.py
- tests/integration/test_feedback.py
- tests/integration/test_liveness_readiness.py
Usefixtures in integration tests
Fixtures can be injected either by passing them as parameters to the test
function, or by using the `@pytest.mark.usefixtures` decorator.
If the test function depends on the fixture being activated, but does not
use it in the test body or otherwise rely on its return value, prefer
the `@pytest.mark.usefixtures` decorator, to make the dependency explicit
and avoid the confusion caused by unused arguments.
> Usefixtures in integration tests who activelly does not use the fixture

- Containerfile
Remove `jq` tool from service dependency
> Remove `jq` tool from service dependency

- tests/unit/app/endpoints/test_authorized.py
- tests/unit/app/endpoints/test_ols.py
- tests/unit/llms/test_llm_loader.py
- tests/unit/utils/test_auth_dependency.py
Usefixtures in integration tests
Fixtures can be injected either by passing them as parameters to the test
function, or by using the `@pytest.mark.usefixtures` decorator.
If the test function depends on the fixture being activated, but does not
use it in the test body or otherwise rely on its return value, prefer
the `@pytest.mark.usefixtures` decorator, to make the dependency explicit
and avoid the confusion caused by unused arguments.
> Use fixtures in unit tests

- examples/olsconfig.yaml
- ols/app/models/config.py
- ols/src/query_helpers/docs_summarizer.py
- tests/config/valid_config.yaml
- tests/unit/app/models/test_config.py
- tests/unit/utils/test_config.py
Without this, you can see warning at the app start
```
/home/ometelka/projects/lightspeed-service/.venv/lib/python3.11/site-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_parameters" has conflict with protected namespace "model_".
You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
warnings.warn(
```
> Fix user warning in model config

- tests/e2e/pytest.ini
- tests/e2e/test_api.py
- tests/e2e/utils/response_evaluation.py
- tests/scripts/test-e2e-cluster.sh
- tests/test_data/question_answer_pair.json
- Capability to evaluate different provider+models using same pre-defined answer (currently similarity score)Save result with all model responses.
- Save summary score which can be used to compare different models (currently average of similarity score is used)
- Enable run from CI (currently not used to gate PRs)
- Combined with existing consistency check, just to avoid duplicate llm calls. If response is not available then only call api to get response.
Note: groundtruth answer is not relevant for this PR. Currently BAM+Granite result is used as ground-truth to test the approach.
[Sample summary result - json](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_lightspeed-service/1147/pull-ci-openshift-lightspeed-service-main-e2e-ols-clust …
> OLS-431: evaluation using groundtruth

- tests/e2e/test_api.py
When we run e2e test case in local, API url is still fetched from cluster and eventually get replaced by empty string..
get hostname only when we are running using a cluster.
> fix: retain api url for local e2e run

- tests/e2e/test_api.py
Refactor: use existing function to run oc command from cluster utils
> Refactor: use existing function to run oc command from cluster utils

- pdm.lock
- pyproject.toml
> Bump-up Mypy to 1.10.1

- Makefile
Ignore error when Mypy can not be uninstalled - that's perfectly ok (and Mypy will be removed from release job anyway)
> Ignore error when Mypy can not be uninstalled

- tests/unit/utils/test_config.py
Minor fixes in config unit tests:
- removed patches/mocks that are not needed anymore (config loader has changed)
- additional checks for redacted_query existence (to avoid possible NPEs detected by linters)
- ensure that config (empty one) is loaded even when some test are skipped or just one test selected to be ru
(each test must be separated, w/o having any context)
> Minor fixes in config unit tests

- scripts/data_collection/update_google_sheet.py
Fix print whole Google sheet URL, not just the ID
> Fix print whole Google sheet URL, not just the ID

- ols/src/query_helpers/docs_summarizer.py
- ols/src/query_helpers/question_validator.py
provider name can be whatever the admin wants.  provider type has to be one of our explicit known values.  For purposes of us understanding which providers customers are using, we want the type(azure_openai, openai, watsonx, etc), not their arbitrary name for the provider config.
- Closes #
> Use provider type, not provider name, as metrics label

- ols/app/models/config.py
- ols/user_data_collection/data_collector.py
- tests/unit/app/models/test_config.py
Add some config default values and load those in data collector.
Only subconfigs that are needed for data collector are initialized here. The proper approach should be to have defaults for all fields (subconfigs with its defaults instead of None's), but more changes are required in order to make it happen.
> Add some config default values and load those in data collector

- ols/src/llms/providers/provider.py
Add azure_ad_token as a valid parameter. This should be there as either this or `api_key` is used for auth to access azure.
> Add azure_ad_token as valid parameter

- ols/constants.py
- scripts/generate_packages_to_prefetch.py
- tests/mock_classes/mock_llm_chain.py
- tests/unit/app/models/test_config.py
- tests/unit/llms/providers/test_azure_openai.py
- tests/unit/utils/test_token_handler.py
When the colon is not used, the rule is interpreted as `noqa: ALL` which is wrong as it can hide another problems in the code.
> Use colon when specifying rule code

- pdm.lock
- pyproject.toml
Bump-up OpenAI to version 1.31.1
> OLS-779: Bump-up OpenAI to version 1.31.1

- pdm.lock
- pyproject.toml
Bump-up llama_index_embeddings_huggingface to 0.2.1
> OLS-779: Bump-up llama_index_embeddings_huggingface to 0.2.1

- ols/src/rag_index/index_loader.py
- pyproject.toml
Enable new **pygrep-hooks** rules
> Enable new pygrep-hooks rules

- ols/app/models/config.py
TLS settings itself is not optional - but it's attributes are
(it makes type checker a bit more precise w/o the need to add `tls != None` everywhere)
> TLS settings itself is not optional - but it's attributes are

- tests/e2e/test_api.py
test_transcripts_storing_cluster  test case is failing for openai (no rag content). This is due to query validation marked this as non-ocp query sometime. Modifying the text, to make it more relevant (this is an assumption). As the error is intermittent, not able reproduce. 
> query: what is kubernetes?
> 
> 
> ```
> this is attachment
> ```
modified to `this is attachment` -> `Kubernetes is a core component of OpenShift.`
Also added `assert transcript["query_is_valid"]` to identify the issue (if occurs again).
This scenario may become obsolete, once we start processing attachment separately.
> fix test case with sample attachment - pass query_val

- pdm.lock
- pyproject.toml
Bump-up lanchchain-ibm to 0.1.9
> OLS-779: Bump-up lanchchain-ibm to 0.1.9

- ols/app/endpoints/ols.py
- ols/app/models/models.py
- ols/src/cache/cache.py
- ols/src/cache/in_memory_cache.py
- ols/src/cache/postgres_cache.py
- ols/src/cache/redis_cache.py
- tests/integration/test_redis.py
- tests/unit/app/endpoints/test_ols.py
- tests/unit/app/models/test_models.py
- tests/unit/cache/test_in_memory_cache.py
- tests/unit/cache/test_postgres_cache.py
- tests/unit/cache/test_redis_cache.py
Add CacheEntry model.
The history format we send in the prompt is unchanged.
The follow-up is adding the attachments to the model.
The insert_or_append method can be used to store only single cache entry - which is exactly what is happening in the ols endpoint.
Question:
- Should Redis cache be updated? Or finally, removed?
- not now
> OLS-697: Add CacheEntry model

- pdm.lock
- pyproject.toml
[OLS-805](https://issues.redhat.com//browse/OLS-805): CVE-free `certifi` package
- Related Issue #CVE-805
> OLS-805: CVE-free certifi package

- pdm.lock
- pyproject.toml
Bump-up OpenAI to version 1.35.7
(that library seems to progress very quickly, but the newest version are not compat with other packages ATM)
> OLS-779: Bump-up OpenAI to version 1.35.7

- tests/config/config_for_integration_tests.yaml
- tests/integration/test_authorized.py
- tests/integration/test_feedback.py
- tests/integration/test_liveness_readiness.py
- tests/integration/test_metrics.py
- tests/integration/test_ols.py
- tests/integration/test_openapi.py
Integration tests should ideally hit as many source code lines as possible. We have a big modules `models.py` and `config.py` so would be nice to test them. Thus complex configuration file to be used just by integration tests were created. It is loaded for all tests and used accordingly.
The code coverage is better by approx. 70 lines, that's pretty nice number.
> Complex config for integration tests

- scripts/evaluation/query_rag.py
Sometime it is essential to verify retrieved RAG chunks.
- to analyze any change in response during evaluation due to RAG content
- to check what exactly we are sending to LLM.
- to check order and score for the chunks.
We can run this script on adhoc basis to do above analysis.
> Add script to get rag chunks for spot verification

- pdm.lock
- pyproject.toml
Bump-up Pydantic to version 2.8.2
> OLS-779: Bump-up Pydantic to version 2.8.2

- pdm.lock
- pyproject.toml
`SQLAlchemy` must be up to date to generate hashes properly
(please note this is both direct and indirect dependency, so it's tricky)
- Related Issue #[OLS-832](https://issues.redhat.com//browse/OLS-832)
> OLS-832: SQLAlchemy must be up to date to generate hashes properly

- pyproject.toml
Change rule name according to updated Ruff naming
The following rules have been remapped to new rule codes:
- `ASYNC102` has been merged into `ASYNC220` and `ASYNC221`
- `TRIO100` to `ASYNC100`
- `TRIO105` to `ASYNC105`
- `TRIO110` to `ASYNC110`
- `TRIO115` to `ASYNC115`
> Change rule name according to updated Ruff naming

- scripts/print_ec_failures.py
Script to print EC failures
- Related Issue #[OLS-703](https://issues.redhat.com//browse/OLS-703)
> OLS-703: Script to print EC failures

- pdm.lock
- pyproject.toml
Bump-up Gradio to version 4.37.2
> OLS-779: Bump-up Gradio to version 4.37.2

- Makefile
Include `runner.py` into coverage report
We seem to be adding more and more code into `runner.py` that was supposed to be used just as simple 10-liner to start Uvicorn. So we need to include this file into coverage report too.
> Include runner.py into coverage report

- ols/app/models/config.py
- tests/unit/app/models/test_config.py
Don't read tenant id etc if dir contains apikey only
> Don't read tenant id etc if dir contains apikey only

- scripts/evaluation/eval_data/question_answer_pair.json
Added additional answers (changed due to 4.16 docs)
Due to [variation in chunks](https://docs.google.com/spreadsheets/d/1H5ctQa4TZHHbNaU6FpsKHi6RlPtbY3EXxDT_Z2gfxgM/edit?usp=sharing), responses have changed for few queries. Cut-off values are set as low as possible to identify even slight variation.
With 4.16 docs, chunks have changed which impacted below queries (out of 10 queries). Manually verified the response and responses for below 3 queries seem to be acceptable (at least can be explained based on chunks) 
- what is kubernetes? (granite - bam/watsonx)
- what is openshift virtualization? (granite - bam/watsonx, gpt - azure/openai)
- Is there a doc on updating clusters? (granite - bam/watsonx, gpt - openai)
This should enable CI jobs ([with 4.16 …
> OLS-827: Add answers changed due to 4.16

- ols/src/llms/providers/azure_openai.py
- ols/src/llms/providers/bam.py
- ols/src/llms/providers/openai.py
- ols/src/llms/providers/watsonx.py
Don't override credentials when they are not specified in provider specific config.
> Don't override credentials when they are not specified in provider specific config

- ols/app/models/config.py
Fix linter warnings when provider-specific config is `None`
> Fix linter warnings when provider-specific config is None

- pdm.lock
- pyproject.toml
update `ibm-cos-sdk` library explicitly
- we might be able to bump up `urllib` later
- Related Issue #[OLS-804](https://issues.redhat.com//browse/OLS-804)
> OLS-804: update ibm-cos-sdk library explicitly

- scripts/evaluation/eval_data/question_answer_pair.json
Update granite eval7 answer for 4.16
Note: 
How the response is formed for this query is subjective. This may not be the ideal answer but aligned as per chunk.
Generally granite gives us consistent answers, but for this query `Is there a doc on updating clusters?` some deviation is observed and very much dependent on slight variations in chunk texts (It got changed since I checked with 4.16 last time).
This should enable `OCP 4.16 rehearsal job` to pass for https://github.com/openshift/lightspeed-service/pull/1288
> Evaluation - Update granite eval7 answer for 4.16

- pdm.lock
- pyproject.toml
Update urllib3 to version 2.2.2 to avoid CVE
When using urllib3's proxy support with ProxyManager, the Proxy-Authorization header is only sent to the configured proxy, as expected.
https://nvd.nist.gov/vuln/detail/CVE-2024-37891
- Related Issue #[OLS-804](https://issues.redhat.com//browse/OLS-804)
> OLS-804: Update urllib3 to version 2.2.2 to avoid CVE

- .tekton/lightspeed-service-pull-request.yaml
- .tekton/lightspeed-service-push.yaml
Update buildah-6b to latest 0.1
```
"key": "oci://quay.io/konflux-ci/tekton-catalog/task-buildah-6gb:0.1",
"value": [
{
"effective_on": "2024-08-19T00:00:00Z",
"ref": "sha256:b79549b4fdd35cb0433ec3dda2f6a1bbbced8ae84f6c058b2cf50dd7dcd4caa8"
},
{
"effective_on": "2024-08-18T00:00:00Z",
"expires_on": "2024-08-19T00:00:00Z",
"ref": "sha256:a98162ee01d16a69eff7a366001958065ff68e9bc2063a8171585fa7fc76b898"
},
```
#[OLS-821](https://issues.redhat.com//browse/OLS-821)
> OLS-821: Update buildah-6b to latest 0.1

- .tekton/lightspeed-service-pull-request.yaml
- .tekton/lightspeed-service-push.yaml
Update Konflux references without buildah (keep old version)
- Related Issue #[OLS-821](https://issues.redhat.com//browse/OLS-821)
> OLS-821: Update Konflux references without buildah-6b (keep old version)

- .tekton/lightspeed-service-pull-request.yaml
- .tekton/lightspeed-service-push.yaml
Update buildah-6b to version 0.2
> Update buildah-6b to version 0.2

- .tekton/lightspeed-service-pull-request.yaml
- .tekton/lightspeed-service-push.yaml
Bump-up `task-init`
```
"key": "oci://quay.io/konflux-ci/tekton-catalog/task-init:0.2",
"value": [
{
"effective_on": "2024-08-23T00:00:00Z",
"ref": "sha256:092c113b614f6551113f17605ae9cb7e822aa704d07f0e37ed209da23ce392cc"
},
{
"effective_on": "2024-08-10T00:00:00Z",
"expires_on": "2024-08-23T00:00:00Z",
"ref": "sha256:99c98d3e5195e9920482f2187590d6f9150c4b8a2001b1ce5dcd5077abda9481"
},
```
> Bump-up `task-init`

- .tekton/lightspeed-service-pull-request.yaml
- .tekton/lightspeed-service-push.yaml
Buildah-6g applicable for 2024-07-23
> Buildah-6g applicable for 2024-07-23

- Makefile
- pdm.lock
- pyproject.toml
[OLS-884](https://issues.redhat.com//browse/OLS-884): use the bug-free latest setuptools on CI
- Related Issue #[OLS-884](https://issues.redhat.com//browse/OLS-884)
> OLS-884: use the bug-free latest setuptools on CI

- pdm.lock
- pyproject.toml
According to https://github.com/pypa/setuptools/issues/4519#issuecomment-2256426150 it would be possible to
use https://github.com/pypa/setuptools/releases/tag/v72.1.0
- Related Issue #[OLS-884](https://issues.redhat.com//browse/OLS-884)
> OLS-884: Bump-up to latest setuptools 72.1.0

- ols/src/cache/in_memory_cache.py
- ols/src/cache/postgres_cache.py
Assign before `return` statement is not needed
> Assign before return statement is not needed

- ols/app/models/config.py
- ols/utils/config.py
Redundant `open` mode parameters are unnecessary and should be removed to
avoid confusion.
```python
with open("foo.txt", "r") as f:
...
```
Use instead:
```python
with open("foo.txt") as f:
...
```
- [Python documentation: `open`](https://docs.python.org/3/library/functions.html#open)
> Removed redundant open modes

- pdm.lock
- pyproject.toml
Bump-up WatsonX-AI library to fixed version 1.1.2
> Bump-up WatsonX-AI library to fixed version 1.1.2

- tests/config/operator_install/catalog.yaml
- tests/config/operator_install/olsconfig.crd.azure_openai.yaml
- tests/config/operator_install/olsconfig.crd.bam.yaml
- tests/config/operator_install/olsconfig.crd.openai.yaml
- tests/config/operator_install/olsconfig.crd.watsonx.yaml
- tests/config/operator_install/operatorgroup.yaml
- tests/config/operator_install/route.yaml
- tests/config/operator_install/subscription.yaml
- tests/e2e/test_api.py
- tests/e2e/utils/cluster.py
- tests/e2e/utils/metrics.py
- tests/e2e/utils/wait_for_ols.py
- tests/scripts/must_gather.py
- tests/scripts/test-e2e-cluster.sh
- tests/scripts/utils.sh
attempting to refactor the e2e ols installer logic to install using the latest OLS
operator instead of manually creating resources
- Closes #
> OLS-688: install ols using operator for e2e

- ols/utils/config.py
Refactor: query-redactor is not optional anymore
> Refactor: query-redactor is not optional anymore

- pdm.lock
- pyproject.toml
Bump-up Mypy to version 1.11.1
> Bump-up Mypy to version 1.11.1 (to fix CI issues)

- ols/app/endpoints/ols.py
Refactoring: `query_redactor` can not be `None`
> Refactoring: `query_redactor` can not be `None`

- tests/config/cluster_install/ols_configmap.yaml
Currently, there are no pod logs for the server in CI artifacts. It just shows
```
This file contained potentially sensitive information and has been removed.
```
Check the reason here - https://redhat-internal.slack.com/archives/C068JAU4Y0P/p1721372504787769
This fixes the issue.
> Change logging level for libs in CI

- Makefile
- pyproject.toml
- tests/benchmarks/pytest.ini
- tests/benchmarks/test_question_validator.py
Benchmarks: real example
Any benchmark can be write in the same style - as unit test, but with `benchmark` parameter + the benchmarked
function or method needs to be called by `benchmark(function_method, parameters)`
> OLS-906: Benchmarks: real example

- pdm.lock
- pyproject.toml
Bump-up NLTK to stable version 3.9.1
Finally the stable version has been released.
- Related Issue #[OLS-934](https://issues.redhat.com//browse/OLS-934)
> OLS-934: Bump-up NLTK to stable version 3.9.1

- .tekton/lightspeed-service-pull-request.yaml
- .tekton/lightspeed-service-push.yaml
Reinstate build.args to pick up Konflux RAG for Konflux builds.
build.args got lost in a migration and we've been building on Konflux with the Prow RAG image.
- Closes #
> Reinstate build.args to pick up Konflux RAG for Konflux builds

- Makefile
- pdm.lock
- pyproject.toml
Bump-up Ruff to 0.6.1
- Related Issue #[OLS-924](https://issues.redhat.com//browse/OLS-924)
> OLS-924: Bump-up Ruff to 0.6.1

- pdm.lock
- pyproject.toml
Bump-up llama-index to 0.10.62
- Related Issue #[OLS-924](https://issues.redhat.com//browse/OLS-924)
> OLS-924: Bump-up llama-index to 0.10.62

- pdm.lock
- pyproject.toml
Bump-up SQLAlchemy to 2.0.32
- Related Issue #[OLS-924](https://issues.redhat.com//browse/OLS-924)
> OLS-924: Bump-up SQLAlchemy to 2.0.32

- pdm.lock
- pyproject.toml
> Bump-up Pytest to 8.3.2

- pdm.lock
- pyproject.toml
Bump-up OpenAI to 1.42.0
- Related Issue #[OLS-924](https://issues.redhat.com//browse/OLS-924)
> OLS-924: Bump-up OpenAI to 1.42.0

- pdm.lock
- pyproject.toml
Bump-up `langchain-ibm` to 0.1.12
> Bump-up langchain-ibm to 0.1.12

- scripts/data_collection/user_data_aggregator.py
Refactoring: don't use f-strings to log exceptions
> Refactoring: don't use f-strings to log exceptions

- .tekton/lightspeed-service-pull-request.yaml
- .tekton/lightspeed-service-push.yaml
Use buildah-8g task with higher memory limits
> OLS-757: Use buildah-8g task with higher memory limits

- pdm.lock
- pyproject.toml
Bump-up sentence-transformers to 3.0.1
- Related Issue #[OLS-855](https://issues.redhat.com//browse/OLS-855)
> OLS-855: Bump-up sentence-transformers to 3.0.1

- ols/constants.py
- ols/src/prompts/prompt_generator.py
- ols/src/prompts/prompts.py
- ols/src/query_helpers/docs_summarizer.py
- ols/utils/token_handler.py
- scripts/evaluation/eval_data/question_answer_pair.json
- tests/e2e/test_api.py
- tests/integration/test_ols.py
- tests/unit/prompts/test_prompt_generator.py
- tests/unit/query_helpers/test_docs_summarizer.py
- tests/unit/utils/test_token_handler.py
Every model/provider has some recommendation or specific way of adding special tags, which help models to understand instruction better. Also azure uses tags/roles to do the content/jailbreak filter.
- Modified the logic to have special tags included in the prompt for granite based on this [documentation](https://dataplatform.cloud.ibm.com/docs/content/wsj/analyze-data/fm-models-ibm-chat.html?context=wx#chat).
- Modified for GPT prompt to have correct role. This will helps us to enable azure ai content filter.
This change will potentially resolve below:
- We can enable azure jailbreak filter as we will have separate role for system instruction and azure won't flag our system instruction as jailbreak. [OLS-776](https://issues.redhat.com//browse/OLS-776) 
- This will also enable us to have …
> model specific dynamic prompt creation

- pdm.lock
- pyproject.toml
> Bump-up Mypy to 1.11.2

- pdm.lock
- pyproject.toml
> Bump-up Redis to 5.0.8

- README.md
- ols/constants.py
- tests/unit/app/models/test_config.py
Increase max resp token default to 1024. YAML in response may take more tokens, so increasing from 512.
This is just a default value; it is recommended to use correct context window and reasonable response token based on model & use.
> increase max resp token default to 1024

- .tekton/lightspeed-service-pull-request.yaml
- .tekton/lightspeed-service-push.yaml
Removed sbom-json-check task from Konflux pipelines, sbom-json-check is getting deprecated.
- Closes #
> Removed sbom-json-check task from Konflux pipelines

- pdm.lock
- pyproject.toml
Bump-up pytest-asyncio to 0.24.0
> Bump-up pytest-asyncio to 0.24.0

- scripts/evaluation/eval_data/question_answer_pair.json
add alternate eval3 ans for openai (4.15)
[Reference](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_lightspeed-service/1512/pull-ci-openshift-lightspeed-service-main-e2e-ols-cluster-4-15/1830855746502266880)
[Reference](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_lightspeed-service/1534/pull-ci-openshift-lightspeed-service-main-e2e-ols-cluster-4-15/1831224066074218496)
> eval: add alternate eval3 ans for openai

- pdm.lock
- pyproject.toml
Fix CVE: bump-up cryptography to 43.0.1
- Related Issue #[OLS-1008](https://issues.redhat.com//browse/OLS-1008)
> OLS-1008: Fix CVE: bump-up cryptography to 43.0.1

- tests/benchmarks/test_attachment_appender.py
- tests/benchmarks/test_docs_summarizer.py
- tests/benchmarks/test_prompt_generator.py
- tests/benchmarks/test_redactor.py
Disable meaningless warnings (linters are too dumb to figure out we pass fixtures)
> Refactor: disable meaningless warnings

- scripts/data_collection/user_data_aggregator.py
The `logging` module provides a mechanism for passing additional values to
be logged using the `extra` keyword argument. This is more consistent, more
efficient, and less error-prone than formatting the string directly.
Using f-strings to format a logging message requires that Python eagerly
format the string, even if the logging statement is never executed (e.g.,
if the log level is above the level of the logging statement), whereas
using the `extra` keyword argument defers formatting until required.
> Removed f-strings from logging

- pdm.lock
- pyproject.toml
Bump-up `ibm-watsonx-ai` to 1.1.8
> Bump-up ibm-watsonx-ai to 1.1.8

- pdm.lock
- pyproject.toml
Fix CVE in jinja2 package version 3.1.3
- Related Issue #[OLS-1051](https://issues.redhat.com//browse/OLS-1051)
> OLS-1051: Fix CVE in jinja2 package version 3.1.3

- ols/app/models/config.py
- ols/constants.py
- tests/unit/app/models/test_config.py
Use single default value for context window; instead of maintaining values for all potential provider/model..
The value keeps on changing with different version (ex: azure/gpt3.5). So It is hard to maintain in-terms of code. Also we may still set an inaccurate value.
> OLS-1004: Use single default value for context window

- scripts/evaluation/eval_data/question_answer_pair.json
cutoff increase for eval6 - openai (due to randomness in response)
[Reference](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_lightspeed-service/1572/pull-ci-openshift-lightspeed-service-main-e2e-ols-cluster-4-16/1833511097504632832)
Note:
Now this issue has become more frequent..
Potentially we can move to 4o-mini or have a larger cut-off for openai..
Also there is discussion to remove this check completely.
I will create relevant stories.
> eval: cutoff increase for eval6 - openai

- pdm.lock
- pyproject.toml
> OLS-1032: Bump-up langchain to 0.2.16

- pdm.lock
- pyproject.toml
Bump-up certify package to 2024.7.30
> OLS-1032: Bump-up certify package to 2024.7.30

- ols/app/models/config.py
- ols/app/models/models.py
- scripts/upload_artifact_s3.py
Refactor: parens not needed after `not` operator - it has low precendence
> Refactor: parens not needed after `not` operator - it has low precendence

- pdm.lock
- pyproject.toml
Bump-up Uvicorn to version 0.30.6
> OLS-1032: Bump-up Uvicorn to version 0.30.6

- pdm.lock
- pyproject.toml
> OLS-1032: Bump-up FastAPI to 0.114.2

- pdm.lock
- pyproject.toml
> OLS-1032: Bump-up pydantic to 2.9.1

- ols/src/cache/postgres_cache.py
- tests/unit/cache/test_postgres_cache.py
Fix for the "invalid input syntax for type bytea at character XXX" Postgres error.
Make cache content a binary buffer before insertion into a bytea field in Postgres.
This follows https://www.psycopg.org/docs/usage.html#index-8.
- Related Issue # https://issues.redhat.com/browse/OLS-438
- Closes #
> Make cache content a binary buffer before insertion into a bytea field in Postgres

- ols/app/models/config.py
Keep exception context when raising new one
Why:
Python's exception chaining shows the traceback of the current exception, but also of the original exception. When you raise a new exception after another exception was caught it's likely that the second exception is a friendly re-wrapping of the first exception. In such cases `raise from` provides a better link between the two tracebacks in the final error.
- Closes #
> Keep exception context when raising new one

- tests/config/operator_install/imagedigestmirrorset.yaml
- tests/e2e/test_api.py
- tests/scripts/utils.sh
add ImageDigestMirrorSet to allow using bundle from unreleased images
- Related Issue # [OLS-1065](https://issues.redhat.com/browse/OLS-1065)
- Closes #
> OLS-1065: fix e2e test to pull unreleased component images

- Makefile
Show PDM version on CI
- Related Issue #[OLS-1085](https://issues.redhat.com//browse/OLS-1085)
> OLS-1085: Show PDM version on CI

- tests/e2e/test_api.py
- More verbose e2e tests setup for easier debugging
- Increased `oc` command wait time
Fixes issue #[OLS-1088](https://issues.redhat.com//browse/OLS-1088)
> OLS-1088: More verbose e2e tests setup + increased `oc` command wait time

- scripts/evaluation/eval_data/question_answer_pair.json
Increase cut-off to 0.3 from 0.25 for openai response for eval-6 query (due to randomness of the model)
[Reference](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_lightspeed-service/1661/pull-ci-openshift-lightspeed-service-main-e2e-ols-cluster-4-15/1840904036534980608)
> eval: increase cutoff for openai-eval6

- Makefile
- pdm.lock
- pyproject.toml
Pydocstyle as devel dependency
- Related Issue #[OLS-1105](https://issues.redhat.com//browse/OLS-1105)
> OLS-1105: Pydocstyle as devel dependency

- README.md
- examples/olsconfig.yaml
- ols/app/models/config.py
- ols/constants.py
- ols/src/llms/providers/azure_openai.py
- tests/config/valid_config_with_azure_openai_api_version.yaml
- tests/unit/app/models/test_config.py
- tests/unit/utils/test_config.py
Add api_version to be configurable [Optional]. This is currently required for azure. Default version is used when it is not set for azure.
> OLS-1067 config: add api_version required for azure

- ols/src/llms/providers/provider.py
Allow non-private attribute to be accessed outside dataclass
> Allow non-private attribute to be accessed outside dataclass

- tests/e2e/test_api.py
- tests/e2e/utils/cluster.py
We can just try to delete since we have the error catch underneath.
> Removing the get from the checks if the resources exist

- tests/e2e/test_api.py
Adding scaling of operator manager pod and deletion of route
> correct-ci-failure-multiple-test-runs

- scripts/evaluation/utils/constants.py
eval default cut-off increase.
[Reference](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_lightspeed-service/1736/pull-ci-openshift-lightspeed-service-main-e2e-ols-cluster-4-17/1844367918855360512)
> eval: increase default cut-off

- Makefile
Back to default PDM
- Closes #
> Back to default PDM

- ols/app/models/config.py
- tests/config/system_prompt.txt
- tests/config/valid_config.yaml
- tests/unit/app/models/test_config.py
- tests/unit/utils/test_config.py
Ability to read system prompt from configuration
- Related Issue #[OLS-1121](https://issues.redhat.com//browse/OLS-1121)
- Closes #
> OLS-1121: Ability to read system prompt from configuration

- ols/src/query_helpers/docs_summarizer.py
- tests/unit/query_helpers/test_docs_summarizer.py
Customizable system prompt.
It is now possible to use custom system prompt by providing path to the file that contains it. The configuration might look
like:
```yaml
ols_config:
logging_config:
app_log_level: info
lib_log_level: warning
default_provider: my_bam
default_model: ibm/granite-13b-chat-v2
system_prompt_path: "tests/config/system_prompt.txt"
```
- Related Issue #[OLS-1121](https://issues.redhat.com//browse/OLS-1121)
> OLS-1121: Customizable system prompt

- runner.py
<Patch from upstream>
Simplified the condition to start uvicorn. The TLS flags will be None in case they are not being used, so there is no need for branching that. The condition was moved to determinate the port of the running service.
> Refactor `start_uvicorn` to be less verbose with conditionals

- ols/src/llms/providers/azure_openai.py
- ols/src/llms/providers/openai.py
- ols/src/llms/providers/provider.py
- ols/src/llms/providers/rhelai_vllm.py
- ols/src/llms/providers/rhoai_vllm.py
- tests/unit/llms/providers/test_azure_openai.py
- tests/unit/llms/providers/test_openai.py
- tests/unit/llms/providers/test_rhelai_vllm.py
- tests/unit/llms/providers/test_rhoai_vllm.py
Refactored to create HTTPX client in one centralized place
The new method will be used later to specify TLS security profile
- Related Issue #[OLS-1106](https://issues.redhat.com//browse/OLS-1106)
> OLS-1106: Refactored to create HTTPX client in one centralized place

- Makefile
- README.md
- docs/openapi.json
- examples/olsconfig.yaml
- examples/openshift-lightspeed-tls.yaml
- ols/app/models/models.py
- ols/constants.py
- ols/src/llms/llm_loader.py
- scripts/evaluation/eval_data/question_answer_pair.json
- scripts/evaluation/utils/constants.py
- scripts/questions_gen.py
- tests/benchmarks/test_prompt_generator.py
- tests/config/empty_openai_api_key.yaml
- tests/config/operator_install/olsconfig.crd.azure_openai.yaml
- tests/config/operator_install/olsconfig.crd.openai.yaml
- tests/config/with_openai_api_key.yaml
- tests/e2e/conftest.py
- tests/e2e/test_api.py
- tests/scripts/test-e2e-cluster.sh
- tests/unit/app/models/test_config.py
- tests/unit/app/models/test_models.py
- tests/unit/prompts/test_prompt_generator.py
> OLS-1055: switch to gpt-4o-mini

- ols/utils/token_handler.py
- tests/unit/utils/test_token_handler.py
Fix: Use formatted history/messages for granite prompt.
> fix: history structure for granite prompt

- pdm.lock
- pyproject.toml
Bump-up FastAPI to 0.115.4
- #[OLS-1174](https://issues.redhat.com//browse/OLS-1174)
> OLS-1174: Bump-up FastAPI to 0.115.4

- scripts/evaluation/eval_data/question_answer_pair.json
Add alternate answer for openai due to randomness.. Adjustment post model change.
[Reference](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_lightspeed-service/1807/pull-ci-openshift-lightspeed-service-main-e2e-ols-cluster-4-17/1849914307219820544)
cut-off increase [[reference](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_lightspeed-service/1829/pull-ci-openshift-lightspeed-service-main-e2e-ols-cluster-4-17/1853356810233188352)]
> eval: add alternate answers after model transition

- runner.py
Don't use string interpolation in `runner.py`
> Don't use string interpolation in `runner.py`

- Makefile
- pdm.lock
- pyproject.toml
Bump-up Mypy to version 1.13
The CI failure is fixed (unable to install all the packages due to conflict)
- Related Issue #[OLS-1205](https://issues.redhat.com//browse/OLS-1205)
- Closes #
> OLS-1205: Bump-up Mypy to version 1.13, updated transitive dependencies, fixed CI failures

- tests/config/operator_install/olsconfig.crd.rhelai_vllm.yaml
- tests/scripts/test-e2e-cluster.sh
[OLS-987](https://issues.redhat.com//browse/OLS-987): Add RHOAI as a provider in prow CI
- Closes # https://issues.redhat.com/browse/OLS-987
> OLS-987: Add RHELAI as a provider in prow CI

- pdm.lock
- pyproject.toml
New dependency: `pytest-subtests` to be used in unit and integration tests
> New dependency: pytest-subtests to be used in unit and integration tests

- ols/src/auth/auth.py
- runner.py
- tests/unit/auth/test_auth.py
- tests/unit/auth/test_k8s.py
[OLS-1204](https://issues.redhat.com//browse/OLS-1204): init k8s module just when configured to
If will allow us to be in-sync with upstream repo (where k8s was commented out on source level)
No changes in operator or in default configuration is needed
- Related Issue #[OLS-1204](https://issues.redhat.com//browse/OLS-1204)
> OLS-1204: init k8s module just when configured to

- pdm.lock
- pyproject.toml
[OLS-1174](https://issues.redhat.com//browse/OLS-1174): bump-up OpenAI to version 1.53.3
> OLS-1174: bump-up OpenAI to version 1.53.3

- pdm.lock
- pyproject.toml
Bump-up Uvicorn to version 0.32.0
> OLS-1174: Bump-up Uvicorn to version 0.32.0

- tests/e2e/test_api.py
as it's not relevant as its not expected for k8s and cluster utils to have the same cluster id
- [x ] Refactor - removing unused test (not relevant)
- Closes #
> OLS-652 - Removing test get cluster id function 

- pdm.lock
- pyproject.toml
Bump-up Pydantic to version 2.23.4
> OLS-1174: Bump-up Pydantic to version 2.23.4

- ols/src/llms/providers/fake_provider.py
[OLS-1226](https://issues.redhat.com//browse/OLS-1226): remove warning about outdated import
- Related Issue #[OLS-1226](https://issues.redhat.com//browse/OLS-1226)
> OLS-1226: remove warning about outdated import

- tests/e2e/test_api.py
- tests/e2e/utils/ols_installer.py
Removing the service image replacement from konflux jobs since now that we moved to a separate application, we no longer have access to the ols application's snapshot
- [x ] Bug fix - fixing konflux test jobs
- Closes #
> OLS-1110 - Auxiliary task: Remove service image installation from konflux jobs

- .tekton/lightspeed-service-pull-request.yaml
- .tekton/lightspeed-service-push.yaml
Builds are using 8 GiB of memory, so request that memory. See `stone-prd-rh01`:
```
sum by (namespace, pod, container) (
max_over_time(
container_memory_working_set_bytes{container=~".*step-build.*", pod=~".*-build-container-pod", namespace="crt-nshift-lightspeed-tenant", pod=~"lightspeed-service-.*"}
[1d])
)
```
- Konflux configuration change
- Related Issue https://issues.redhat.com/browse/KONFLUX-5392
> build(KONFLUX-5392): Request more memory for build container step as it is actually being used

- ols/runners/__init__.py
- ols/runners/uvicorn.py
- runner.py
- tests/unit/runners/test_uvicorn_runner.py
[OLS-1229](https://issues.redhat.com//browse/OLS-1229): refactor Uvicorn runner into its own module
- Related Issue #[OLS-1229](https://issues.redhat.com//browse/OLS-1229)
> OLS-1229: refactor Uvicorn runner into its own module

- ols/src/query_helpers/docs_summarizer.py
- ols/utils/token_handler.py
fix: end of token in granite-13b response
[Reference](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_lightspeed-service/1946/pull-ci-openshift-lightspeed-service-main-4.15-e2e-ols-cluster/1860756078703153152)
[OLS-1261](https://issues.redhat.com/browse/OLS-1261)
> fix: end of token in granite-13b response

- Containerfile
use rhel-9-4-els/rhel instead of ubi-minimal base image
- Related Issue #  [OLS-1192](https://issues.redhat.com//browse/OLS-1192)
- Closes #
> OLS-1192: FIPS compliance - use rhel-9-4-els/rhel base image

- tests/unit/extra_certs/__init__.py
- tests/unit/runners/__init__.py
- tests/unit/user_data_collection/__init__.py
Added missing `__init__.py` into all unit tests
- Related Issue #[OLS-1233](https://issues.redhat.com//browse/OLS-1233)
> OLS-1233: Added missing `__init__.py` into all unit tests

- pdm.lock
- pyproject.toml
Bump-up Gradio to version 4.44.1 to avoid warning messages on startup
> Bump-up Gradio to version 4.44.1 to avoid warning messages on startup

- Containerfile
Switch back to UBI9 image as base image. The new UBI9 images are already FIPS-140-3 compliant.
- Related Issue # [OLS-1192](https://issues.redhat.com/browse/OLS-1192)
- Closes #
> config: base image switch back to ubi9 minimal, FIPS compliant version.

- pdm.lock
- pyproject.toml
[OLS-1262](https://issues.redhat.com//browse/OLS-1262): use CVE-free virtualenv
- Related Issue #[OLS-1262](https://issues.redhat.com//browse/OLS-1262)
> OLS-1262: use CVE-free virtualenv

- pdm.lock
- pyproject.toml
Setting distribution flag
It allow us, among other things to run `pdm show --version` to display service version.
`msgpack` has to be updated to pass CI checks (newer version is installed already on CI systems)
- Related Issue #[OLS-1168](https://issues.redhat.com//browse/OLS-1168)
> OLS-1168: Setting distribution flag

- Makefile
- README.md
- pyproject.toml
- runner.py
[OLS-1168](https://issues.redhat.com//browse/OLS-1168): Ability to print current version to stdout
- Related Issue #[OLS-1168](https://issues.redhat.com//browse/OLS-1168)
> OLS-1168: Ability to print current version to stdout

- scripts/evaluation/eval_data/question_answer_pair.json
add alternative ans for azure-eval9
[Reference](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_lightspeed-service/2031/pull-ci-openshift-lightspeed-service-main-4.17-e2e-ols-cluster/1866136104692879360)
> eval: add alternative ans for azure-eval9

- scripts/data_collection/user_data_aggregator.py
[OLS-1313](https://issues.redhat.com//browse/OLS-1313): Remove f-strings from all log in user data aggregator
- Related Issue #[OLS-1313](https://issues.redhat.com//browse/OLS-1313)
> OLS-1313: Remove f-strings from all log statements in user data aggregator

- pdm.lock
- pyproject.toml
[OLS-1311](https://issues.redhat.com//browse/OLS-1311): Bump-up Uvicorn to 0.32.0
> OLS-1311: Bump-up Uvicorn to 0.32.0

- pdm.lock
- pyproject.toml
Bump-up Mypy to 1.14.1
- Related Issue #[OLS-1321](https://issues.redhat.com//browse/OLS-1321)
- Closes #
> OLS-1321: Bump-up Mypy to 1.14.1

- pdm.lock
- pyproject.toml
Bump-up Jinja2 to 3.1.5 to fix vulnerability
- Related Issue #[OLS-1318](https://issues.redhat.com//browse/OLS-1318), #[OLS-1319](https://issues.redhat.com//browse/OLS-1319)
> OLS-1318: Bump-up Jinja2 to 3.1.5 to fix vulnerability

- pdm.lock
- pyproject.toml
> OLS-1311: Bump-up tqdm to 4.67.1

- tests/integration/test_authorized.py
- tests/integration/test_feedback.py
- tests/integration/test_liveness_readiness.py
- tests/integration/test_metrics.py
- tests/integration/test_ols.py
- tests/integration/test_openapi.py
- tests/integration/test_redis.py
Get rid of global variables in integration tests
> OLS-1323: Get rid of global variables in integration tests

- pdm.lock
- pyproject.toml
> OLS-1311: Bump-up aiohttp to 3.11.10

- pdm.lock
- pyproject.toml
Bump-up `cryptography` package to version 44.0.0
> OLS-1311: Bump-up cryptography package to version 44.0.0

- tests/e2e/utils/cluster.py
Refactoring: f-strings are possible in exception constructors
> OLS-1323: Refactoring: f-strings are possible in exception constructors

- pdm.lock
- pyproject.toml
Bump-up `faiss-cpu` to version `1.9.0.post1`
> OLS-1311: Bump-up faiss-cpu to version 1.9.0.post1

- tests/e2e/conftest.py
Assert attributes in `session.config`
Will make more clear why e2e tests are failing
> Assert attributes in session.config

- ols/constants.py
- tests/benchmarks/test_prompt_generator.py
- tests/integration/test_ols.py
- tests/unit/app/models/test_config.py
- tests/unit/prompts/test_prompt_generator.py
Removed unnecessary exact model name reference in test modules.
**Background**:
Recently we moved to granite 3 model for CI e2e test. There were several files got modified just to remove any reference to granite 2 in test code. But we don't have any actual logic which checks the exact model name, so having exact name in test cases is not really needed. And this also creates confusion that actual model name is used in app code.
_So removing exact model name reference in unit/integration tests (actual e2e test requires correct/exact model names)_
> chore: remove unnecessary exact model name reference during test

- tests/unit/app/metrics/test_token_counter.py
[OLS-1337](https://issues.redhat.com//browse/OLS-1337): Fixed import for generic token counter unit tests
- Related Issue #[OLS-1337](https://issues.redhat.com//browse/OLS-1337)
> OLS-1337: Fixed import for generic token counter unit tests

- examples/olsconfig.yaml
- ols/app/models/config.py
- ols/runners/uvicorn.py
- tests/unit/app/models/test_config.py
- tests/unit/runners/test_uvicorn_runner.py
Support for not default Uvicorn port number for dev
> [backport] Support for not default Uvicorn port number for dev

- ols/app/endpoints/ols.py
- ols/app/metrics/token_counter.py
- ols/app/models/models.py
- ols/src/query_helpers/docs_summarizer.py
- ols/src/query_helpers/question_validator.py
- tests/unit/app/endpoints/test_ols.py
- tests/unit/app/metrics/test_token_counter.py
[OLS-1228](https://issues.redhat.com//browse/OLS-1228): `TokenCounter` as separate dataclass
It allow us to pass it via reference as mutable state (filled by async stream processing etc.)
Basically it is a refactoring, not a new feature
- Related Issue #[OLS-1228](https://issues.redhat.com//browse/OLS-1228)
> OLS-1228: TokenCounter as separate dataclass

- docs/openapi.json
- ols/app/endpoints/authorized.py
- ols/app/endpoints/ols.py
- ols/app/endpoints/streaming_ols.py
[OLS-1352](https://issues.redhat.com//browse/OLS-1352): `user_id` as optional REST API parameter
- Related Issue #[OLS-1352](https://issues.redhat.com//browse/OLS-1352)
> OLS-1352: User ID as optional REST API parameter

- ols/src/query_helpers/docs_summarizer.py
- tests/unit/query_helpers/test_docs_summarizer.py
[upstream] Re-enable system prompt override
System Prompt Override added with #227 is no longer working.  System prompt was set using the
`_system_prompt` attribute of  `QueryHelper` class. However, the `DocsSummarizer` class, which extends
`QueryHelper`, now has `system_prompt` attribute, which does not contain the logic required for
System Prompt Override. We can simply use the `_system_prompt` attribute as it is set in the constructor
of `QueryHelper`.
> [upstream] Re-enable system prompt override

- examples/olsconfig.yaml
- ols/app/endpoints/streaming_ols.py
- ols/app/models/config.py
- tests/unit/app/endpoints/test_streaming_ols.py
[Upstream][Feature] Event stream format support
Implements changes for #299.  This will add a new option `enable_event_stream_format` to `ols_config`.
When `enable_event_stream_format` is set to `true` (default is `false`), it will add `data: ` to the beginning and 
`\n\n` at the end of stringfied JSON data. This option works only when `media-type` is set to `application/json`.
> [Upstream][Feature] Event stream format support

- ols/app/endpoints/ols.py
- tests/unit/app/endpoints/test_ols.py
Refactoring: `conversation-id` passing
- Related Issue #[OLS-1375](https://issues.redhat.com//browse/OLS-1375)
> OLS-1375: Refactoring: conversation-id passing

- tests/scripts/test-e2e-cluster-periodics.sh
Moving model evaluation tests outside watsonx tests in periodic pipelines so that it doesn't affect standard tests statistics and we can work on creating more model evaluation tests.
Also renaming suite id for certificates to not override the openai suite summary.
- Closes #
> Move model evaluation tests

- ols/app/endpoints/ols.py
- ols/app/models/models.py
- ols/src/cache/postgres_cache.py
- ols/src/cache/redis_cache.py
- ols/src/prompts/prompt_generator.py
- ols/src/query_helpers/docs_summarizer.py
- ols/utils/token_handler.py
- tests/integration/test_ols.py
- tests/integration/test_redis.py
- tests/unit/app/endpoints/test_ols.py
- tests/unit/app/models/test_models.py
- tests/unit/cache/test_in_memory_cache.py
- tests/unit/cache/test_postgres_cache.py
- tests/unit/cache/test_redis_cache.py
- tests/unit/prompts/test_prompt_generator.py
- tests/unit/query_helpers/test_docs_summarizer.py
- tests/unit/utils/test_token_handler.py
[OLS-1376](https://issues.redhat.com//browse/OLS-1376): Usage of langchain messages instead of plain strings
> OLS-1376: Usage of langchain messages instead of plain strings

- Makefile
- examples/olsconfig.yaml
- ols/app/models/config.py
- ols/constants.py
- ols/src/llms/llm_loader.py
- ols/src/llms/providers/watsonx.py
- ols/src/prompts/prompt_generator.py
- ols/src/prompts/prompts.py
- ols/src/query_helpers/docs_summarizer.py
- ols/src/tools/__init__.py
- ols/src/tools/tools.py
- tests/config/operator_install/olsconfig.crd.azure_openai_introspection.yaml
- tests/config/operator_install/olsconfig.crd.openai_introspection.yaml
- tests/config/operator_install/olsconfig.crd.watsonx_introspection.yaml
- tests/e2e/pytest.ini
- tests/e2e/test_api.py
- tests/e2e/test_query_endpoint.py
- tests/e2e/utils/ols_installer.py
- tests/integration/test_ols.py
- tests/mock_classes/mock_llm_loader.py
- tests/mock_classes/mock_tools.py
- tests/mock_classes/mock_watsonxllm.py
- tests/scripts/test-e2e-cluster.sh
- tests/scripts/utils.sh
- tests/unit/app/models/test_config.py
- tests/unit/llms/providers/test_watsonx.py
- tests/unit/query_helpers/test_docs_summarizer.py
Change Summary
* [OLS-1383](https://issues.redhat.com/browse/OLS-1383)
* Add a flag to the config to enable introspection
* [OLS-1373](https://issues.redhat.com//browse/OLS-1373)
* Add sample tool with mock output
* Tool calling in a loop when introspection flag is enabled
* Stop the loop when max iteration is reached or model gives final response.
* Existing flow when flag is False.
* Minor modification to prompt when tool calling is enabled
* Modify watsonx model class to handle bind_tools
* some refactoring
* [OLS-1288](https://issues.redhat.com/browse/OLS-1288)
* Use langchain runnable instead of LLMChain (Didn't change query validator, as we need to remove the logic)
* e2e test case
* Added different suite with different marker for tool calling e2e test case. Currently commented …
> feat: enable tool calling in a loop

- ols/app/endpoints/authorized.py
- ols/app/endpoints/ols.py
- ols/app/endpoints/streaming_ols.py
- ols/constants.py
- ols/src/auth/auth_dependency_interface.py
- ols/src/auth/k8s.py
- ols/src/auth/noop.py
- tests/unit/app/endpoints/test_ols.py
- tests/unit/auth/test_k8s.py
- tests/unit/auth/test_noop_auth_dependency.py
Forward user's token for future use in agent/tool
> OLS-1379: Forward user's token

- README.md
- pyproject.toml
[OLS-1460](https://issues.redhat.com//browse/OLS-1460): Allow Python 3.13 to be used
- Related Issue #[OLS-1460](https://issues.redhat.com//browse/OLS-1460)
> OLS-1460: Allow Python 3.13 to be used

- ols/app/endpoints/health.py
- ols/src/cache/cache.py
- ols/src/cache/in_memory_cache.py
- ols/src/cache/postgres_cache.py
- ols/src/cache/redis_cache.py
- tests/mock_classes/mock_redis_client.py
- tests/unit/app/endpoints/test_health.py
- tests/unit/cache/test_in_memory_cache.py
- tests/unit/cache/test_postgres_cache.py
- tests/unit/cache/test_redis_cache.py
readiness probe checks cache state
- Closes # [OLS-670](https://issues.redhat.com//browse/OLS-670)
> OLS-670: readiness probe checks cache state

- Containerfile
- build.args
Use the Konflux-built RAG image in both Konflux and Prow environments.
- Related Issue # https://issues.redhat.com/browse/OLS-1515
- Closes # 
> OLS-1515: Stop building RAG in Prow

- tests/e2e/test_streaming_query_endpoint.py
[OLS-1521](https://issues.redhat.com//browse/OLS-1521): Switch to new granite-3-8b-instruct model from IBM
- Related Issue #[OLS-1521](https://issues.redhat.com//browse/OLS-1521)
> OLS-1521: Switch to new granite-3-8b-instruct model from IBM

- tests/unit/quota/test_cluster_quota_limiter.py
- tests/unit/quota/test_quota_limiter_factory.py
- tests/unit/quota/test_user_quota_limiter.py
Remove mock connect decorator from quota unit tests
> OLS-1519: Remove mock connect decorator from quota unit tests

- tests/unit/cache/test_cache_factory.py
- tests/unit/cache/test_postgres_cache.py
Remove mock connect decorator from cache unit tests
Also added missing tests
> OLS-1519: Remove mock connect decorator from cache unit tests

- tests/integration/test_authorized.py
- tests/integration/test_ols.py
- tests/integration/test_runners.py
[OLS-1519](https://issues.redhat.com//browse/OLS-1519): no `@patch` decorators in integration tests
> OLS-1519: no patch decorators in integration tests

- tests/benchmarks/test_docs_summarizer.py
- tests/benchmarks/test_question_validator.py
[OLS-1519](https://issues.redhat.com//browse/OLS-1519): no `@patch` decorators in benchmarks
> OLS-1519: no @patch decorators in benchmarks

- tests/integration/test_liveness_readiness.py
- tests/integration/test_metrics.py
- tests/integration/test_openapi.py
- tests/unit/query_helpers/test_docs_summarizer.py
- tests/unit/query_helpers/test_question_validator.py
- tests/unit/rag_index/test_index_loader.py
- tests/unit/runners/test_quota_scheduler_runner.py
- tests/unit/runners/test_uvicorn_runner.py
[OLS-1519](https://issues.redhat.com//browse/OLS-1519): no `@patch` decorator in unit and integration tests
> OLS-1519: no @patch decorator in unit and integration tests

- tests/unit/llms/providers/test_azure_openai.py
- tests/unit/llms/providers/test_watsonx.py
- tests/unit/llms/test_llm_loader.py
- tests/unit/utils/test_config.py
- tests/unit/utils/test_environments.py
[OLS-1519](https://issues.redhat.com//browse/OLS-1519): Removed all remained `@patch` decorators from unit tests
> OLS-1519: Removed all remained @patch decorators from unit tests

- .tekton/lightspeed-service-pull-request.yaml
- .tekton/lightspeed-service-push.yaml
- Containerfile
- Makefile
Moved the RAG content Konflux component into its own application, which  changed the URL of the produced RAG image.
- Related Issue # https://issues.redhat.com/browse/OLS-1304
- Closes #
> OLS-1304: Build rag image in a separate konflux application to avoid EC failures in other repos

- ols/src/query_helpers/docs_summarizer.py
- ols/src/tools/oc_cli.py
- ols/src/tools/tools.py
- tests/e2e/test_query_endpoint.py
- tests/e2e/utils/ols_installer.py
- tests/scripts/test-e2e-cluster.sh
- tests/unit/tools/test_oc_cli.py
- tests/unit/tools/test_tools.py
Enable introspection E2E test
- Remove oc server arg.
- Use InjectedToolArg for token arg (nothing for LLM to figure out).
- Remove langchain's debug (leaks token).
- Closes #
> OLS-1408: Enable introspection e2e

- ols/app/endpoints/health.py
- ols/app/endpoints/ols.py
- ols/src/llms/llm_loader.py
- ols/src/llms/providers/provider.py
- ols/src/query_helpers/docs_summarizer.py
- ols/src/query_helpers/query_helper.py
- ols/src/query_helpers/question_validator.py
- tests/unit/llms/providers/test_providers.py
- tests/unit/query_helpers/test_docs_summarizer.py
- tests/unit/query_helpers/test_query_helper.py
- tests/unit/query_helpers/test_question_validator.py
We don't need this option. It have no effect as the non-streaming/streaming depends on `docs_summarizer` method selected - create_response (non-streaming) or generate_response (streaming).
- Closes #
> OLS-1454: Remove streaming parameter from providers

- rpms.lock.yaml
- ubi.repo
address the EC check failure about unknown RPM repository ID as shown below:
```
ImageRef: quay.io/redhat-user-workloads/crt-nshift-lightspeed-tenant/ols/lightspeed-service@sha256:dfacbb51fbc4e084a4527c40fd75b829321edf201c738d826d79b17536d6f70c
Reason: RPM repo id check failed: An RPM component in the SBOM specified an unknown or disallowed repository_id:
pkg:rpm/redhat/libnsl2@2.0.0-1.el9?arch=x86_64&checksum=sha256:052f7a182180528ba6e3c4378e5dcfb84640594a3e2e7bbe4f0167381e824ce0&repository_id=ubi-9-appstream-rpms
```
similar to this change https://gitlab.cee.redhat.com/aap-konflux/aap-konflux-pipelines/-/merge_requests/66/diffs#d7cbad7ed11c136dbcd8de350eec5b29cf0d4336 as suggested by konflux team.
- Closes #
- Please provide detailed steps to perform tests related to …
> rename ubi9 repos to conform with EC rules

- ols/src/prompts/prompt_generator.py
- ols/src/prompts/prompts.py
- ols/src/query_helpers/docs_summarizer.py
- ols/src/tools/oc_cli.py
- ols/src/tools/tools.py
- ols/utils/token_handler.py
- scripts/evaluation/eval_data/question_answer_pair.json
- scripts/evaluation/utils/rag.py
- tests/benchmarks/test_token_handler.py
- tests/config/operator_install/olsconfig.crd.watsonx_introspection.yaml
- tests/e2e/test_query_endpoint.py
- tests/integration/test_ols.py
- tests/scripts/test-e2e-cluster.sh
- tests/unit/prompts/test_prompt_generator.py
- tests/unit/query_helpers/test_docs_summarizer.py
- tests/unit/tools/test_oc_cli.py
- tests/unit/utils/test_token_handler.py
- Different prompt for Granite tool call.
- Removed unnecessary new-lines during prompt generation
- Removed special tag (granite-2 specific) addition to the prompt. (This will be taken care by the packages)
- Tool doc string modification to make it easier for granite.
- Temporarily added processing of tool arguments to handle scenarios where granite gives additional args.
- Use latest granite model for tool calling
- Simplified token calculation.
Note: Initially the plan was to add special tags/processing for granite. But it is not required now.
[OLS-1497](https://issues.redhat.com//browse/OLS-1497)
> Remove special formatting of the prompt

- ols/src/query_helpers/docs_summarizer.py
Temporary fix for fake-llm (load test) which gives output as string.
Currently every method that we use gives us proper output, except fake-llm.
We need to move to a different fake-llm (or custom fake-llm) which can handle streaming/non-streaming & tool calling and gives response not as string.
Even this temp fix will fail for tool calling. (load test can be run with tool calling set to False till we have a permanent fix)
[Discussion next-steps.](https://redhat-internal.slack.com/archives/C068JAU4Y0P/p1742968057080699?thread_ts=1742906110.101449&cid=C068JAU4Y0P)
> load-test: temp fix for fake-llm output format

- tests/e2e/test_query_endpoint.py
OpenAI tool calling test case started failing.
Surprisingly it works if we remove the `?` in query. GPT is not supposed to be so fragile though.
Perhaps there is a better solution, but for time being it fixes the issue.
> change tool calling query

- ols/src/llms/providers/azure_openai.py
- ols/src/llms/providers/openai.py
- ols/src/llms/providers/provider.py
- ols/src/llms/providers/rhelai_vllm.py
- ols/src/llms/providers/rhoai_vllm.py
- tests/unit/llms/providers/test_openai.py
- tests/unit/llms/providers/test_providers.py
- tests/unit/llms/providers/test_rhelai_vllm.py
- tests/unit/llms/providers/test_rhoai_vllm.py
Streaming endpoints use non-blocking astream API to connect to model providers . FIx adds the custom trust store to ssl_context and adds http_async_client parameter per https://python.langchain.com/api_reference/openai/chat_models/langchain_openai.chat_models.base.BaseChatOpenAI.html
- Related Issue [#](https://issues.redhat.com/browse/OLS-1527)
- Closes #
> add http_async_client for async invocations

- pdm.lock
- pyproject.toml
[OLS-1612](https://issues.redhat.com//browse/OLS-1612): Bump-up ibm-watson-ai to version 1.3.6
- Related Issue #[OLS-1612](https://issues.redhat.com//browse/OLS-1612)
> OLS-1612: Bump-up ibm-watson-ai to version 1.3.6

- tests/scripts/test-e2e-cluster.sh
Disable openai/watsonx introspection test suites temporarily due to some flakiness..
Once the issue is resolved these will be enabled again..
Periodic run still has these.
There are already two PRs for immediate fix.. rerunning test cases for those PRs multiple times to make sure that flakiness has reduced..
https://github.com/openshift/lightspeed-service/pull/2454
https://github.com/openshift/lightspeed-service/pull/2447
[OLS-1657](https://issues.redhat.com//browse/OLS-1657)
> disable openai/watsonx introspection test suites temporarily

- ols/app/models/config.py
- tests/config/config_for_integration_tests.yaml
- tests/config/valid_config.yaml
- tests/unit/app/models/test_config.py
- tests/unit/utils/test_config.py
Changes:
- use pure pydantic capabilities for config definition
- remove code and methods that were re-implementing what pydantic is already doing
- matching yaml definition - no internal conversions
- type Literal expects the value and not variable (not sure what to do with those constants)
Config changes:
sse - `url` is required, the rest is optional
stdio - `command` and `args` are required, the rest if optional
stdio - `args` are actually a list, not string
- Closes #
> Refactor mcp server config

- tests/e2e/test_query_endpoint.py
- tests/e2e/test_streaming_query_endpoint.py
- tests/scripts/test-e2e-cluster.sh
openai/gpt-4o-mini currently rejects tool calling e2e query as non-ocp.
Prompt modification can be done, but it seems like model quality is the issue as same query is successful with azure/gpt-4o-mini.
So far the actual reason seems to be model is getting confused with the given context.
Modify e2e query to make it more obvious for openai/gpt to do a tool call.
Granite also fails to summarize sometime. This is more related to model flakiness as most of the time it is successful. So adding alternate assert statement.
Enable previously commented test suites.
[OLS-1657](https://issues.redhat.com//browse/OLS-1657)
> fix: introspection e2e flakiness

- ols/app/endpoints/feedback.py
Use `Annotated` in feedback endpoint handler
The [FastAPI documentation](https://fastapi.tiangolo.com/tutorial/query-params-str-validations/?h=annotated#advantages-of-annotated) recommends the use of [typing.Annotated](https://docs.python.org/3/library/typing.html#typing.Annotated) for defining route dependencies and parameters, rather than using Depends, Query or similar as a default value for a parameter. Using this approach everywhere helps ensure consistency and clarity in defining dependencies and parameters.
> Use Annotated in feedback endpoint handler

- .tekton/lightspeed-service-push.yaml
stop nudging catalog files, because catalog should be updated from bundle not only image references.
- Closes #
> conf: konflux nudge ignore FBC

- ols/app/models/config.py
- ols/src/llms/providers/openai.py
- tests/unit/llms/providers/test_openai.py
An OpenAI provider can be configured with a custom url. If the configured endpoint is secured with a self signed certificate, as in the case of locally hosted OpenAI compatible providers, a trust configuration needs to be applied.
This PR enables the OpenAI provider to use a custom ca the same way as the RHELAI and RHOAI Providers.
An OpenAI provider can be configured with a custom url. If the configured endpoint is secured with a self signed certificate, as in the case of locally hosted OpenAI compatible providers, a trust configuration needs to be applied.
This PR enables the OpenAI provider to use a custom ca the same way as the RHELAI and RHOAI Providers.
- Related Issue #  [OLS-1715](https://issues.redhat.com//browse/OLS-1715)
- Closes #
- Please provide detailed steps to perform …
> OLS-1715: openai provider allow custom CA

- ols/app/models/config.py
- ols/src/llms/providers/provider.py
- ols/utils/config.py
- tests/unit/app/models/test_config.py
Add a new option to configure CA certificate of HTTPS proxy. This allows the lightspeed backend to connect to external server ,such as LLM provider, through a TLS introspection HTTPS proxy, not only through a transparent proxy. 
This PR does not need synchronize with the operator side.
The operator side PR: https://github.com/openshift/lightspeed-operator/pull/702
- Related Issue # [OLS-1176](https://issues.redhat.com//browse/OLS-1176)
- Closes #
> OLS-1176: add option to configure CA certificate of HTTPS proxy

- ols/src/quota/cluster_quota_limiter.py
- ols/src/quota/quota_limiter.py
- ols/src/quota/revokable_quota_limiter.py
- ols/src/quota/token_usage_history.py
- ols/src/quota/user_quota_limiter.py
[OLS-1714](https://issues.redhat.com//browse/OLS-1714): reconnect PostgreSQL quota DB when tables are deleted
- Related Issue #[OLS-1714](https://issues.redhat.com//browse/OLS-1714)
> OLS-1714: reconnect PostgreSQL quota DB when tables are deleted

- mcp_local/openshift.py
- ols/src/query_helpers/docs_summarizer.py
- tests/e2e/test_query_endpoint.py
- tests/e2e/test_streaming_query_endpoint.py
- tests/mcp_local/test_openshift.py
- Enable langchain debug (now that we are handling tokens better)
- Create MCP client connection per user request rather than per iteration.
- Raise exception when we skip OC command execution due to some validation. 
- Raise exception when OC command fails, so that status in host can be error.
- handle <tool_call> text (for granite)
> tool calling: fixes & improvements

- ols/app/models/config.py
- tests/unit/app/models/test_config.py
The RAG index loader will use the default version of the RAG index if the assigned version path is not available.
This is a special case for OCP documentation RAGs.
This will work together with this PR on [the RAG content side](https://github.com/openshift/lightspeed-rag-content/pull/346).
- Related Issue # [OLS-1340](https://issues.redhat.com//browse/OLS-1340)
- Closes #
> OLS-1340: use default version of OCP docs RAG if the current version is not available

- ols/src/rag_index/index_loader.py
- tests/unit/rag_index/test_index_loader.py
Override query fusion class to use weights as it is instead of normalized weighted score.
This is currently an experimental/easy work-around to prioritize indexes.
> add custom weights to rag indexes

- ols/app/models/config.py
- ols/src/llms/providers/provider.py
- tests/unit/app/models/test_config.py
fix the proxy config incompatible type problem with httpx client
fix the bug that misuse ssl context for http proxy
based on @onmete 's PR https://github.com/openshift/lightspeed-service/pull/2539
Tested valid for the configs below
1. httpS proxy with CA certificate
```yaml
ols_config:
proxy_config:
proxy_url: "https://192.168.2.165:3129"
proxy_ca_cert_path: rootCA.crt
```
2. http proxy
```yaml
ols_config:
proxy_config:
proxy_url: "http://192.168.2.165:3128"
```
3. httpS proxy from env var
```yaml
ols_config:
proxy_config:
proxy_ca_cert_path: rootCA.crt
```
4. http proxy from env var
```shell
https_proxy="https://192.168.2.165:3129"
```
- Closes # [OLS-1808](https://issues.redhat.com//browse/OLS-1808)
- Please provide detailed steps to perform tests related to this code …
> OLS-1808 bugfix: proxy config type error + ignore SSL context for HTTP proxy

- ols/constants.py
4096 is too much, I haven't seen response that big yet.. But it definitely creates problem when people forget to set it properly for smaller model. Reducing it won't resolve the issue completely but error will occur less.
Best solution for this is to make people aware about this through doc.
> reduce max resp token to 2048

- ols/src/cache/postgres_cache.py
- tests/unit/cache/test_postgres_cache.py
[OLS-1835](https://issues.redhat.com//browse/OLS-1835): Service pod fails to connect to the Postgres pod after restart
Added psycopg2.InterfaceError as a possible exception seen when a connection to Postgres is lost.
- Closes # https://issues.redhat.com/browse/OLS-1835
> OLS-1835: Service pod fails to connect to the Postgres pod after restart

- ols/app/models/config.py
- ols/src/query_helpers/docs_summarizer.py
- ols/src/tools/mcp_config_builder.py
- tests/integration/test_ols.py
- tests/unit/app/models/test_config.py
- tests/unit/query_helpers/test_docs_summarizer.py
- tests/unit/tools/test_mcp_config_builder.py
Implements user-token auth through header.
**How to test locally**
0. get the cluster, do `oc login` and store the kubeconfig `oc config view --raw > <kubeconfig_path>`
1. start the mcp server via `npx kubernetes-mcp-server@latest --sse-port 8090 --kubeconfig <kubeconfig_path>`
2. start ols service with this config
```yaml
ols_config:
authentication_config:
    module: "noop-with-token"
    ...
mcp_servers:
- name: k8s-mcp
transport: sse
sse:
url: "http://localhost:8090/sse"
```
3. prompt through
```bash
curl -X POST http://localhost:8080/v1/query -H "Content-Type: application/json" -H "Authorization: Bearer sha256~blabla" -d '{"query": "Is there openshift-lightspeed namespace in my openshift 4 cluster?"}'
```
> OLS-1800: Add auth header for sse mcp config

- ols/constants.py
keeping async timeout really high till it gets configurable. (some model inference server takes significantly more time to respond)
> async timeout increase

- Makefile
possible this was user error, but previously this target attempted to run setuptools (to check the version) before running the pdm install command that actually installs setuptools, so it was always failing for me.  It might have worked for people who had manually installed setuptools previously.
I'm not entirely sure this output is useful, so an alternative PR would be to just delete the invocation entirely. let me know if you'd prefer that.
here's the output seen with this change:
```
pdm show setuptools
Name:                  setuptools                                                         
Latest version:        80.9.0                                                             
Latest stable version: 80.9.0                                                             
Installed …
```
> Fix displaying setuptools version in make install-tools

- ols/src/query_helpers/docs_summarizer.py
When OLS service cannot reach to MCP server , it returns `An error occurred during LLM invocation. Please contact your OpenShift Lightspeed administrator.: unhandled errors in a TaskGroup (1 sub-exception)`
Log MCP connection error and use no tools if there is no MCP available. 
- Closes #
>  log MCP connection error and go with no tools

- ols/src/llms/providers/azure_openai.py
- ols/src/llms/providers/openai.py
- tests/unit/llms/providers/test_azure_openai.py
- tests/unit/llms/providers/test_openai.py
remove temperature, top_p and frequency_penalty for gpt-5 & o-series models
Note
I have only tested with openai/o3-mini, remaining I am unable to test as those requires deployment (azure), openai/gpt-5 requires org level change (`Your organization must be verified to stream this model. Please go to: https://platform.openai.com/settings/organization/general and click on Verify Organization.`)
[OLS-2041](https://issues.redhat.com/browse/OLS-2041)
> parameter adjustment for gpt5 and o-series model

- ols/app/models/config.py
- ols/user_data_collection/data_collector.py
Instead of providing offline token and using RH endpoint to get the ingress stage auth token, we provide the token directly from our vault.
This affects ONLY how the token is provided to our CI - ingress stage env.
The same token will be expected in the new dataverse exporter.
- Closes #
> Fix data collector e2e tests
